INSERT INTO polls_carreer VALUES(1,'Administración de Empresas','T');
INSERT INTO polls_carreer VALUES(2,'Administración de Empresas','C');
INSERT INTO polls_carreer VALUES(3,'Administración de Empresas','S');
INSERT INTO polls_carreer VALUES(4,'Administración de Empresas Agropecuarias','D');
INSERT INTO polls_carreer VALUES(5,'Administración Industrial','D');
INSERT INTO polls_carreer VALUES(6,'Administración Turística y Hotelera','D');
INSERT INTO polls_carreer VALUES(7,'Contaduría Pública','T');
INSERT INTO polls_carreer VALUES(8,'Contaduría Pública','C');
INSERT INTO polls_carreer VALUES(9,'Contaduría Pública','S');
INSERT INTO polls_carreer VALUES(10,'Biología','T');
INSERT INTO polls_carreer VALUES(11,'Derecho','T');
INSERT INTO polls_carreer VALUES(12,'Diseño Industrial','D');
INSERT INTO polls_carreer VALUES(13,'Economía','T');
INSERT INTO polls_carreer VALUES(14,'Enfermería','T');
INSERT INTO polls_carreer VALUES(15,'Física','T');
INSERT INTO polls_carreer VALUES(16,'Ingeniería Agronómica','T');
INSERT INTO polls_carreer VALUES(17,'Ingeniería Ambiental','T');
INSERT INTO polls_carreer VALUES(18,'Ingeniería Civil','T');
INSERT INTO polls_carreer VALUES(19,'Ingeniería Electrónica','T');
INSERT INTO polls_carreer VALUES(20,'Ingeniería Electrónica','S');
INSERT INTO polls_carreer VALUES(21,'Ingeniería Electromecánica','D');
INSERT INTO polls_carreer VALUES(22,'Ingeniería Geológica','S');
INSERT INTO polls_carreer VALUES(23,'Ingeniería Industrial','S');
INSERT INTO polls_carreer VALUES(24,'Ingeniería Metalúrgica','T');
INSERT INTO polls_carreer VALUES(25,'Ingeniería de Minas','S');
INSERT INTO polls_carreer VALUES(26,'Ingeniería de Sistemas y Computación','T');
INSERT INTO polls_carreer VALUES(27,'Ingeniería de Sistemas y Computación','S');
INSERT INTO polls_carreer VALUES(28,'Ingeniería de Transporte y Vías','T');
INSERT INTO polls_carreer VALUES(29,'Licenciatura en Artes Plásticas','T');
INSERT INTO polls_carreer VALUES(30,'Licenciatura en Ciencias Naturales y Educación Ambiental','T');
INSERT INTO polls_carreer VALUES(31,'Licenciatura en Ciencias Sociales','T');
INSERT INTO polls_carreer VALUES(32,'Licenciatura en Educación Básica con énfasis en Matemática, Humanidades y Lengua Castellana','T');
INSERT INTO polls_carreer VALUES(33,'Licenciatura en Educación Física, Recreación y Deporte','T');
INSERT INTO polls_carreer VALUES(34,'Licenciatura en Educación Física, Recreación y Deporte','C');
INSERT INTO polls_carreer VALUES(35,'Licenciatura en Filosofía','T');
INSERT INTO polls_carreer VALUES(36,'Licenciatura en Educación Preescolar','T');
INSERT INTO polls_carreer VALUES(37,'Licenciatura en Idiomas Modernos Español','T');
INSERT INTO polls_carreer VALUES(38,'Licenciatura en Informática y Tecnología','T');
INSERT INTO polls_carreer VALUES(39,'Licenciatura en Lenguas Extranjeras','T');
INSERT INTO polls_carreer VALUES(40,'Licenciatura en Matemáticas','T');
INSERT INTO polls_carreer VALUES(41,'Licenciatura en Matemáticas y Estadística','D');
INSERT INTO polls_carreer VALUES(42,'Licenciatura en Música','T');
INSERT INTO polls_carreer VALUES(43,'Licenciatura en Psicopedagogía énfasis en Asesoría Educativa','T');
INSERT INTO polls_carreer VALUES(44,'Licenciatura en Tecnología','D');
INSERT INTO polls_carreer VALUES(45,'Matemáticas','T');
INSERT INTO polls_carreer VALUES(46,'Medicina','T');
INSERT INTO polls_carreer VALUES(47,'Medicina Veterinaria y Zootecnia','T');
INSERT INTO polls_carreer VALUES(48,'Psicología','T');
INSERT INTO polls_carreer VALUES(49,'Química','T');



INSERT INTO polls_departamento VALUES(1,'AMAZONAS');
INSERT INTO polls_departamento VALUES(2,'ANTIOQUIA');
INSERT INTO polls_departamento VALUES(3,'ARAUCA');
INSERT INTO polls_departamento VALUES(4,'ATLÁNTICO');
INSERT INTO polls_departamento VALUES(5,'BOLÍVAR');
INSERT INTO polls_departamento VALUES(6,'BOYACÁ');
INSERT INTO polls_departamento VALUES(7,'CALDAS');
INSERT INTO polls_departamento VALUES(8,'CAQUETÁ');
INSERT INTO polls_departamento VALUES(9,'CASANARE');
INSERT INTO polls_departamento VALUES(10,'CAUCA');
INSERT INTO polls_departamento VALUES(11,'CESAR');
INSERT INTO polls_departamento VALUES(12,'CHOCÓ');
INSERT INTO polls_departamento VALUES(13,'CÓRDOBA');
INSERT INTO polls_departamento VALUES(14,'CUNDINAMARCA');
INSERT INTO polls_departamento VALUES(15,'GUAINÍA');
INSERT INTO polls_departamento VALUES(16,'GUAVIARE');
INSERT INTO polls_departamento VALUES(17,'HUILA');
INSERT INTO polls_departamento VALUES(18,'LA GUAJIRA');
INSERT INTO polls_departamento VALUES(19,'MAGDALENA');
INSERT INTO polls_departamento VALUES(20,'META');
INSERT INTO polls_departamento VALUES(21,'NARIÑO');
INSERT INTO polls_departamento VALUES(22,'NORTE DE SANTANDER');
INSERT INTO polls_departamento VALUES(23,'PUTUMAYO');
INSERT INTO polls_departamento VALUES(24,'QUINDÍO');
INSERT INTO polls_departamento VALUES(25,'RISARALDA');
INSERT INTO polls_departamento VALUES(26,'SAN ANDRÉS Y PROVIDENCIA');
INSERT INTO polls_departamento VALUES(27,'SANTANDER');
INSERT INTO polls_departamento VALUES(28,'SUCRE');
INSERT INTO polls_departamento VALUES(29,'TOLIMA');
INSERT INTO polls_departamento VALUES(30,'VALLE DEL CAUCA');
INSERT INTO polls_departamento VALUES(31,'VAUPÉS');
INSERT INTO polls_departamento VALUES(32,'VICHADA');




INSERT INTO polls_municipio VALUES(1,'EL ENCANTO',1);
INSERT INTO polls_municipio VALUES(2,'LA CHORRERA',1);
INSERT INTO polls_municipio VALUES(3,'LA PEDRERA',1);
INSERT INTO polls_municipio VALUES(4,'LA VICTORIA',1);
INSERT INTO polls_municipio VALUES(5,'LETICIA',1);
INSERT INTO polls_municipio VALUES(6,'MIRITI',1);
INSERT INTO polls_municipio VALUES(7,'PUERTO ALEGRIA',1);
INSERT INTO polls_municipio VALUES(8,'PUERTO ARICA',1);
INSERT INTO polls_municipio VALUES(9,'PUERTO NARIÑO',1);
INSERT INTO polls_municipio VALUES(10,'PUERTO SANTANDER',1);
INSERT INTO polls_municipio VALUES(11,'TURAPACA',1);
INSERT INTO polls_municipio VALUES(12,'ABEJORRAL',2);
INSERT INTO polls_municipio VALUES(13,'ABRIAQUI',2);
INSERT INTO polls_municipio VALUES(14,'ALEJANDRIA',2);
INSERT INTO polls_municipio VALUES(15,'AMAGA',2);
INSERT INTO polls_municipio VALUES(16,'AMALFI',2);
INSERT INTO polls_municipio VALUES(17,'ANDES',2);
INSERT INTO polls_municipio VALUES(18,'ANGELOPOLIS',2);
INSERT INTO polls_municipio VALUES(19,'ANGOSTURA',2);
INSERT INTO polls_municipio VALUES(20,'ANORI',2);
INSERT INTO polls_municipio VALUES(21,'ANTIOQUIA',2);
INSERT INTO polls_municipio VALUES(22,'ANZA',2);
INSERT INTO polls_municipio VALUES(23,'APARTADO',2);
INSERT INTO polls_municipio VALUES(24,'ARBOLETES',2);
INSERT INTO polls_municipio VALUES(25,'ARGELIA',2);
INSERT INTO polls_municipio VALUES(26,'ARMENIA',2);
INSERT INTO polls_municipio VALUES(27,'BARBOSA',2);
INSERT INTO polls_municipio VALUES(28,'BELLO',2);
INSERT INTO polls_municipio VALUES(29,'BELMIRA',2);
INSERT INTO polls_municipio VALUES(30,'BETANIA',2);
INSERT INTO polls_municipio VALUES(31,'BETULIA',2);
INSERT INTO polls_municipio VALUES(32,'BOLIVAR',2);
INSERT INTO polls_municipio VALUES(33,'BRICEÑO',2);
INSERT INTO polls_municipio VALUES(34,'BURITICA',2);
INSERT INTO polls_municipio VALUES(35,'CACERES',2);
INSERT INTO polls_municipio VALUES(36,'CAICEDO',2);
INSERT INTO polls_municipio VALUES(37,'CALDAS',2);
INSERT INTO polls_municipio VALUES(38,'CAMPAMENTO',2);
INSERT INTO polls_municipio VALUES(39,'CANASGORDAS',2);
INSERT INTO polls_municipio VALUES(40,'CARACOLI',2);
INSERT INTO polls_municipio VALUES(41,'CARAMANTA',2);
INSERT INTO polls_municipio VALUES(42,'CAREPA',2);
INSERT INTO polls_municipio VALUES(43,'CARMEN DE VIBORAL',2);
INSERT INTO polls_municipio VALUES(44,'CAROLINA DEL PRINCIPE',2);
INSERT INTO polls_municipio VALUES(45,'CAUCASIA',2);
INSERT INTO polls_municipio VALUES(46,'CHIGORODO',2);
INSERT INTO polls_municipio VALUES(47,'CISNEROS',2);
INSERT INTO polls_municipio VALUES(48,'COCORNA',2);
INSERT INTO polls_municipio VALUES(49,'CONCEPCION',2);
INSERT INTO polls_municipio VALUES(50,'CONCORDIA',2);
INSERT INTO polls_municipio VALUES(51,'COPACABANA',2);
INSERT INTO polls_municipio VALUES(52,'DABEIBA',2);
INSERT INTO polls_municipio VALUES(53,'DONMATIAS',2);
INSERT INTO polls_municipio VALUES(54,'EBEJICO',2);
INSERT INTO polls_municipio VALUES(55,'EL BAGRE',2);
INSERT INTO polls_municipio VALUES(56,'EL PENOL',2);
INSERT INTO polls_municipio VALUES(57,'EL RETIRO',2);
INSERT INTO polls_municipio VALUES(58,'ENTRERRIOS',2);
INSERT INTO polls_municipio VALUES(59,'ENVIGADO',2);
INSERT INTO polls_municipio VALUES(60,'FREDONIA',2);
INSERT INTO polls_municipio VALUES(61,'FRONTINO',2);
INSERT INTO polls_municipio VALUES(62,'GIRALDO',2);
INSERT INTO polls_municipio VALUES(63,'GIRARDOTA',2);
INSERT INTO polls_municipio VALUES(64,'GOMEZ PLATA',2);
INSERT INTO polls_municipio VALUES(65,'GRANADA',2);
INSERT INTO polls_municipio VALUES(66,'GUADALUPE',2);
INSERT INTO polls_municipio VALUES(67,'GUARNE',2);
INSERT INTO polls_municipio VALUES(68,'GUATAQUE',2);
INSERT INTO polls_municipio VALUES(69,'HELICONIA',2);
INSERT INTO polls_municipio VALUES(70,'HISPANIA',2);
INSERT INTO polls_municipio VALUES(71,'ITAGUI',2);
INSERT INTO polls_municipio VALUES(72,'ITUANGO',2);
INSERT INTO polls_municipio VALUES(73,'JARDIN',2);
INSERT INTO polls_municipio VALUES(74,'JERICO',2);
INSERT INTO polls_municipio VALUES(75,'LA CEJA',2);
INSERT INTO polls_municipio VALUES(76,'LA ESTRELLA',2);
INSERT INTO polls_municipio VALUES(77,'LA PINTADA',2);
INSERT INTO polls_municipio VALUES(78,'LA UNION',2);
INSERT INTO polls_municipio VALUES(79,'LIBORINA',2);
INSERT INTO polls_municipio VALUES(80,'MACEO',2);
INSERT INTO polls_municipio VALUES(81,'MARINILLA',2);
INSERT INTO polls_municipio VALUES(82,'MEDELLIN',2);
INSERT INTO polls_municipio VALUES(83,'MONTEBELLO',2);
INSERT INTO polls_municipio VALUES(84,'MURINDO',2);
INSERT INTO polls_municipio VALUES(85,'MUTATA',2);
INSERT INTO polls_municipio VALUES(86,'NARINO',2);
INSERT INTO polls_municipio VALUES(87,'NECHI',2);
INSERT INTO polls_municipio VALUES(88,'NECOCLI',2);
INSERT INTO polls_municipio VALUES(89,'OLAYA',2);
INSERT INTO polls_municipio VALUES(90,'PEQUE',2);
INSERT INTO polls_municipio VALUES(91,'PUEBLORRICO',2);
INSERT INTO polls_municipio VALUES(92,'PUERTO BERRIO',2);
INSERT INTO polls_municipio VALUES(93,'PUERTO NARE',2);
INSERT INTO polls_municipio VALUES(94,'PUERTO TRIUNFO',2);
INSERT INTO polls_municipio VALUES(95,'REMEDIOS',2);
INSERT INTO polls_municipio VALUES(96,'RIONEGRO',2);
INSERT INTO polls_municipio VALUES(97,'SABANALARGA',2);
INSERT INTO polls_municipio VALUES(98,'SABANETA',2);
INSERT INTO polls_municipio VALUES(99,'SALGAR',2);
INSERT INTO polls_municipio VALUES(100,'SAN ANDRES DE CUERQUIA',2);
INSERT INTO polls_municipio VALUES(101,'SAN CARLOS',2);
INSERT INTO polls_municipio VALUES(102,'SAN FRANCISCO',2);
INSERT INTO polls_municipio VALUES(103,'SAN JERONIMO',2);
INSERT INTO polls_municipio VALUES(104,'SAN JOSE DE LA MONTAÑA',2);
INSERT INTO polls_municipio VALUES(105,'SAN JUAN DE URABA',2);
INSERT INTO polls_municipio VALUES(106,'SAN LUIS',2);
INSERT INTO polls_municipio VALUES(107,'SAN PEDRO DE LOS MILAGROS',2);
INSERT INTO polls_municipio VALUES(108,'SAN PEDRO DE URABA',2);
INSERT INTO polls_municipio VALUES(109,'SAN RAFAEL',2);
INSERT INTO polls_municipio VALUES(110,'SAN ROQUE',2);
INSERT INTO polls_municipio VALUES(111,'SAN VICENTE',2);
INSERT INTO polls_municipio VALUES(112,'SANTA BARBARA',2);
INSERT INTO polls_municipio VALUES(113,'SANTA ROSA DE OSOS',2);
INSERT INTO polls_municipio VALUES(114,'SANTO DOMINGO',2);
INSERT INTO polls_municipio VALUES(115,'SANTUARIO',2);
INSERT INTO polls_municipio VALUES(116,'SEGOVIA',2);
INSERT INTO polls_municipio VALUES(117,'SONSON',2);
INSERT INTO polls_municipio VALUES(118,'SOPETRAN',2);
INSERT INTO polls_municipio VALUES(119,'TAMESIS',2);
INSERT INTO polls_municipio VALUES(120,'TARAZA',2);
INSERT INTO polls_municipio VALUES(121,'TARSO',2);
INSERT INTO polls_municipio VALUES(122,'TITIRIBI',2);
INSERT INTO polls_municipio VALUES(123,'TOLEDO',2);
INSERT INTO polls_municipio VALUES(124,'TURBO',2);
INSERT INTO polls_municipio VALUES(125,'URAMITA',2);
INSERT INTO polls_municipio VALUES(126,'URRAO',2);
INSERT INTO polls_municipio VALUES(127,'VALDIVIA',2);
INSERT INTO polls_municipio VALUES(128,'VALPARAISO',2);
INSERT INTO polls_municipio VALUES(129,'VEGACHI',2);
INSERT INTO polls_municipio VALUES(130,'VENECIA',2);
INSERT INTO polls_municipio VALUES(131,'VIGIA DEL FUERTE',2);
INSERT INTO polls_municipio VALUES(132,'YALI',2);
INSERT INTO polls_municipio VALUES(133,'YARUMAL',2);
INSERT INTO polls_municipio VALUES(134,'YOLOMBO',2);
INSERT INTO polls_municipio VALUES(135,'YONDO',2);
INSERT INTO polls_municipio VALUES(136,'ZARAGOZA',2);
INSERT INTO polls_municipio VALUES(137,'ARAUCA',3);
INSERT INTO polls_municipio VALUES(138,'ARAUQUITA',3);
INSERT INTO polls_municipio VALUES(139,'CRAVO NORTE',3);
INSERT INTO polls_municipio VALUES(140,'FORTUL',3);
INSERT INTO polls_municipio VALUES(141,'PUERTO RONDON',3);
INSERT INTO polls_municipio VALUES(142,'SARAVENA',3);
INSERT INTO polls_municipio VALUES(143,'TAME',3);
INSERT INTO polls_municipio VALUES(144,'BARANOA',4);
INSERT INTO polls_municipio VALUES(145,'BARRANQUILLA',4);
INSERT INTO polls_municipio VALUES(146,'CAMPO DE LA CRUZ',4);
INSERT INTO polls_municipio VALUES(147,'CANDELARIA',4);
INSERT INTO polls_municipio VALUES(148,'GALAPA',4);
INSERT INTO polls_municipio VALUES(149,'JUAN DE ACOSTA',4);
INSERT INTO polls_municipio VALUES(150,'LURUACO',4);
INSERT INTO polls_municipio VALUES(151,'MALAMBO',4);
INSERT INTO polls_municipio VALUES(152,'MANATI',4);
INSERT INTO polls_municipio VALUES(153,'PALMAR DE VARELA',4);
INSERT INTO polls_municipio VALUES(154,'PIOJO',4);
INSERT INTO polls_municipio VALUES(155,'POLO NUEVO',4);
INSERT INTO polls_municipio VALUES(156,'PONEDERA',4);
INSERT INTO polls_municipio VALUES(157,'PUERTO COLOMBIA',4);
INSERT INTO polls_municipio VALUES(158,'REPELON',4);
INSERT INTO polls_municipio VALUES(159,'SABANAGRANDE',4);
INSERT INTO polls_municipio VALUES(160,'SABANALARGA',4);
INSERT INTO polls_municipio VALUES(161,'SANTA LUCIA',4);
INSERT INTO polls_municipio VALUES(162,'SANTO TOMAS',4);
INSERT INTO polls_municipio VALUES(163,'SOLEDAD',4);
INSERT INTO polls_municipio VALUES(164,'SUAN',4);
INSERT INTO polls_municipio VALUES(165,'TUBARA',4);
INSERT INTO polls_municipio VALUES(166,'USIACURI',4);
INSERT INTO polls_municipio VALUES(167,'ACHI',5);
INSERT INTO polls_municipio VALUES(168,'ALTOS DEL ROSARIO',5);
INSERT INTO polls_municipio VALUES(169,'ARENAL',5);
INSERT INTO polls_municipio VALUES(170,'ARJONA',5);
INSERT INTO polls_municipio VALUES(171,'ARROYOHONDO',5);
INSERT INTO polls_municipio VALUES(172,'BARRANCO DE LOBA',5);
INSERT INTO polls_municipio VALUES(173,'BRAZUELO DE PAPAYAL',5);
INSERT INTO polls_municipio VALUES(174,'CALAMAR',5);
INSERT INTO polls_municipio VALUES(175,'CANTAGALLO',5);
INSERT INTO polls_municipio VALUES(176,'CARTAGENA DE INDIAS',5);
INSERT INTO polls_municipio VALUES(177,'CICUCO',5);
INSERT INTO polls_municipio VALUES(178,'CLEMENCIA',5);
INSERT INTO polls_municipio VALUES(179,'CORDOBA',5);
INSERT INTO polls_municipio VALUES(180,'EL CARMEN DE BOLIVAR',5);
INSERT INTO polls_municipio VALUES(181,'EL GUAMO',5);
INSERT INTO polls_municipio VALUES(182,'EL PENION',5);
INSERT INTO polls_municipio VALUES(183,'HATILLO DE LOBA',5);
INSERT INTO polls_municipio VALUES(184,'MAGANGUE',5);
INSERT INTO polls_municipio VALUES(185,'MAHATES',5);
INSERT INTO polls_municipio VALUES(186,'MARGARITA',5);
INSERT INTO polls_municipio VALUES(187,'MARIA LA BAJA',5);
INSERT INTO polls_municipio VALUES(188,'MONTECRISTO',5);
INSERT INTO polls_municipio VALUES(189,'MORALES',5);
INSERT INTO polls_municipio VALUES(190,'MORALES',5);
INSERT INTO polls_municipio VALUES(191,'NOROSI',5);
INSERT INTO polls_municipio VALUES(192,'PINILLOS',5);
INSERT INTO polls_municipio VALUES(193,'REGIDOR',5);
INSERT INTO polls_municipio VALUES(194,'RIO VIEJO',5);
INSERT INTO polls_municipio VALUES(195,'SAN CRISTOBAL',5);
INSERT INTO polls_municipio VALUES(196,'SAN ESTANISLAO',5);
INSERT INTO polls_municipio VALUES(197,'SAN FERNANDO',5);
INSERT INTO polls_municipio VALUES(198,'SAN JACINTO',5);
INSERT INTO polls_municipio VALUES(199,'SAN JACINTO DEL CAUCA',5);
INSERT INTO polls_municipio VALUES(200,'SAN JUAN DE NEPOMUCENO',5);
INSERT INTO polls_municipio VALUES(201,'SAN MARTIN DE LOBA',5);
INSERT INTO polls_municipio VALUES(202,'SAN PABLO',5);
INSERT INTO polls_municipio VALUES(203,'SAN PABLO NORTE',5);
INSERT INTO polls_municipio VALUES(204,'SANTA CATALINA',5);
INSERT INTO polls_municipio VALUES(205,'SANTA CRUZ DE MOMPOX',5);
INSERT INTO polls_municipio VALUES(206,'SANTA ROSA',5);
INSERT INTO polls_municipio VALUES(207,'SANTA ROSA DEL SUR',5);
INSERT INTO polls_municipio VALUES(208,'SIMITI',5);
INSERT INTO polls_municipio VALUES(209,'SOPLAVIENTO',5);
INSERT INTO polls_municipio VALUES(210,'TALAIGUA NUEVO',5);
INSERT INTO polls_municipio VALUES(211,'TUQUISIO',5);
INSERT INTO polls_municipio VALUES(212,'TURBACO',5);
INSERT INTO polls_municipio VALUES(213,'TURBANA',5);
INSERT INTO polls_municipio VALUES(214,'VILLANUEVA',5);
INSERT INTO polls_municipio VALUES(215,'ZAMBRANO',5);
INSERT INTO polls_municipio VALUES(216,'AQUITANIA',6);
INSERT INTO polls_municipio VALUES(217,'ARCABUCO',6);
INSERT INTO polls_municipio VALUES(218,'BELÉN',6);
INSERT INTO polls_municipio VALUES(219,'BERBEO',6);
INSERT INTO polls_municipio VALUES(220,'BETÉITIVA',6);
INSERT INTO polls_municipio VALUES(221,'BOAVITA',6);
INSERT INTO polls_municipio VALUES(222,'BOYACÁ',6);
INSERT INTO polls_municipio VALUES(223,'BRICEÑO',6);
INSERT INTO polls_municipio VALUES(224,'BUENAVISTA',6);
INSERT INTO polls_municipio VALUES(225,'BUSBANZÁ',6);
INSERT INTO polls_municipio VALUES(226,'CALDAS',6);
INSERT INTO polls_municipio VALUES(227,'CAMPO HERMOSO',6);
INSERT INTO polls_municipio VALUES(228,'CERINZA',6);
INSERT INTO polls_municipio VALUES(229,'CHINAVITA',6);
INSERT INTO polls_municipio VALUES(230,'CHIQUINQUIRÁ',6);
INSERT INTO polls_municipio VALUES(231,'CHÍQUIZA',6);
INSERT INTO polls_municipio VALUES(232,'CHISCAS',6);
INSERT INTO polls_municipio VALUES(233,'CHITA',6);
INSERT INTO polls_municipio VALUES(234,'CHITARAQUE',6);
INSERT INTO polls_municipio VALUES(235,'CHIVATÁ',6);
INSERT INTO polls_municipio VALUES(236,'CIÉNEGA',6);
INSERT INTO polls_municipio VALUES(237,'CÓMBITA',6);
INSERT INTO polls_municipio VALUES(238,'COPER',6);
INSERT INTO polls_municipio VALUES(239,'CORRALES',6);
INSERT INTO polls_municipio VALUES(240,'COVARACHÍA',6);
INSERT INTO polls_municipio VALUES(241,'CUBARA',6);
INSERT INTO polls_municipio VALUES(242,'CUCAITA',6);
INSERT INTO polls_municipio VALUES(243,'CUITIVA',6);
INSERT INTO polls_municipio VALUES(244,'DUITAMA',6);
INSERT INTO polls_municipio VALUES(245,'EL COCUY',6);
INSERT INTO polls_municipio VALUES(246,'EL ESPINO',6);
INSERT INTO polls_municipio VALUES(247,'FIRAVITOBA',6);
INSERT INTO polls_municipio VALUES(248,'FLORESTA',6);
INSERT INTO polls_municipio VALUES(249,'GACHANTIVÁ',6);
INSERT INTO polls_municipio VALUES(250,'GÁMEZA',6);
INSERT INTO polls_municipio VALUES(251,'GARAGOA',6);
INSERT INTO polls_municipio VALUES(252,'GUACAMAYAS',6);
INSERT INTO polls_municipio VALUES(253,'GÜICÁN',6);
INSERT INTO polls_municipio VALUES(254,'IZA',6);
INSERT INTO polls_municipio VALUES(255,'JENESANO',6);
INSERT INTO polls_municipio VALUES(256,'JERICÓ',6);
INSERT INTO polls_municipio VALUES(257,'LA UVITA',6);
INSERT INTO polls_municipio VALUES(258,'LA VICTORIA',6);
INSERT INTO polls_municipio VALUES(259,'LABRANZA GRANDE',6);
INSERT INTO polls_municipio VALUES(260,'MACANAL',6);
INSERT INTO polls_municipio VALUES(261,'MARIPÍ',6);
INSERT INTO polls_municipio VALUES(262,'MIRAFLORES',6);
INSERT INTO polls_municipio VALUES(263,'MONGUA',6);
INSERT INTO polls_municipio VALUES(264,'MONGUÍ',6);
INSERT INTO polls_municipio VALUES(265,'MONIQUIRÁ',6);
INSERT INTO polls_municipio VALUES(266,'MOTAVITA',6);
INSERT INTO polls_municipio VALUES(267,'MUZO',6);
INSERT INTO polls_municipio VALUES(268,'NOBSA',6);
INSERT INTO polls_municipio VALUES(269,'NUEVO COLÓN',6);
INSERT INTO polls_municipio VALUES(270,'OICATÁ',6);
INSERT INTO polls_municipio VALUES(271,'OTANCHE',6);
INSERT INTO polls_municipio VALUES(272,'PACHAVITA',6);
INSERT INTO polls_municipio VALUES(273,'PÁEZ',6);
INSERT INTO polls_municipio VALUES(274,'PAIPA',6);
INSERT INTO polls_municipio VALUES(275,'PAJARITO',6);
INSERT INTO polls_municipio VALUES(276,'PANQUEBA',6);
INSERT INTO polls_municipio VALUES(277,'PAUNA',6);
INSERT INTO polls_municipio VALUES(278,'PAYA',6);
INSERT INTO polls_municipio VALUES(279,'PAZ DE RÍO',6);
INSERT INTO polls_municipio VALUES(280,'PESCA',6);
INSERT INTO polls_municipio VALUES(281,'PISBA',6);
INSERT INTO polls_municipio VALUES(282,'PUERTO BOYACA',6);
INSERT INTO polls_municipio VALUES(283,'QUÍPAMA',6);
INSERT INTO polls_municipio VALUES(284,'RAMIRIQUÍ',6);
INSERT INTO polls_municipio VALUES(285,'RÁQUIRA',6);
INSERT INTO polls_municipio VALUES(286,'RONDÓN',6);
INSERT INTO polls_municipio VALUES(287,'SABOYÁ',6);
INSERT INTO polls_municipio VALUES(288,'SÁCHICA',6);
INSERT INTO polls_municipio VALUES(289,'SAMACÁ',6);
INSERT INTO polls_municipio VALUES(290,'SAN EDUARDO',6);
INSERT INTO polls_municipio VALUES(291,'SAN JOSÉ DE PARE',6);
INSERT INTO polls_municipio VALUES(292,'SAN LUÍS DE GACENO',6);
INSERT INTO polls_municipio VALUES(293,'SAN MATEO',6);
INSERT INTO polls_municipio VALUES(294,'SAN MIGUEL DE SEMA',6);
INSERT INTO polls_municipio VALUES(295,'SAN PABLO DE BORBUR',6);
INSERT INTO polls_municipio VALUES(296,'SANTA MARÍA',6);
INSERT INTO polls_municipio VALUES(297,'SANTA ROSA DE VITERBO',6);
INSERT INTO polls_municipio VALUES(298,'SANTA SOFÍA',6);
INSERT INTO polls_municipio VALUES(299,'SANTANA',6);
INSERT INTO polls_municipio VALUES(300,'SATIVANORTE',6);
INSERT INTO polls_municipio VALUES(301,'SATIVASUR',6);
INSERT INTO polls_municipio VALUES(302,'SIACHOQUE',6);
INSERT INTO polls_municipio VALUES(303,'SOATÁ',6);
INSERT INTO polls_municipio VALUES(304,'SOCHA',6);
INSERT INTO polls_municipio VALUES(305,'SOCOTÁ',6);
INSERT INTO polls_municipio VALUES(306,'SOGAMOSO',6);
INSERT INTO polls_municipio VALUES(307,'SORA',6);
INSERT INTO polls_municipio VALUES(308,'SORACÁ',6);
INSERT INTO polls_municipio VALUES(309,'SOTAQUIRÁ',6);
INSERT INTO polls_municipio VALUES(310,'SUSACÓN',6);
INSERT INTO polls_municipio VALUES(311,'SUTARMACHÁN',6);
INSERT INTO polls_municipio VALUES(312,'TASCO',6);
INSERT INTO polls_municipio VALUES(313,'TIBANÁ',6);
INSERT INTO polls_municipio VALUES(314,'TIBASOSA',6);
INSERT INTO polls_municipio VALUES(315,'TINJACÁ',6);
INSERT INTO polls_municipio VALUES(316,'TIPACOQUE',6);
INSERT INTO polls_municipio VALUES(317,'TOCA',6);
INSERT INTO polls_municipio VALUES(318,'TOGÜÍ',6);
INSERT INTO polls_municipio VALUES(319,'TÓPAGA',6);
INSERT INTO polls_municipio VALUES(320,'TOTA',6);
INSERT INTO polls_municipio VALUES(321,'TUNJA',6);
INSERT INTO polls_municipio VALUES(322,'TUNUNGUÁ',6);
INSERT INTO polls_municipio VALUES(323,'TURMEQUÉ',6);
INSERT INTO polls_municipio VALUES(324,'TUTA',6);
INSERT INTO polls_municipio VALUES(325,'TUTAZÁ',6);
INSERT INTO polls_municipio VALUES(326,'UMBITA',6);
INSERT INTO polls_municipio VALUES(327,'VENTA QUEMADA',6);
INSERT INTO polls_municipio VALUES(328,'VILLA DE LEYVA',6);
INSERT INTO polls_municipio VALUES(329,'VIRACACHÁ',6);
INSERT INTO polls_municipio VALUES(330,'ZETAQUIRA',6);
INSERT INTO polls_municipio VALUES(331,'AGUADAS',7);
INSERT INTO polls_municipio VALUES(332,'ANSERMA',7);
INSERT INTO polls_municipio VALUES(333,'ARANZAZU',7);
INSERT INTO polls_municipio VALUES(334,'BELALCAZAR',7);
INSERT INTO polls_municipio VALUES(335,'CHINCHINÁ',7);
INSERT INTO polls_municipio VALUES(336,'FILADELFIA',7);
INSERT INTO polls_municipio VALUES(337,'LA DORADA',7);
INSERT INTO polls_municipio VALUES(338,'LA MERCED',7);
INSERT INTO polls_municipio VALUES(339,'MANIZALES',7);
INSERT INTO polls_municipio VALUES(340,'MANZANARES',7);
INSERT INTO polls_municipio VALUES(341,'MARMATO',7);
INSERT INTO polls_municipio VALUES(342,'MARQUETALIA',7);
INSERT INTO polls_municipio VALUES(343,'MARULANDA',7);
INSERT INTO polls_municipio VALUES(344,'NEIRA',7);
INSERT INTO polls_municipio VALUES(345,'NORCASIA',7);
INSERT INTO polls_municipio VALUES(346,'PACORA',7);
INSERT INTO polls_municipio VALUES(347,'PALESTINA',7);
INSERT INTO polls_municipio VALUES(348,'PENSILVANIA',7);
INSERT INTO polls_municipio VALUES(349,'RIOSUCIO',7);
INSERT INTO polls_municipio VALUES(350,'RISARALDA',7);
INSERT INTO polls_municipio VALUES(351,'SALAMINA',7);
INSERT INTO polls_municipio VALUES(352,'SAMANA',7);
INSERT INTO polls_municipio VALUES(353,'SAN JOSE',7);
INSERT INTO polls_municipio VALUES(354,'SUPÍA',7);
INSERT INTO polls_municipio VALUES(355,'VICTORIA',7);
INSERT INTO polls_municipio VALUES(356,'VILLAMARÍA',7);
INSERT INTO polls_municipio VALUES(357,'VITERBO',7);
INSERT INTO polls_municipio VALUES(358,'ALBANIA',8);
INSERT INTO polls_municipio VALUES(359,'BELÉN ANDAQUIES',8);
INSERT INTO polls_municipio VALUES(360,'CARTAGENA DEL CHAIRA',8);
INSERT INTO polls_municipio VALUES(361,'CURILLO',8);
INSERT INTO polls_municipio VALUES(362,'EL DONCELLO',8);
INSERT INTO polls_municipio VALUES(363,'EL PAUJIL',8);
INSERT INTO polls_municipio VALUES(364,'FLORENCIA',8);
INSERT INTO polls_municipio VALUES(365,'LA MONTAÑITA',8);
INSERT INTO polls_municipio VALUES(366,'MILÁN',8);
INSERT INTO polls_municipio VALUES(367,'MORELIA',8);
INSERT INTO polls_municipio VALUES(368,'PUERTO RICO',8);
INSERT INTO polls_municipio VALUES(369,'SAN  VICENTE DEL CAGUAN',8);
INSERT INTO polls_municipio VALUES(370,'SAN JOSÉ DE FRAGUA',8);
INSERT INTO polls_municipio VALUES(371,'SOLANO',8);
INSERT INTO polls_municipio VALUES(372,'SOLITA',8);
INSERT INTO polls_municipio VALUES(373,'VALPARAÍSO',8);
INSERT INTO polls_municipio VALUES(374,'AGUAZUL',9);
INSERT INTO polls_municipio VALUES(375,'CHAMEZA',9);
INSERT INTO polls_municipio VALUES(376,'HATO COROZAL',9);
INSERT INTO polls_municipio VALUES(377,'LA SALINA',9);
INSERT INTO polls_municipio VALUES(378,'MANÍ',9);
INSERT INTO polls_municipio VALUES(379,'MONTERREY',9);
INSERT INTO polls_municipio VALUES(380,'NUNCHIA',9);
INSERT INTO polls_municipio VALUES(381,'OROCUE',9);
INSERT INTO polls_municipio VALUES(382,'PAZ DE ARIPORO',9);
INSERT INTO polls_municipio VALUES(383,'PORE',9);
INSERT INTO polls_municipio VALUES(384,'RECETOR',9);
INSERT INTO polls_municipio VALUES(385,'SABANA LARGA',9);
INSERT INTO polls_municipio VALUES(386,'SACAMA',9);
INSERT INTO polls_municipio VALUES(387,'SAN LUIS DE PALENQUE',9);
INSERT INTO polls_municipio VALUES(388,'TAMARA',9);
INSERT INTO polls_municipio VALUES(389,'TAURAMENA',9);
INSERT INTO polls_municipio VALUES(390,'TRINIDAD',9);
INSERT INTO polls_municipio VALUES(391,'VILLANUEVA',9);
INSERT INTO polls_municipio VALUES(392,'YOPAL',9);
INSERT INTO polls_municipio VALUES(393,'ALMAGUER',10);
INSERT INTO polls_municipio VALUES(394,'ARGELIA',10);
INSERT INTO polls_municipio VALUES(395,'BALBOA',10);
INSERT INTO polls_municipio VALUES(396,'BOLÍVAR',10);
INSERT INTO polls_municipio VALUES(397,'BUENOS AIRES',10);
INSERT INTO polls_municipio VALUES(398,'CAJIBIO',10);
INSERT INTO polls_municipio VALUES(399,'CALDONO',10);
INSERT INTO polls_municipio VALUES(400,'CALOTO',10);
INSERT INTO polls_municipio VALUES(401,'CORINTO',10);
INSERT INTO polls_municipio VALUES(402,'EL TAMBO',10);
INSERT INTO polls_municipio VALUES(403,'FLORENCIA',10);
INSERT INTO polls_municipio VALUES(404,'GUAPI',10);
INSERT INTO polls_municipio VALUES(405,'INZA',10);
INSERT INTO polls_municipio VALUES(406,'JAMBALÓ',10);
INSERT INTO polls_municipio VALUES(407,'LA SIERRA',10);
INSERT INTO polls_municipio VALUES(408,'LA VEGA',10);
INSERT INTO polls_municipio VALUES(409,'LÓPEZ',10);
INSERT INTO polls_municipio VALUES(410,'MERCADERES',10);
INSERT INTO polls_municipio VALUES(411,'MIRANDA',10);
INSERT INTO polls_municipio VALUES(412,'MORALES',10);
INSERT INTO polls_municipio VALUES(413,'PADILLA',10);
INSERT INTO polls_municipio VALUES(414,'PÁEZ',10);
INSERT INTO polls_municipio VALUES(415,'PATIA (EL BORDO)',10);
INSERT INTO polls_municipio VALUES(416,'PIAMONTE',10);
INSERT INTO polls_municipio VALUES(417,'PIENDAMO',10);
INSERT INTO polls_municipio VALUES(418,'POPAYÁN',10);
INSERT INTO polls_municipio VALUES(419,'PUERTO TEJADA',10);
INSERT INTO polls_municipio VALUES(420,'PURACE',10);
INSERT INTO polls_municipio VALUES(421,'ROSAS',10);
INSERT INTO polls_municipio VALUES(422,'SAN SEBASTIÁN',10);
INSERT INTO polls_municipio VALUES(423,'SANTA ROSA',10);
INSERT INTO polls_municipio VALUES(424,'SANTANDER DE QUILICHAO',10);
INSERT INTO polls_municipio VALUES(425,'SILVIA',10);
INSERT INTO polls_municipio VALUES(426,'SOTARA',10);
INSERT INTO polls_municipio VALUES(427,'SUÁREZ',10);
INSERT INTO polls_municipio VALUES(428,'SUCRE',10);
INSERT INTO polls_municipio VALUES(429,'TIMBÍO',10);
INSERT INTO polls_municipio VALUES(430,'TIMBIQUÍ',10);
INSERT INTO polls_municipio VALUES(431,'TORIBIO',10);
INSERT INTO polls_municipio VALUES(432,'TOTORO',10);
INSERT INTO polls_municipio VALUES(433,'VILLA RICA',10);
INSERT INTO polls_municipio VALUES(434,'AGUACHICA',11);
INSERT INTO polls_municipio VALUES(435,'AGUSTÍN CODAZZI',11);
INSERT INTO polls_municipio VALUES(436,'ASTREA',11);
INSERT INTO polls_municipio VALUES(437,'BECERRIL',11);
INSERT INTO polls_municipio VALUES(438,'BOSCONIA',11);
INSERT INTO polls_municipio VALUES(439,'CHIMICHAGUA',11);
INSERT INTO polls_municipio VALUES(440,'CHIRIGUANÁ',11);
INSERT INTO polls_municipio VALUES(441,'CURUMANÍ',11);
INSERT INTO polls_municipio VALUES(442,'EL COPEY',11);
INSERT INTO polls_municipio VALUES(443,'EL PASO',11);
INSERT INTO polls_municipio VALUES(444,'GAMARRA',11);
INSERT INTO polls_municipio VALUES(445,'GONZÁLEZ',11);
INSERT INTO polls_municipio VALUES(446,'LA GLORIA',11);
INSERT INTO polls_municipio VALUES(447,'LA JAGUA IBIRICO',11);
INSERT INTO polls_municipio VALUES(448,'MANAURE BALCÓN DEL CESAR',11);
INSERT INTO polls_municipio VALUES(449,'PAILITAS',11);
INSERT INTO polls_municipio VALUES(450,'PELAYA',11);
INSERT INTO polls_municipio VALUES(451,'PUEBLO BELLO',11);
INSERT INTO polls_municipio VALUES(452,'RÍO DE ORO',11);
INSERT INTO polls_municipio VALUES(453,'ROBLES (LA PAZ)',11);
INSERT INTO polls_municipio VALUES(454,'SAN ALBERTO',11);
INSERT INTO polls_municipio VALUES(455,'SAN DIEGO',11);
INSERT INTO polls_municipio VALUES(456,'SAN MARTÍN',11);
INSERT INTO polls_municipio VALUES(457,'TAMALAMEQUE',11);
INSERT INTO polls_municipio VALUES(458,'VALLEDUPAR',11);
INSERT INTO polls_municipio VALUES(459,'ACANDI',12);
INSERT INTO polls_municipio VALUES(460,'ALTO BAUDO (PIE DE PATO)',12);
INSERT INTO polls_municipio VALUES(461,'ATRATO',12);
INSERT INTO polls_municipio VALUES(462,'BAGADO',12);
INSERT INTO polls_municipio VALUES(463,'BAHIA SOLANO (MUTIS)',12);
INSERT INTO polls_municipio VALUES(464,'BAJO BAUDO (PIZARRO)',12);
INSERT INTO polls_municipio VALUES(465,'BOJAYA (BELLAVISTA)',12);
INSERT INTO polls_municipio VALUES(466,'CANTON DE SAN PABLO',12);
INSERT INTO polls_municipio VALUES(467,'CARMEN DEL DARIEN',12);
INSERT INTO polls_municipio VALUES(468,'CERTEGUI',12);
INSERT INTO polls_municipio VALUES(469,'CONDOTO',12);
INSERT INTO polls_municipio VALUES(470,'EL CARMEN',12);
INSERT INTO polls_municipio VALUES(471,'ISTMINA',12);
INSERT INTO polls_municipio VALUES(472,'JURADO',12);
INSERT INTO polls_municipio VALUES(473,'LITORAL DEL SAN JUAN',12);
INSERT INTO polls_municipio VALUES(474,'LLORO',12);
INSERT INTO polls_municipio VALUES(475,'MEDIO ATRATO',12);
INSERT INTO polls_municipio VALUES(476,'MEDIO BAUDO (BOCA DE PEPE)',12);
INSERT INTO polls_municipio VALUES(477,'MEDIO SAN JUAN',12);
INSERT INTO polls_municipio VALUES(478,'NOVITA',12);
INSERT INTO polls_municipio VALUES(479,'NUQUI',12);
INSERT INTO polls_municipio VALUES(480,'QUIBDO',12);
INSERT INTO polls_municipio VALUES(481,'RIO IRO',12);
INSERT INTO polls_municipio VALUES(482,'RIO QUITO',12);
INSERT INTO polls_municipio VALUES(483,'RIOSUCIO',12);
INSERT INTO polls_municipio VALUES(484,'SAN JOSE DEL PALMAR',12);
INSERT INTO polls_municipio VALUES(485,'SIPI',12);
INSERT INTO polls_municipio VALUES(486,'TADO',12);
INSERT INTO polls_municipio VALUES(487,'UNGUIA',12);
INSERT INTO polls_municipio VALUES(488,'UNIÓN PANAMERICANA',12);
INSERT INTO polls_municipio VALUES(489,'AYAPEL',13);
INSERT INTO polls_municipio VALUES(490,'BUENAVISTA',13);
INSERT INTO polls_municipio VALUES(491,'CANALETE',13);
INSERT INTO polls_municipio VALUES(492,'CERETÉ',13);
INSERT INTO polls_municipio VALUES(493,'CHIMA',13);
INSERT INTO polls_municipio VALUES(494,'CHINÚ',13);
INSERT INTO polls_municipio VALUES(495,'CIENAGA DE ORO',13);
INSERT INTO polls_municipio VALUES(496,'COTORRA',13);
INSERT INTO polls_municipio VALUES(497,'LA APARTADA',13);
INSERT INTO polls_municipio VALUES(498,'LORICA',13);
INSERT INTO polls_municipio VALUES(499,'LOS CÓRDOBAS',13);
INSERT INTO polls_municipio VALUES(500,'MOMIL',13);
INSERT INTO polls_municipio VALUES(501,'MONTELÍBANO',13);
INSERT INTO polls_municipio VALUES(502,'MONTERÍA',13);
INSERT INTO polls_municipio VALUES(503,'MOÑITOS',13);
INSERT INTO polls_municipio VALUES(504,'PLANETA RICA',13);
INSERT INTO polls_municipio VALUES(505,'PUEBLO NUEVO',13);
INSERT INTO polls_municipio VALUES(506,'PUERTO ESCONDIDO',13);
INSERT INTO polls_municipio VALUES(507,'PUERTO LIBERTADOR',13);
INSERT INTO polls_municipio VALUES(508,'PURÍSIMA',13);
INSERT INTO polls_municipio VALUES(509,'SAHAGÚN',13);
INSERT INTO polls_municipio VALUES(510,'SAN ANDRÉS SOTAVENTO',13);
INSERT INTO polls_municipio VALUES(511,'SAN ANTERO',13);
INSERT INTO polls_municipio VALUES(512,'SAN BERNARDO VIENTO',13);
INSERT INTO polls_municipio VALUES(513,'SAN CARLOS',13);
INSERT INTO polls_municipio VALUES(514,'SAN PELAYO',13);
INSERT INTO polls_municipio VALUES(515,'TIERRALTA',13);
INSERT INTO polls_municipio VALUES(516,'VALENCIA',13);
INSERT INTO polls_municipio VALUES(517,'AGUA DE DIOS',14);
INSERT INTO polls_municipio VALUES(518,'ALBAN',14);
INSERT INTO polls_municipio VALUES(519,'ANAPOIMA',14);
INSERT INTO polls_municipio VALUES(520,'ANOLAIMA',14);
INSERT INTO polls_municipio VALUES(521,'ARBELAEZ',14);
INSERT INTO polls_municipio VALUES(522,'BELTRÁN',14);
INSERT INTO polls_municipio VALUES(523,'BITUIMA',14);
INSERT INTO polls_municipio VALUES(524,'BOGOTÁ DC',14);
INSERT INTO polls_municipio VALUES(525,'BOJACÁ',14);
INSERT INTO polls_municipio VALUES(526,'CABRERA',14);
INSERT INTO polls_municipio VALUES(527,'CACHIPAY',14);
INSERT INTO polls_municipio VALUES(528,'CAJICÁ',14);
INSERT INTO polls_municipio VALUES(529,'CAPARRAPÍ',14);
INSERT INTO polls_municipio VALUES(530,'CAQUEZA',14);
INSERT INTO polls_municipio VALUES(531,'CARMEN DE CARUPA',14);
INSERT INTO polls_municipio VALUES(532,'CHAGUANÍ',14);
INSERT INTO polls_municipio VALUES(533,'CHIA',14);
INSERT INTO polls_municipio VALUES(534,'CHIPAQUE',14);
INSERT INTO polls_municipio VALUES(535,'CHOACHÍ',14);
INSERT INTO polls_municipio VALUES(536,'CHOCONTÁ',14);
INSERT INTO polls_municipio VALUES(537,'COGUA',14);
INSERT INTO polls_municipio VALUES(538,'COTA',14);
INSERT INTO polls_municipio VALUES(539,'CUCUNUBÁ',14);
INSERT INTO polls_municipio VALUES(540,'EL COLEGIO',14);
INSERT INTO polls_municipio VALUES(541,'EL PEÑÓN',14);
INSERT INTO polls_municipio VALUES(542,'EL ROSAL1',14);
INSERT INTO polls_municipio VALUES(543,'FACATATIVA',14);
INSERT INTO polls_municipio VALUES(544,'FÓMEQUE',14);
INSERT INTO polls_municipio VALUES(545,'FOSCA',14);
INSERT INTO polls_municipio VALUES(546,'FUNZA',14);
INSERT INTO polls_municipio VALUES(547,'FÚQUENE',14);
INSERT INTO polls_municipio VALUES(548,'FUSAGASUGA',14);
INSERT INTO polls_municipio VALUES(549,'GACHALÁ',14);
INSERT INTO polls_municipio VALUES(550,'GACHANCIPÁ',14);
INSERT INTO polls_municipio VALUES(551,'GACHETA',14);
INSERT INTO polls_municipio VALUES(552,'GAMA',14);
INSERT INTO polls_municipio VALUES(553,'GIRARDOT',14);
INSERT INTO polls_municipio VALUES(554,'GRANADA2',14);
INSERT INTO polls_municipio VALUES(555,'GUACHETÁ',14);
INSERT INTO polls_municipio VALUES(556,'GUADUAS',14);
INSERT INTO polls_municipio VALUES(557,'GUASCA',14);
INSERT INTO polls_municipio VALUES(558,'GUATAQUÍ',14);
INSERT INTO polls_municipio VALUES(559,'GUATAVITA',14);
INSERT INTO polls_municipio VALUES(560,'GUAYABAL DE SIQUIMA',14);
INSERT INTO polls_municipio VALUES(561,'GUAYABETAL',14);
INSERT INTO polls_municipio VALUES(562,'GUTIÉRREZ',14);
INSERT INTO polls_municipio VALUES(563,'JERUSALÉN',14);
INSERT INTO polls_municipio VALUES(564,'JUNÍN',14);
INSERT INTO polls_municipio VALUES(565,'LA CALERA',14);
INSERT INTO polls_municipio VALUES(566,'LA MESA',14);
INSERT INTO polls_municipio VALUES(567,'LA PALMA',14);
INSERT INTO polls_municipio VALUES(568,'LA PEÑA',14);
INSERT INTO polls_municipio VALUES(569,'LA VEGA',14);
INSERT INTO polls_municipio VALUES(570,'LENGUAZAQUE',14);
INSERT INTO polls_municipio VALUES(571,'MACHETÁ',14);
INSERT INTO polls_municipio VALUES(572,'MADRID',14);
INSERT INTO polls_municipio VALUES(573,'MANTA',14);
INSERT INTO polls_municipio VALUES(574,'MEDINA',14);
INSERT INTO polls_municipio VALUES(575,'MOSQUERA',14);
INSERT INTO polls_municipio VALUES(576,'NARIÑO',14);
INSERT INTO polls_municipio VALUES(577,'NEMOCÓN',14);
INSERT INTO polls_municipio VALUES(578,'NILO',14);
INSERT INTO polls_municipio VALUES(579,'NIMAIMA',14);
INSERT INTO polls_municipio VALUES(580,'NOCAIMA',14);
INSERT INTO polls_municipio VALUES(581,'OSPINA PÉREZ',14);
INSERT INTO polls_municipio VALUES(582,'PACHO',14);
INSERT INTO polls_municipio VALUES(583,'PAIME',14);
INSERT INTO polls_municipio VALUES(584,'PANDI',14);
INSERT INTO polls_municipio VALUES(585,'PARATEBUENO',14);
INSERT INTO polls_municipio VALUES(586,'PASCA',14);
INSERT INTO polls_municipio VALUES(587,'PUERTO SALGAR',14);
INSERT INTO polls_municipio VALUES(588,'PULÍ',14);
INSERT INTO polls_municipio VALUES(589,'QUEBRADANEGRA',14);
INSERT INTO polls_municipio VALUES(590,'QUETAME',14);
INSERT INTO polls_municipio VALUES(591,'QUIPILE',14);
INSERT INTO polls_municipio VALUES(592,'RAFAEL REYES',14);
INSERT INTO polls_municipio VALUES(593,'RICAURTE',14);
INSERT INTO polls_municipio VALUES(594,'SAN  ANTONIO DEL  TEQUENDAMA',14);
INSERT INTO polls_municipio VALUES(595,'SAN BERNARDO',14);
INSERT INTO polls_municipio VALUES(596,'SAN CAYETANO',14);
INSERT INTO polls_municipio VALUES(597,'SAN FRANCISCO',14);
INSERT INTO polls_municipio VALUES(598,'SAN JUAN DE RIOSECO',14);
INSERT INTO polls_municipio VALUES(599,'SASAIMA',14);
INSERT INTO polls_municipio VALUES(600,'SESQUILÉ',14);
INSERT INTO polls_municipio VALUES(601,'SIBATÉ',14);
INSERT INTO polls_municipio VALUES(602,'SILVANIA',14);
INSERT INTO polls_municipio VALUES(603,'SIMIJACA',14);
INSERT INTO polls_municipio VALUES(604,'SOACHA',14);
INSERT INTO polls_municipio VALUES(605,'SOPO',14);
INSERT INTO polls_municipio VALUES(606,'SUBACHOQUE',14);
INSERT INTO polls_municipio VALUES(607,'SUESCA',14);
INSERT INTO polls_municipio VALUES(608,'SUPATÁ',14);
INSERT INTO polls_municipio VALUES(609,'SUSA',14);
INSERT INTO polls_municipio VALUES(610,'SUTATAUSA',14);
INSERT INTO polls_municipio VALUES(611,'TABIO',14);
INSERT INTO polls_municipio VALUES(612,'TAUSA',14);
INSERT INTO polls_municipio VALUES(613,'TENA',14);
INSERT INTO polls_municipio VALUES(614,'TENJO',14);
INSERT INTO polls_municipio VALUES(615,'TIBACUY',14);
INSERT INTO polls_municipio VALUES(616,'TIBIRITA',14);
INSERT INTO polls_municipio VALUES(617,'TOCAIMA',14);
INSERT INTO polls_municipio VALUES(618,'TOCANCIPÁ',14);
INSERT INTO polls_municipio VALUES(619,'TOPAIPÍ',14);
INSERT INTO polls_municipio VALUES(620,'UBALÁ',14);
INSERT INTO polls_municipio VALUES(621,'UBAQUE',14);
INSERT INTO polls_municipio VALUES(622,'UBATÉ',14);
INSERT INTO polls_municipio VALUES(623,'UNE',14);
INSERT INTO polls_municipio VALUES(624,'UTICA',14);
INSERT INTO polls_municipio VALUES(625,'VERGARA',14);
INSERT INTO polls_municipio VALUES(626,'VIANI',14);
INSERT INTO polls_municipio VALUES(627,'VILLA GOMEZ',14);
INSERT INTO polls_municipio VALUES(628,'VILLA PINZÓN',14);
INSERT INTO polls_municipio VALUES(629,'VILLETA',14);
INSERT INTO polls_municipio VALUES(630,'VIOTA',14);
INSERT INTO polls_municipio VALUES(631,'YACOPÍ',14);
INSERT INTO polls_municipio VALUES(632,'ZIPACÓN',14);
INSERT INTO polls_municipio VALUES(633,'ZIPAQUIRÁ',14);
INSERT INTO polls_municipio VALUES(634,'BARRANCO MINAS',15);
INSERT INTO polls_municipio VALUES(635,'CACAHUAL',15);
INSERT INTO polls_municipio VALUES(636,'INÍRIDA',15);
INSERT INTO polls_municipio VALUES(637,'LA GUADALUPE',15);
INSERT INTO polls_municipio VALUES(638,'MAPIRIPANA',15);
INSERT INTO polls_municipio VALUES(639,'MORICHAL',15);
INSERT INTO polls_municipio VALUES(640,'PANA PANA',15);
INSERT INTO polls_municipio VALUES(641,'PUERTO COLOMBIA',15);
INSERT INTO polls_municipio VALUES(642,'SAN FELIPE',15);
INSERT INTO polls_municipio VALUES(643,'CALAMAR',16);
INSERT INTO polls_municipio VALUES(644,'EL RETORNO',16);
INSERT INTO polls_municipio VALUES(645,'MIRAFLOREZ',16);
INSERT INTO polls_municipio VALUES(646,'SAN JOSÉ DEL GUAVIARE',16);
INSERT INTO polls_municipio VALUES(647,'ACEVEDO',17);
INSERT INTO polls_municipio VALUES(648,'AGRADO',17);
INSERT INTO polls_municipio VALUES(649,'AIPE',17);
INSERT INTO polls_municipio VALUES(650,'ALGECIRAS',17);
INSERT INTO polls_municipio VALUES(651,'ALTAMIRA',17);
INSERT INTO polls_municipio VALUES(652,'BARAYA',17);
INSERT INTO polls_municipio VALUES(653,'CAMPO ALEGRE',17);
INSERT INTO polls_municipio VALUES(654,'COLOMBIA',17);
INSERT INTO polls_municipio VALUES(655,'ELIAS',17);
INSERT INTO polls_municipio VALUES(656,'GARZÓN',17);
INSERT INTO polls_municipio VALUES(657,'GIGANTE',17);
INSERT INTO polls_municipio VALUES(658,'GUADALUPE',17);
INSERT INTO polls_municipio VALUES(659,'HOBO',17);
INSERT INTO polls_municipio VALUES(660,'IQUIRA',17);
INSERT INTO polls_municipio VALUES(661,'ISNOS',17);
INSERT INTO polls_municipio VALUES(662,'LA ARGENTINA',17);
INSERT INTO polls_municipio VALUES(663,'LA PLATA',17);
INSERT INTO polls_municipio VALUES(664,'NATAGA',17);
INSERT INTO polls_municipio VALUES(665,'NEIVA',17);
INSERT INTO polls_municipio VALUES(666,'OPORAPA',17);
INSERT INTO polls_municipio VALUES(667,'PAICOL',17);
INSERT INTO polls_municipio VALUES(668,'PALERMO',17);
INSERT INTO polls_municipio VALUES(669,'PALESTINA',17);
INSERT INTO polls_municipio VALUES(670,'PITAL',17);
INSERT INTO polls_municipio VALUES(671,'PITALITO',17);
INSERT INTO polls_municipio VALUES(672,'RIVERA',17);
INSERT INTO polls_municipio VALUES(673,'SALADO BLANCO',17);
INSERT INTO polls_municipio VALUES(674,'SAN AGUSTÍN',17);
INSERT INTO polls_municipio VALUES(675,'SANTA MARIA',17);
INSERT INTO polls_municipio VALUES(676,'SUAZA',17);
INSERT INTO polls_municipio VALUES(677,'TARQUI',17);
INSERT INTO polls_municipio VALUES(678,'TELLO',17);
INSERT INTO polls_municipio VALUES(679,'TERUEL',17);
INSERT INTO polls_municipio VALUES(680,'TESALIA',17);
INSERT INTO polls_municipio VALUES(681,'TIMANA',17);
INSERT INTO polls_municipio VALUES(682,'VILLAVIEJA',17);
INSERT INTO polls_municipio VALUES(683,'YAGUARA',17);
INSERT INTO polls_municipio VALUES(684,'ALBANIA',18);
INSERT INTO polls_municipio VALUES(685,'BARRANCAS',18);
INSERT INTO polls_municipio VALUES(686,'DIBULLA',18);
INSERT INTO polls_municipio VALUES(687,'DISTRACCIÓN',18);
INSERT INTO polls_municipio VALUES(688,'EL MOLINO',18);
INSERT INTO polls_municipio VALUES(689,'FONSECA',18);
INSERT INTO polls_municipio VALUES(690,'HATO NUEVO',18);
INSERT INTO polls_municipio VALUES(691,'LA JAGUA DEL PILAR',18);
INSERT INTO polls_municipio VALUES(692,'MAICAO',18);
INSERT INTO polls_municipio VALUES(693,'MANAURE',18);
INSERT INTO polls_municipio VALUES(694,'RIOHACHA',18);
INSERT INTO polls_municipio VALUES(695,'SAN JUAN DEL CESAR',18);
INSERT INTO polls_municipio VALUES(696,'URIBIA',18);
INSERT INTO polls_municipio VALUES(697,'URUMITA',18);
INSERT INTO polls_municipio VALUES(698,'VILLANUEVA',18);
INSERT INTO polls_municipio VALUES(699,'ALGARROBO',19);
INSERT INTO polls_municipio VALUES(700,'ARACATACA',19);
INSERT INTO polls_municipio VALUES(701,'ARIGUANI',19);
INSERT INTO polls_municipio VALUES(702,'CERRO SAN ANTONIO',19);
INSERT INTO polls_municipio VALUES(703,'CHIVOLO',19);
INSERT INTO polls_municipio VALUES(704,'CIENAGA',19);
INSERT INTO polls_municipio VALUES(705,'CONCORDIA',19);
INSERT INTO polls_municipio VALUES(706,'EL BANCO',19);
INSERT INTO polls_municipio VALUES(707,'EL PIÑON',19);
INSERT INTO polls_municipio VALUES(708,'EL RETEN',19);
INSERT INTO polls_municipio VALUES(709,'FUNDACION',19);
INSERT INTO polls_municipio VALUES(710,'GUAMAL',19);
INSERT INTO polls_municipio VALUES(711,'NUEVA GRANADA',19);
INSERT INTO polls_municipio VALUES(712,'PEDRAZA',19);
INSERT INTO polls_municipio VALUES(713,'PIJIÑO DEL CARMEN',19);
INSERT INTO polls_municipio VALUES(714,'PIVIJAY',19);
INSERT INTO polls_municipio VALUES(715,'PLATO',19);
INSERT INTO polls_municipio VALUES(716,'PUEBLO VIEJO',19);
INSERT INTO polls_municipio VALUES(717,'REMOLINO',19);
INSERT INTO polls_municipio VALUES(718,'SABANAS DE SAN ANGEL',19);
INSERT INTO polls_municipio VALUES(719,'SALAMINA',19);
INSERT INTO polls_municipio VALUES(720,'SAN SEBASTIAN DE BUENAVISTA',19);
INSERT INTO polls_municipio VALUES(721,'SAN ZENON',19);
INSERT INTO polls_municipio VALUES(722,'SANTA ANA',19);
INSERT INTO polls_municipio VALUES(723,'SANTA BARBARA DE PINTO',19);
INSERT INTO polls_municipio VALUES(724,'SANTA MARTA',19);
INSERT INTO polls_municipio VALUES(725,'SITIONUEVO',19);
INSERT INTO polls_municipio VALUES(726,'TENERIFE',19);
INSERT INTO polls_municipio VALUES(727,'ZAPAYAN',19);
INSERT INTO polls_municipio VALUES(728,'ZONA BANANERA',19);
INSERT INTO polls_municipio VALUES(729,'ACACIAS',20);
INSERT INTO polls_municipio VALUES(730,'BARRANCA DE UPIA',20);
INSERT INTO polls_municipio VALUES(731,'CABUYARO',20);
INSERT INTO polls_municipio VALUES(732,'CASTILLA LA NUEVA',20);
INSERT INTO polls_municipio VALUES(733,'CUBARRAL',20);
INSERT INTO polls_municipio VALUES(734,'CUMARAL',20);
INSERT INTO polls_municipio VALUES(735,'EL CALVARIO',20);
INSERT INTO polls_municipio VALUES(736,'EL CASTILLO',20);
INSERT INTO polls_municipio VALUES(737,'EL DORADO',20);
INSERT INTO polls_municipio VALUES(738,'FUENTE DE ORO',20);
INSERT INTO polls_municipio VALUES(739,'GRANADA',20);
INSERT INTO polls_municipio VALUES(740,'GUAMAL',20);
INSERT INTO polls_municipio VALUES(741,'LA MACARENA',20);
INSERT INTO polls_municipio VALUES(742,'LA URIBE',20);
INSERT INTO polls_municipio VALUES(743,'LEJANÍAS',20);
INSERT INTO polls_municipio VALUES(744,'MAPIRIPÁN',20);
INSERT INTO polls_municipio VALUES(745,'MESETAS',20);
INSERT INTO polls_municipio VALUES(746,'PUERTO CONCORDIA',20);
INSERT INTO polls_municipio VALUES(747,'PUERTO GAITÁN',20);
INSERT INTO polls_municipio VALUES(748,'PUERTO LLERAS',20);
INSERT INTO polls_municipio VALUES(749,'PUERTO LÓPEZ',20);
INSERT INTO polls_municipio VALUES(750,'PUERTO RICO',20);
INSERT INTO polls_municipio VALUES(751,'RESTREPO',20);
INSERT INTO polls_municipio VALUES(752,'SAN  JUAN DE ARAMA',20);
INSERT INTO polls_municipio VALUES(753,'SAN CARLOS GUAROA',20);
INSERT INTO polls_municipio VALUES(754,'SAN JUANITO',20);
INSERT INTO polls_municipio VALUES(755,'SAN MARTÍN',20);
INSERT INTO polls_municipio VALUES(756,'VILLAVICENCIO',20);
INSERT INTO polls_municipio VALUES(757,'VISTA HERMOSA',20);
INSERT INTO polls_municipio VALUES(758,'ALBAN',21);
INSERT INTO polls_municipio VALUES(759,'ALDAÑA',21);
INSERT INTO polls_municipio VALUES(760,'ANCUYA',21);
INSERT INTO polls_municipio VALUES(761,'ARBOLEDA',21);
INSERT INTO polls_municipio VALUES(762,'BARBACOAS',21);
INSERT INTO polls_municipio VALUES(763,'BELEN',21);
INSERT INTO polls_municipio VALUES(764,'BUESACO',21);
INSERT INTO polls_municipio VALUES(765,'CHACHAGUI',21);
INSERT INTO polls_municipio VALUES(766,'COLON (GENOVA)',21);
INSERT INTO polls_municipio VALUES(767,'CONSACA',21);
INSERT INTO polls_municipio VALUES(768,'CONTADERO',21);
INSERT INTO polls_municipio VALUES(769,'CORDOBA',21);
INSERT INTO polls_municipio VALUES(770,'CUASPUD',21);
INSERT INTO polls_municipio VALUES(771,'CUMBAL',21);
INSERT INTO polls_municipio VALUES(772,'CUMBITARA',21);
INSERT INTO polls_municipio VALUES(773,'EL CHARCO',21);
INSERT INTO polls_municipio VALUES(774,'EL PEÑOL',21);
INSERT INTO polls_municipio VALUES(775,'EL ROSARIO',21);
INSERT INTO polls_municipio VALUES(776,'EL TABLÓN',21);
INSERT INTO polls_municipio VALUES(777,'EL TAMBO',21);
INSERT INTO polls_municipio VALUES(778,'FUNES',21);
INSERT INTO polls_municipio VALUES(779,'GUACHUCAL',21);
INSERT INTO polls_municipio VALUES(780,'GUAITARILLA',21);
INSERT INTO polls_municipio VALUES(781,'GUALMATAN',21);
INSERT INTO polls_municipio VALUES(782,'ILES',21);
INSERT INTO polls_municipio VALUES(783,'IMUES',21);
INSERT INTO polls_municipio VALUES(784,'IPIALES',21);
INSERT INTO polls_municipio VALUES(785,'LA CRUZ',21);
INSERT INTO polls_municipio VALUES(786,'LA FLORIDA',21);
INSERT INTO polls_municipio VALUES(787,'LA LLANADA',21);
INSERT INTO polls_municipio VALUES(788,'LA TOLA',21);
INSERT INTO polls_municipio VALUES(789,'LA UNION',21);
INSERT INTO polls_municipio VALUES(790,'LEIVA',21);
INSERT INTO polls_municipio VALUES(791,'LINARES',21);
INSERT INTO polls_municipio VALUES(792,'LOS ANDES',21);
INSERT INTO polls_municipio VALUES(793,'MAGUI',21);
INSERT INTO polls_municipio VALUES(794,'MALLAMA',21);
INSERT INTO polls_municipio VALUES(795,'MOSQUEZA',21);
INSERT INTO polls_municipio VALUES(796,'NARIÑO',21);
INSERT INTO polls_municipio VALUES(797,'OLAYA HERRERA',21);
INSERT INTO polls_municipio VALUES(798,'OSPINA',21);
INSERT INTO polls_municipio VALUES(799,'PASTO',21);
INSERT INTO polls_municipio VALUES(800,'PIZARRO',21);
INSERT INTO polls_municipio VALUES(801,'POLICARPA',21);
INSERT INTO polls_municipio VALUES(802,'POTOSI',21);
INSERT INTO polls_municipio VALUES(803,'PROVIDENCIA',21);
INSERT INTO polls_municipio VALUES(804,'PUERRES',21);
INSERT INTO polls_municipio VALUES(805,'PUPIALES',21);
INSERT INTO polls_municipio VALUES(806,'RICAURTE',21);
INSERT INTO polls_municipio VALUES(807,'ROBERTO PAYAN',21);
INSERT INTO polls_municipio VALUES(808,'SAMANIEGO',21);
INSERT INTO polls_municipio VALUES(809,'SAN BERNARDO',21);
INSERT INTO polls_municipio VALUES(810,'SAN LORENZO',21);
INSERT INTO polls_municipio VALUES(811,'SAN PABLO',21);
INSERT INTO polls_municipio VALUES(812,'SAN PEDRO DE CARTAGO',21);
INSERT INTO polls_municipio VALUES(813,'SANDONA',21);
INSERT INTO polls_municipio VALUES(814,'SANTA BARBARA',21);
INSERT INTO polls_municipio VALUES(815,'SANTACRUZ',21);
INSERT INTO polls_municipio VALUES(816,'SAPUYES',21);
INSERT INTO polls_municipio VALUES(817,'TAMINANGO',21);
INSERT INTO polls_municipio VALUES(818,'TANGUA',21);
INSERT INTO polls_municipio VALUES(819,'TUMACO',21);
INSERT INTO polls_municipio VALUES(820,'TUQUERRES',21);
INSERT INTO polls_municipio VALUES(821,'YACUANQUER',21);
INSERT INTO polls_municipio VALUES(822,'ABREGO',22);
INSERT INTO polls_municipio VALUES(823,'ARBOLEDAS',22);
INSERT INTO polls_municipio VALUES(824,'BOCHALEMA',22);
INSERT INTO polls_municipio VALUES(825,'BUCARASICA',22);
INSERT INTO polls_municipio VALUES(826,'CÁCHIRA',22);
INSERT INTO polls_municipio VALUES(827,'CÁCOTA',22);
INSERT INTO polls_municipio VALUES(828,'CHINÁCOTA',22);
INSERT INTO polls_municipio VALUES(829,'CHITAGÁ',22);
INSERT INTO polls_municipio VALUES(830,'CONVENCIÓN',22);
INSERT INTO polls_municipio VALUES(831,'CÚCUTA',22);
INSERT INTO polls_municipio VALUES(832,'CUCUTILLA',22);
INSERT INTO polls_municipio VALUES(833,'DURANIA',22);
INSERT INTO polls_municipio VALUES(834,'EL CARMEN',22);
INSERT INTO polls_municipio VALUES(835,'EL TARRA',22);
INSERT INTO polls_municipio VALUES(836,'EL ZULIA',22);
INSERT INTO polls_municipio VALUES(837,'GRAMALOTE',22);
INSERT INTO polls_municipio VALUES(838,'HACARI',22);
INSERT INTO polls_municipio VALUES(839,'HERRÁN',22);
INSERT INTO polls_municipio VALUES(840,'LA ESPERANZA',22);
INSERT INTO polls_municipio VALUES(841,'LA PLAYA',22);
INSERT INTO polls_municipio VALUES(842,'LABATECA',22);
INSERT INTO polls_municipio VALUES(843,'LOS PATIOS',22);
INSERT INTO polls_municipio VALUES(844,'LOURDES',22);
INSERT INTO polls_municipio VALUES(845,'MUTISCUA',22);
INSERT INTO polls_municipio VALUES(846,'OCAÑA',22);
INSERT INTO polls_municipio VALUES(847,'PAMPLONA',22);
INSERT INTO polls_municipio VALUES(848,'PAMPLONITA',22);
INSERT INTO polls_municipio VALUES(849,'PUERTO SANTANDER',22);
INSERT INTO polls_municipio VALUES(850,'RAGONVALIA',22);
INSERT INTO polls_municipio VALUES(851,'SALAZAR',22);
INSERT INTO polls_municipio VALUES(852,'SAN CALIXTO',22);
INSERT INTO polls_municipio VALUES(853,'SAN CAYETANO',22);
INSERT INTO polls_municipio VALUES(854,'SANTIAGO',22);
INSERT INTO polls_municipio VALUES(855,'SARDINATA',22);
INSERT INTO polls_municipio VALUES(856,'SILOS',22);
INSERT INTO polls_municipio VALUES(857,'TEORAMA',22);
INSERT INTO polls_municipio VALUES(858,'TIBÚ',22);
INSERT INTO polls_municipio VALUES(859,'TOLEDO',22);
INSERT INTO polls_municipio VALUES(860,'VILLA CARO',22);
INSERT INTO polls_municipio VALUES(861,'VILLA DEL ROSARIO',22);
INSERT INTO polls_municipio VALUES(862,'COLÓN',23);
INSERT INTO polls_municipio VALUES(863,'MOCOA',23);
INSERT INTO polls_municipio VALUES(864,'ORITO',23);
INSERT INTO polls_municipio VALUES(865,'PUERTO ASÍS',23);
INSERT INTO polls_municipio VALUES(866,'PUERTO CAYCEDO',23);
INSERT INTO polls_municipio VALUES(867,'PUERTO GUZMÁN',23);
INSERT INTO polls_municipio VALUES(868,'PUERTO LEGUÍZAMO',23);
INSERT INTO polls_municipio VALUES(869,'SAN FRANCISCO',23);
INSERT INTO polls_municipio VALUES(870,'SAN MIGUEL',23);
INSERT INTO polls_municipio VALUES(871,'SANTIAGO',23);
INSERT INTO polls_municipio VALUES(872,'SIBUNDOY',23);
INSERT INTO polls_municipio VALUES(873,'VALLE DEL GUAMUEZ',23);
INSERT INTO polls_municipio VALUES(874,'VILLAGARZÓN',23);
INSERT INTO polls_municipio VALUES(875,'ARMENIA',24);
INSERT INTO polls_municipio VALUES(876,'BUENAVISTA',24);
INSERT INTO polls_municipio VALUES(877,'CALARCÁ',24);
INSERT INTO polls_municipio VALUES(878,'CIRCASIA',24);
INSERT INTO polls_municipio VALUES(879,'CÓRDOBA',24);
INSERT INTO polls_municipio VALUES(880,'FILANDIA',24);
INSERT INTO polls_municipio VALUES(881,'GÉNOVA',24);
INSERT INTO polls_municipio VALUES(882,'LA TEBAIDA',24);
INSERT INTO polls_municipio VALUES(883,'MONTENEGRO',24);
INSERT INTO polls_municipio VALUES(884,'PIJAO',24);
INSERT INTO polls_municipio VALUES(885,'QUIMBAYA',24);
INSERT INTO polls_municipio VALUES(886,'SALENTO',24);
INSERT INTO polls_municipio VALUES(887,'APIA',25);
INSERT INTO polls_municipio VALUES(888,'BALBOA',25);
INSERT INTO polls_municipio VALUES(889,'BELÉN DE UMBRÍA',25);
INSERT INTO polls_municipio VALUES(890,'DOS QUEBRADAS',25);
INSERT INTO polls_municipio VALUES(891,'GUATICA',25);
INSERT INTO polls_municipio VALUES(892,'LA CELIA',25);
INSERT INTO polls_municipio VALUES(893,'LA VIRGINIA',25);
INSERT INTO polls_municipio VALUES(894,'MARSELLA',25);
INSERT INTO polls_municipio VALUES(895,'MISTRATO',25);
INSERT INTO polls_municipio VALUES(896,'PEREIRA',25);
INSERT INTO polls_municipio VALUES(897,'PUEBLO RICO',25);
INSERT INTO polls_municipio VALUES(898,'QUINCHÍA',25);
INSERT INTO polls_municipio VALUES(899,'SANTA ROSA DE CABAL',25);
INSERT INTO polls_municipio VALUES(900,'SANTUARIO',25);
INSERT INTO polls_municipio VALUES(901,'PROVIDENCIA',26);
INSERT INTO polls_municipio VALUES(902,'SAN ANDRES',26);
INSERT INTO polls_municipio VALUES(903,'SANTA CATALINA',26);
INSERT INTO polls_municipio VALUES(904,'AGUADA',27);
INSERT INTO polls_municipio VALUES(905,'ALBANIA',27);
INSERT INTO polls_municipio VALUES(906,'ARATOCA',27);
INSERT INTO polls_municipio VALUES(907,'BARBOSA',27);
INSERT INTO polls_municipio VALUES(908,'BARICHARA',27);
INSERT INTO polls_municipio VALUES(909,'BARRANCABERMEJA',27);
INSERT INTO polls_municipio VALUES(910,'BETULIA',27);
INSERT INTO polls_municipio VALUES(911,'BOLÍVAR',27);
INSERT INTO polls_municipio VALUES(912,'BUCARAMANGA',27);
INSERT INTO polls_municipio VALUES(913,'CABRERA',27);
INSERT INTO polls_municipio VALUES(914,'CALIFORNIA',27);
INSERT INTO polls_municipio VALUES(915,'CAPITANEJO',27);
INSERT INTO polls_municipio VALUES(916,'CARCASI',27);
INSERT INTO polls_municipio VALUES(917,'CEPITA',27);
INSERT INTO polls_municipio VALUES(918,'CERRITO',27);
INSERT INTO polls_municipio VALUES(919,'CHARALÁ',27);
INSERT INTO polls_municipio VALUES(920,'CHARTA',27);
INSERT INTO polls_municipio VALUES(921,'CHIMA',27);
INSERT INTO polls_municipio VALUES(922,'CHIPATÁ',27);
INSERT INTO polls_municipio VALUES(923,'CIMITARRA',27);
INSERT INTO polls_municipio VALUES(924,'CONCEPCIÓN',27);
INSERT INTO polls_municipio VALUES(925,'CONFINES',27);
INSERT INTO polls_municipio VALUES(926,'CONTRATACIÓN',27);
INSERT INTO polls_municipio VALUES(927,'COROMORO',27);
INSERT INTO polls_municipio VALUES(928,'CURITÍ',27);
INSERT INTO polls_municipio VALUES(929,'EL CARMEN',27);
INSERT INTO polls_municipio VALUES(930,'EL GUACAMAYO',27);
INSERT INTO polls_municipio VALUES(931,'EL PEÑÓN',27);
INSERT INTO polls_municipio VALUES(932,'EL PLAYÓN',27);
INSERT INTO polls_municipio VALUES(933,'ENCINO',27);
INSERT INTO polls_municipio VALUES(934,'ENCISO',27);
INSERT INTO polls_municipio VALUES(935,'FLORIÁN',27);
INSERT INTO polls_municipio VALUES(936,'FLORIDABLANCA',27);
INSERT INTO polls_municipio VALUES(937,'GALÁN',27);
INSERT INTO polls_municipio VALUES(938,'GAMBITA',27);
INSERT INTO polls_municipio VALUES(939,'GIRÓN',27);
INSERT INTO polls_municipio VALUES(940,'GUACA',27);
INSERT INTO polls_municipio VALUES(941,'GUADALUPE',27);
INSERT INTO polls_municipio VALUES(942,'GUAPOTA',27);
INSERT INTO polls_municipio VALUES(943,'GUAVATÁ',27);
INSERT INTO polls_municipio VALUES(944,'GUEPSA',27);
INSERT INTO polls_municipio VALUES(945,'HATO',27);
INSERT INTO polls_municipio VALUES(946,'JESÚS MARIA',27);
INSERT INTO polls_municipio VALUES(947,'JORDÁN',27);
INSERT INTO polls_municipio VALUES(948,'LA BELLEZA',27);
INSERT INTO polls_municipio VALUES(949,'LA PAZ',27);
INSERT INTO polls_municipio VALUES(950,'LANDAZURI',27);
INSERT INTO polls_municipio VALUES(951,'LEBRIJA',27);
INSERT INTO polls_municipio VALUES(952,'LOS SANTOS',27);
INSERT INTO polls_municipio VALUES(953,'MACARAVITA',27);
INSERT INTO polls_municipio VALUES(954,'MÁLAGA',27);
INSERT INTO polls_municipio VALUES(955,'MATANZA',27);
INSERT INTO polls_municipio VALUES(956,'MOGOTES',27);
INSERT INTO polls_municipio VALUES(957,'MOLAGAVITA',27);
INSERT INTO polls_municipio VALUES(958,'OCAMONTE',27);
INSERT INTO polls_municipio VALUES(959,'OIBA',27);
INSERT INTO polls_municipio VALUES(960,'ONZAGA',27);
INSERT INTO polls_municipio VALUES(961,'PALMAR',27);
INSERT INTO polls_municipio VALUES(962,'PALMAS DEL SOCORRO',27);
INSERT INTO polls_municipio VALUES(963,'PÁRAMO',27);
INSERT INTO polls_municipio VALUES(964,'PIEDECUESTA',27);
INSERT INTO polls_municipio VALUES(965,'PINCHOTE',27);
INSERT INTO polls_municipio VALUES(966,'PUENTE NACIONAL',27);
INSERT INTO polls_municipio VALUES(967,'PUERTO PARRA',27);
INSERT INTO polls_municipio VALUES(968,'PUERTO WILCHES',27);
INSERT INTO polls_municipio VALUES(969,'RIONEGRO',27);
INSERT INTO polls_municipio VALUES(970,'SABANA DE TORRES',27);
INSERT INTO polls_municipio VALUES(971,'SAN ANDRÉS',27);
INSERT INTO polls_municipio VALUES(972,'SAN BENITO',27);
INSERT INTO polls_municipio VALUES(973,'SAN GIL',27);
INSERT INTO polls_municipio VALUES(974,'SAN JOAQUÍN',27);
INSERT INTO polls_municipio VALUES(975,'SAN JOSÉ DE MIRANDA',27);
INSERT INTO polls_municipio VALUES(976,'SAN MIGUEL',27);
INSERT INTO polls_municipio VALUES(977,'SAN VICENTE DE CHUCURÍ',27);
INSERT INTO polls_municipio VALUES(978,'SANTA BÁRBARA',27);
INSERT INTO polls_municipio VALUES(979,'SANTA HELENA',27);
INSERT INTO polls_municipio VALUES(980,'SIMACOTA',27);
INSERT INTO polls_municipio VALUES(981,'SOCORRO',27);
INSERT INTO polls_municipio VALUES(982,'SUAITA',27);
INSERT INTO polls_municipio VALUES(983,'SUCRE',27);
INSERT INTO polls_municipio VALUES(984,'SURATA',27);
INSERT INTO polls_municipio VALUES(985,'TONA',27);
INSERT INTO polls_municipio VALUES(986,'VALLE SAN JOSÉ',27);
INSERT INTO polls_municipio VALUES(987,'VÉLEZ',27);
INSERT INTO polls_municipio VALUES(988,'VETAS',27);
INSERT INTO polls_municipio VALUES(989,'VILLANUEVA',27);
INSERT INTO polls_municipio VALUES(990,'ZAPATOCA',27);
INSERT INTO polls_municipio VALUES(991,'BUENAVISTA',28);
INSERT INTO polls_municipio VALUES(992,'CAIMITO',28);
INSERT INTO polls_municipio VALUES(993,'CHALÁN',28);
INSERT INTO polls_municipio VALUES(994,'COLOSO',28);
INSERT INTO polls_municipio VALUES(995,'COROZAL',28);
INSERT INTO polls_municipio VALUES(996,'EL ROBLE',28);
INSERT INTO polls_municipio VALUES(997,'GALERAS',28);
INSERT INTO polls_municipio VALUES(998,'GUARANDA',28);
INSERT INTO polls_municipio VALUES(999,'LA UNIÓN',28);
INSERT INTO polls_municipio VALUES(1000,'LOS PALMITOS',28);
INSERT INTO polls_municipio VALUES(1001,'MAJAGUAL',28);
INSERT INTO polls_municipio VALUES(1002,'MORROA',28);
INSERT INTO polls_municipio VALUES(1003,'OVEJAS',28);
INSERT INTO polls_municipio VALUES(1004,'PALMITO',28);
INSERT INTO polls_municipio VALUES(1005,'SAMPUES',28);
INSERT INTO polls_municipio VALUES(1006,'SAN BENITO ABAD',28);
INSERT INTO polls_municipio VALUES(1007,'SAN JUAN DE BETULIA',28);
INSERT INTO polls_municipio VALUES(1008,'SAN MARCOS',28);
INSERT INTO polls_municipio VALUES(1009,'SAN ONOFRE',28);
INSERT INTO polls_municipio VALUES(1010,'SAN PEDRO',28);
INSERT INTO polls_municipio VALUES(1011,'SINCÉ',28);
INSERT INTO polls_municipio VALUES(1012,'SINCELEJO',28);
INSERT INTO polls_municipio VALUES(1013,'SUCRE',28);
INSERT INTO polls_municipio VALUES(1014,'TOLÚ',28);
INSERT INTO polls_municipio VALUES(1015,'TOLUVIEJO',28);
INSERT INTO polls_municipio VALUES(1016,'ALPUJARRA',29);
INSERT INTO polls_municipio VALUES(1017,'ALVARADO',29);
INSERT INTO polls_municipio VALUES(1018,'AMBALEMA',29);
INSERT INTO polls_municipio VALUES(1019,'ANZOATEGUI',29);
INSERT INTO polls_municipio VALUES(1020,'ARMERO (GUAYABAL)',29);
INSERT INTO polls_municipio VALUES(1021,'ATACO',29);
INSERT INTO polls_municipio VALUES(1022,'CAJAMARCA',29);
INSERT INTO polls_municipio VALUES(1023,'CARMEN DE APICALÁ',29);
INSERT INTO polls_municipio VALUES(1024,'CASABIANCA',29);
INSERT INTO polls_municipio VALUES(1025,'CHAPARRAL',29);
INSERT INTO polls_municipio VALUES(1026,'COELLO',29);
INSERT INTO polls_municipio VALUES(1027,'COYAIMA',29);
INSERT INTO polls_municipio VALUES(1028,'CUNDAY',29);
INSERT INTO polls_municipio VALUES(1029,'DOLORES',29);
INSERT INTO polls_municipio VALUES(1030,'ESPINAL',29);
INSERT INTO polls_municipio VALUES(1031,'FALÁN',29);
INSERT INTO polls_municipio VALUES(1032,'FLANDES',29);
INSERT INTO polls_municipio VALUES(1033,'FRESNO',29);
INSERT INTO polls_municipio VALUES(1034,'GUAMO',29);
INSERT INTO polls_municipio VALUES(1035,'HERVEO',29);
INSERT INTO polls_municipio VALUES(1036,'HONDA',29);
INSERT INTO polls_municipio VALUES(1037,'IBAGUÉ',29);
INSERT INTO polls_municipio VALUES(1038,'ICONONZO',29);
INSERT INTO polls_municipio VALUES(1039,'LÉRIDA',29);
INSERT INTO polls_municipio VALUES(1040,'LÍBANO',29);
INSERT INTO polls_municipio VALUES(1041,'MARIQUITA',29);
INSERT INTO polls_municipio VALUES(1042,'MELGAR',29);
INSERT INTO polls_municipio VALUES(1043,'MURILLO',29);
INSERT INTO polls_municipio VALUES(1044,'NATAGAIMA',29);
INSERT INTO polls_municipio VALUES(1045,'ORTEGA',29);
INSERT INTO polls_municipio VALUES(1046,'PALOCABILDO',29);
INSERT INTO polls_municipio VALUES(1047,'PIEDRAS PLANADAS',29);
INSERT INTO polls_municipio VALUES(1048,'PRADO',29);
INSERT INTO polls_municipio VALUES(1049,'PURIFICACIÓN',29);
INSERT INTO polls_municipio VALUES(1050,'RIOBLANCO',29);
INSERT INTO polls_municipio VALUES(1051,'RONCESVALLES',29);
INSERT INTO polls_municipio VALUES(1052,'ROVIRA',29);
INSERT INTO polls_municipio VALUES(1053,'SALDAÑA',29);
INSERT INTO polls_municipio VALUES(1054,'SAN ANTONIO',29);
INSERT INTO polls_municipio VALUES(1055,'SAN LUIS',29);
INSERT INTO polls_municipio VALUES(1056,'SANTA ISABEL',29);
INSERT INTO polls_municipio VALUES(1057,'SUÁREZ',29);
INSERT INTO polls_municipio VALUES(1058,'VALLE DE SAN JUAN',29);
INSERT INTO polls_municipio VALUES(1059,'VENADILLO',29);
INSERT INTO polls_municipio VALUES(1060,'VILLAHERMOSA',29);
INSERT INTO polls_municipio VALUES(1061,'VILLARRICA',29);
INSERT INTO polls_municipio VALUES(1062,'ALCALÁ',30);
INSERT INTO polls_municipio VALUES(1063,'ANDALUCÍA',30);
INSERT INTO polls_municipio VALUES(1064,'ANSERMA NUEVO',30);
INSERT INTO polls_municipio VALUES(1065,'ARGELIA',30);
INSERT INTO polls_municipio VALUES(1066,'BOLÍVAR',30);
INSERT INTO polls_municipio VALUES(1067,'BUENAVENTURA',30);
INSERT INTO polls_municipio VALUES(1068,'BUGA',30);
INSERT INTO polls_municipio VALUES(1069,'BUGALAGRANDE',30);
INSERT INTO polls_municipio VALUES(1070,'CAICEDONIA',30);
INSERT INTO polls_municipio VALUES(1071,'CALI',30);
INSERT INTO polls_municipio VALUES(1072,'CALIMA (DARIEN)',30);
INSERT INTO polls_municipio VALUES(1073,'CANDELARIA',30);
INSERT INTO polls_municipio VALUES(1074,'CARTAGO',30);
INSERT INTO polls_municipio VALUES(1075,'DAGUA',30);
INSERT INTO polls_municipio VALUES(1076,'EL AGUILA',30);
INSERT INTO polls_municipio VALUES(1077,'EL CAIRO',30);
INSERT INTO polls_municipio VALUES(1078,'EL CERRITO',30);
INSERT INTO polls_municipio VALUES(1079,'EL DOVIO',30);
INSERT INTO polls_municipio VALUES(1080,'FLORIDA',30);
INSERT INTO polls_municipio VALUES(1081,'GINEBRA GUACARI',30);
INSERT INTO polls_municipio VALUES(1082,'JAMUNDÍ',30);
INSERT INTO polls_municipio VALUES(1083,'LA CUMBRE',30);
INSERT INTO polls_municipio VALUES(1084,'LA UNIÓN',30);
INSERT INTO polls_municipio VALUES(1085,'LA VICTORIA',30);
INSERT INTO polls_municipio VALUES(1086,'OBANDO',30);
INSERT INTO polls_municipio VALUES(1087,'PALMIRA',30);
INSERT INTO polls_municipio VALUES(1088,'PRADERA',30);
INSERT INTO polls_municipio VALUES(1089,'RESTREPO',30);
INSERT INTO polls_municipio VALUES(1090,'RIO FRÍO',30);
INSERT INTO polls_municipio VALUES(1091,'ROLDANILLO',30);
INSERT INTO polls_municipio VALUES(1092,'SAN PEDRO',30);
INSERT INTO polls_municipio VALUES(1093,'SEVILLA',30);
INSERT INTO polls_municipio VALUES(1094,'TORO',30);
INSERT INTO polls_municipio VALUES(1095,'TRUJILLO',30);
INSERT INTO polls_municipio VALUES(1096,'TULÚA',30);
INSERT INTO polls_municipio VALUES(1097,'ULLOA',30);
INSERT INTO polls_municipio VALUES(1098,'VERSALLES',30);
INSERT INTO polls_municipio VALUES(1099,'VIJES',30);
INSERT INTO polls_municipio VALUES(1100,'YOTOCO',30);
INSERT INTO polls_municipio VALUES(1101,'YUMBO',30);
INSERT INTO polls_municipio VALUES(1102,'ZARZAL',30);
INSERT INTO polls_municipio VALUES(1103,'CARURÚ',31);
INSERT INTO polls_municipio VALUES(1104,'MITÚ',31);
INSERT INTO polls_municipio VALUES(1105,'PACOA',31);
INSERT INTO polls_municipio VALUES(1106,'PAPUNAUA',31);
INSERT INTO polls_municipio VALUES(1107,'TARAIRA',31);
INSERT INTO polls_municipio VALUES(1108,'YAVARATÉ',31);
INSERT INTO polls_municipio VALUES(1109,'CUMARIBO',32);
INSERT INTO polls_municipio VALUES(1110,'LA PRIMAVERA',32);
INSERT INTO polls_municipio VALUES(1111,'PUERTO CARREÑO',32);
INSERT INTO polls_municipio VALUES(1112,'SANTA ROSALIA',32);


INSERT INTO polls_poll VALUES(1,'Escala de Ideación Suicida','2014-10-31 01:44:47','2014-10-31 02:33:03','<p style="text-align: center;"><strong>(Beck Scale for Suicide Ideation, BSSI, Beck, Kovacs y Wasserman, 1979)</strong><strong></strong></p><p style="text-align: center;">(Traducción y adaptación de C. Vázquez)</p>','<p>Seleccione una de las opciones para cada pregunta. Una vez elegida su respuesta presione el botón "Continuar" para almacenar la respuesta y continuar con la siguiente.</p>');

INSERT INTO polls_pollsection VALUES(1,'I. CARACTERÍSTICAS DE ACTITUDES HACIA VIVIR/MORIR',1,1);
INSERT INTO polls_pollsection VALUES(2,'II. CARACTERÍSTICAS DEL DESEO/IDEACION DE SUICIDIO',2,1);
INSERT INTO polls_pollsection VALUES(3,'III. CARACTERÍSTICAS DEL INTENTO EN CUESTIÓN',3,1);
INSERT INTO polls_pollsection VALUES(4,'IV. ACTUALIZACIÓN DEL INTENTO EN CUESTIÓN',4,1);
INSERT INTO polls_pollsection VALUES(5,'V. FACTORES PREVIOS (no incluibles en la puntuación total)',5,1);


INSERT INTO polls_question VALUES(2,'Deseo de vivir',1,'Elija una de las opciones y presione "Continuar".',1,1);
INSERT INTO polls_question VALUES(3,'Deseo de morir',2,'Elija una de las opciones y presione "Continuar".',1,1);
INSERT INTO polls_question VALUES(4,'Razones para vivir/morir',3,'Elija una de las opciones y presione "Continuar".',1,1);
INSERT INTO polls_question VALUES(5,'Deseo de efectuar un intento activo de suicidio',4,'Elija una de las opciones y presione "Continuar".',1,1);
INSERT INTO polls_question VALUES(6,'Intento pasivo de suicidio',5,'Elija una de las opciones y presione "Continuar".',1,1);
INSERT INTO polls_question VALUES(7,'Dimensión temporal: Duración',6,'Elija una de las opciones y presione "Continuar".',1,2);
INSERT INTO polls_question VALUES(8,'Dimensión temporal: frecuencia',7,'Elija una de las opciones y presione "Continuar".',1,2);
INSERT INTO polls_question VALUES(9,'Actitud hacia la ideación/deseo',8,'Elija una de las opciones y presione "Continuar".',1,2);
INSERT INTO polls_question VALUES(10,'Control sobre el deseo de actuación o acto suicida',9,'Elija una de las opciones y presione "Continuar".',1,2);
INSERT INTO polls_question VALUES(11,'Barreras para el intento activo (por ejemplo: la familia, religión, posibilidad de lesión grave si se fracasa; irreversibilidad del intento)',10,'Elija una de las opciones y presione "Continuar".',1,2);
INSERT INTO polls_question VALUES(12,'Razón del intento en cuestión',11,'Elija una de las opciones y presione "Continuar".',1,2);
INSERT INTO polls_question VALUES(13,'Método: Especificidad/planeación',12,'Elija una de las opciones y presione "Continuar".',1,3);
INSERT INTO polls_question VALUES(14,'Método: Disponibilidad/oportunidad',13,'Elija una de las opciones y presione "Continuar".',1,3);
INSERT INTO polls_question VALUES(15,'Sensación de «capacidad» para llevar a cabo un intento',14,'Elija una de las opciones y presione "Continuar".',1,3);
INSERT INTO polls_question VALUES(16,'Expectativas/anticipación del intento real',15,'Elija una de las opciones y presione "Continuar".',1,3);
INSERT INTO polls_question VALUES(17,'Preparación real',16,'Elija una de las opciones y presione "Continuar".',1,4);
INSERT INTO polls_question VALUES(18,'Nota de suicidio',17,'Elija una de las opciones y presione "Continuar".',1,4);
INSERT INTO polls_question VALUES(19,'Actos finales de anticipación de la muerte (por ejemplo: seguros, testamento, donaciones)',18,'Elija una de las opciones y presione "Continuar".',1,4);
INSERT INTO polls_question VALUES(20,'Engaño/encubrimiento del engaño',19,'Elija una de las opciones y presione "Continuar".',1,4);
INSERT INTO polls_question VALUES(21,'Intentos previos de suicidio',20,'Elija una de las opciones y presione "Continuar".',1,5);
INSERT INTO polls_question VALUES(22,'Intención de morir asociada con el último intento',21,'Elija una de las opciones y presione "Continuar".',1,5);



INSERT INTO polls_option VALUES(1,'0: Moderado a fuerte',1,2);
INSERT INTO polls_option VALUES(2,'1: Débil',2,2);
INSERT INTO polls_option VALUES(3,'2: Ninguno',3,2);
INSERT INTO polls_option VALUES(4,'0: Ninguno',1,3);
INSERT INTO polls_option VALUES(5,'1: Débil',2,3);
INSERT INTO polls_option VALUES(6,'2: Moderado a fuerte',3,3);
INSERT INTO polls_option VALUES(7,'0: Las de vivir superan a las de morir',1,4);
INSERT INTO polls_option VALUES(8,'1: Mas o menos igual',2,4);
INSERT INTO polls_option VALUES(9,'2: Las de morir superan a las de vivir',3,4);
INSERT INTO polls_option VALUES(10,'0: Ninguno',1,5);
INSERT INTO polls_option VALUES(11,'1: Débil',2,5);
INSERT INTO polls_option VALUES(12,'2: Moderado a fuerte',3,5);
INSERT INTO polls_option VALUES(13,'0: Tomaría precauciones para salvar la vida',1,6);
INSERT INTO polls_option VALUES(14,'1: Dejaría al azar la vida o la muerte (por ejemplo, cruzar sin mirar una calle)',2,6);
INSERT INTO polls_option VALUES(15,'2: Evitaria las medidas necesarias para salvar o mantener la vida (por ejemplo, un diabético que deja de tomar insulina)',3,6);
INSERT INTO polls_option VALUES(16,'0: Breve, períodos fugaces',1,7);
INSERT INTO polls_option VALUES(17,'1: Períodos más largos',2,7);
INSERT INTO polls_option VALUES(18,'2: Continuo (crónico) o casi continuo',3,7);
INSERT INTO polls_option VALUES(19,'0: Infrecuente, ocasional',1,8);
INSERT INTO polls_option VALUES(20,'1: Intermitente',2,8);
INSERT INTO polls_option VALUES(21,'2: Persistente o continua',3,8);
INSERT INTO polls_option VALUES(22,'0: Rechazo',1,9);
INSERT INTO polls_option VALUES(23,'1: Ambivalente; indiferente',2,9);
INSERT INTO polls_option VALUES(24,'2: Aceptación',3,9);
INSERT INTO polls_option VALUES(25,'0: Tiene sensación de control',1,10);
INSERT INTO polls_option VALUES(26,'1: Inseguro del control',2,10);
INSERT INTO polls_option VALUES(27,'2: No tiene sensación de control',3,10);
INSERT INTO polls_option VALUES(28,'0: No intentaría suicidio a causa de una barrera',1,11);
INSERT INTO polls_option VALUES(29,'1: Alguna preocupación sobre las barreras',2,11);
INSERT INTO polls_option VALUES(30,'2: Mínima o nula preocupación sobre las barreras',3,11);
INSERT INTO polls_option VALUES(31,'0: Manipular el entorno: Conseguir atención, venganza',1,12);
INSERT INTO polls_option VALUES(32,'1: Combinación de «1» y «2»',2,12);
INSERT INTO polls_option VALUES(33,'2: Escape, resolver problemas, desaparecer',3,12);
INSERT INTO polls_option VALUES(34,'0: No en cuestión',1,13);
INSERT INTO polls_option VALUES(35,'1: Considerado pero sin elaborar detalles',2,13);
INSERT INTO polls_option VALUES(36,'2: Detalles bien elaborados; bien formulado',3,13);
INSERT INTO polls_option VALUES(37,'0: Método no disponible; ninguna oportunidad',1,14);
INSERT INTO polls_option VALUES(38,'1: El método llevaría tiempo/esfuerzo; oportunidad no fácilmente disponible',2,14);
INSERT INTO polls_option VALUES(39,'2: Oportunidad futura o anticipada disponibilidad de método',3,14);
INSERT INTO polls_option VALUES(40,'0: Cobarde, demasiado débil, asustado, incapaz',1,15);
INSERT INTO polls_option VALUES(41,'1: Inseguro de la valentía o de la capacidad',2,15);
INSERT INTO polls_option VALUES(42,'2: Seguro de la valentía o de la capacidad',3,15);
INSERT INTO polls_option VALUES(43,'0: No',1,16);
INSERT INTO polls_option VALUES(44,'1: Inciertas, no seguro',2,16);
INSERT INTO polls_option VALUES(45,'2: Sí',3,16);
INSERT INTO polls_option VALUES(46,'0: Ninguno',1,21);
INSERT INTO polls_option VALUES(47,'1: Uno',2,21);
INSERT INTO polls_option VALUES(48,'2: Más de uno',3,21);
INSERT INTO polls_option VALUES(49,'0: Baja',1,22);
INSERT INTO polls_option VALUES(50,' 1: Moderada; ambivalente; incierta',2,22);
INSERT INTO polls_option VALUES(51,'2: Alta',3,22);
INSERT INTO polls_option VALUES(52,'0: Ninguna',1,17);
INSERT INTO polls_option VALUES(53,'1: Parcial (por ejemplo, comenzar a acumular pastillas)',2,17);
INSERT INTO polls_option VALUES(54,'2: Completa (por ejemplo, tiene pastillas, cuchillas, un arma cargada)',3,17);
INSERT INTO polls_option VALUES(55,'0: Ninguna',1,18);
INSERT INTO polls_option VALUES(56,'1: Comenzada pero no acabada; sólo se ha pensado en ella',2,18);
INSERT INTO polls_option VALUES(57,'2: Acabada',3,18);
INSERT INTO polls_option VALUES(58,'0: Ninguno',1,19);
INSERT INTO polls_option VALUES(59,'1: Algunas ideas o se han hecho algunas gestiones',2,19);
INSERT INTO polls_option VALUES(60,'2: Planes finales efectuados o gestiones finalizadas',3,19);
INSERT INTO polls_option VALUES(61,'0: Ideas expresadas abiertamente',1,20);
INSERT INTO polls_option VALUES(62,'1: Ideas reservadas',2,20);
INSERT INTO polls_option VALUES(63,'2: Intento de engañar, mentir, encubrir',3,20);
