INSERT INTO polls_municipio (id, nombre) VALUES (1, "EL ENCANTO");
INSERT INTO polls_municipio (id, nombre) VALUES (2, "LA CHORRERA");
INSERT INTO polls_municipio (id, nombre) VALUES (3, "LA PEDRERA");
INSERT INTO polls_municipio (id, nombre) VALUES (4, "LA VICTORIA");
INSERT INTO polls_municipio (id, nombre) VALUES (5, "LETICIA");
INSERT INTO polls_municipio (id, nombre) VALUES (6, "MIRITI");
INSERT INTO polls_municipio (id, nombre) VALUES (7, "PUERTO ALEGRIA");
INSERT INTO polls_municipio (id, nombre) VALUES (8, "PUERTO ARICA");
INSERT INTO polls_municipio (id, nombre) VALUES (9, "PUERTO NARIÑO");
INSERT INTO polls_municipio (id, nombre) VALUES (10, "PUERTO SANTANDER");
INSERT INTO polls_municipio (id, nombre) VALUES (11, "TURAPACA");
INSERT INTO polls_municipio (id, nombre) VALUES (12, "ABEJORRAL");
INSERT INTO polls_municipio (id, nombre) VALUES (13, "ABRIAQUI");
INSERT INTO polls_municipio (id, nombre) VALUES (14, "ALEJANDRIA");
INSERT INTO polls_municipio (id, nombre) VALUES (15, "AMAGA");
INSERT INTO polls_municipio (id, nombre) VALUES (16, "AMALFI");
INSERT INTO polls_municipio (id, nombre) VALUES (17, "ANDES");
INSERT INTO polls_municipio (id, nombre) VALUES (18, "ANGELOPOLIS");
INSERT INTO polls_municipio (id, nombre) VALUES (19, "ANGOSTURA");
INSERT INTO polls_municipio (id, nombre) VALUES (20, "ANORI");
INSERT INTO polls_municipio (id, nombre) VALUES (21, "ANTIOQUIA");
INSERT INTO polls_municipio (id, nombre) VALUES (22, "ANZA");
INSERT INTO polls_municipio (id, nombre) VALUES (23, "APARTADO");
INSERT INTO polls_municipio (id, nombre) VALUES (24, "ARBOLETES");
INSERT INTO polls_municipio (id, nombre) VALUES (25, "ARGELIA");
INSERT INTO polls_municipio (id, nombre) VALUES (26, "ARMENIA");
INSERT INTO polls_municipio (id, nombre) VALUES (27, "BARBOSA");
INSERT INTO polls_municipio (id, nombre) VALUES (28, "BELLO");
INSERT INTO polls_municipio (id, nombre) VALUES (29, "BELMIRA");
INSERT INTO polls_municipio (id, nombre) VALUES (30, "BETANIA");
INSERT INTO polls_municipio (id, nombre) VALUES (31, "BETULIA");
INSERT INTO polls_municipio (id, nombre) VALUES (32, "BOLIVAR");
INSERT INTO polls_municipio (id, nombre) VALUES (33, "BRICEÑO");
INSERT INTO polls_municipio (id, nombre) VALUES (34, "BURITICA");
INSERT INTO polls_municipio (id, nombre) VALUES (35, "CACERES");
INSERT INTO polls_municipio (id, nombre) VALUES (36, "CAICEDO");
INSERT INTO polls_municipio (id, nombre) VALUES (37, "CALDAS");
INSERT INTO polls_municipio (id, nombre) VALUES (38, "CAMPAMENTO");
INSERT INTO polls_municipio (id, nombre) VALUES (39, "CANASGORDAS");
INSERT INTO polls_municipio (id, nombre) VALUES (40, "CARACOLI");
INSERT INTO polls_municipio (id, nombre) VALUES (41, "CARAMANTA");
INSERT INTO polls_municipio (id, nombre) VALUES (42, "CAREPA");
INSERT INTO polls_municipio (id, nombre) VALUES (43, "CARMEN DE VIBORAL");
INSERT INTO polls_municipio (id, nombre) VALUES (44, "CAROLINA DEL PRINCIPE");
INSERT INTO polls_municipio (id, nombre) VALUES (45, "CAUCASIA");
INSERT INTO polls_municipio (id, nombre) VALUES (46, "CHIGORODO");
INSERT INTO polls_municipio (id, nombre) VALUES (47, "CISNEROS");
INSERT INTO polls_municipio (id, nombre) VALUES (48, "COCORNA");
INSERT INTO polls_municipio (id, nombre) VALUES (49, "CONCEPCION");
INSERT INTO polls_municipio (id, nombre) VALUES (50, "CONCORDIA");
INSERT INTO polls_municipio (id, nombre) VALUES (51, "COPACABANA");
INSERT INTO polls_municipio (id, nombre) VALUES (52, "DABEIBA");
INSERT INTO polls_municipio (id, nombre) VALUES (53, "DONMATIAS");
INSERT INTO polls_municipio (id, nombre) VALUES (54, "EBEJICO");
INSERT INTO polls_municipio (id, nombre) VALUES (55, "EL BAGRE");
INSERT INTO polls_municipio (id, nombre) VALUES (56, "EL PENOL");
INSERT INTO polls_municipio (id, nombre) VALUES (57, "EL RETIRO");
INSERT INTO polls_municipio (id, nombre) VALUES (58, "ENTRERRIOS");
INSERT INTO polls_municipio (id, nombre) VALUES (59, "ENVIGADO");
INSERT INTO polls_municipio (id, nombre) VALUES (60, "FREDONIA");
INSERT INTO polls_municipio (id, nombre) VALUES (61, "FRONTINO");
INSERT INTO polls_municipio (id, nombre) VALUES (62, "GIRALDO");
INSERT INTO polls_municipio (id, nombre) VALUES (63, "GIRARDOTA");
INSERT INTO polls_municipio (id, nombre) VALUES (64, "GOMEZ PLATA");
INSERT INTO polls_municipio (id, nombre) VALUES (65, "GRANADA");
INSERT INTO polls_municipio (id, nombre) VALUES (66, "GUADALUPE");
INSERT INTO polls_municipio (id, nombre) VALUES (67, "GUARNE");
INSERT INTO polls_municipio (id, nombre) VALUES (68, "GUATAQUE");
INSERT INTO polls_municipio (id, nombre) VALUES (69, "HELICONIA");
INSERT INTO polls_municipio (id, nombre) VALUES (70, "HISPANIA");
INSERT INTO polls_municipio (id, nombre) VALUES (71, "ITAGUI");
INSERT INTO polls_municipio (id, nombre) VALUES (72, "ITUANGO");
INSERT INTO polls_municipio (id, nombre) VALUES (73, "JARDIN");
INSERT INTO polls_municipio (id, nombre) VALUES (74, "JERICO");
INSERT INTO polls_municipio (id, nombre) VALUES (75, "LA CEJA");
INSERT INTO polls_municipio (id, nombre) VALUES (76, "LA ESTRELLA");
INSERT INTO polls_municipio (id, nombre) VALUES (77, "LA PINTADA");
INSERT INTO polls_municipio (id, nombre) VALUES (78, "LA UNION");
INSERT INTO polls_municipio (id, nombre) VALUES (79, "LIBORINA");
INSERT INTO polls_municipio (id, nombre) VALUES (80, "MACEO");
INSERT INTO polls_municipio (id, nombre) VALUES (81, "MARINILLA");
INSERT INTO polls_municipio (id, nombre) VALUES (82, "MEDELLIN");
INSERT INTO polls_municipio (id, nombre) VALUES (83, "MONTEBELLO");
INSERT INTO polls_municipio (id, nombre) VALUES (84, "MURINDO");
INSERT INTO polls_municipio (id, nombre) VALUES (85, "MUTATA");
INSERT INTO polls_municipio (id, nombre) VALUES (86, "NARINO");
INSERT INTO polls_municipio (id, nombre) VALUES (87, "NECHI");
INSERT INTO polls_municipio (id, nombre) VALUES (88, "NECOCLI");
INSERT INTO polls_municipio (id, nombre) VALUES (89, "OLAYA");
INSERT INTO polls_municipio (id, nombre) VALUES (90, "PEQUE");
INSERT INTO polls_municipio (id, nombre) VALUES (91, "PUEBLORRICO");
INSERT INTO polls_municipio (id, nombre) VALUES (92, "PUERTO BERRIO");
INSERT INTO polls_municipio (id, nombre) VALUES (93, "PUERTO NARE");
INSERT INTO polls_municipio (id, nombre) VALUES (94, "PUERTO TRIUNFO");
INSERT INTO polls_municipio (id, nombre) VALUES (95, "REMEDIOS");
INSERT INTO polls_municipio (id, nombre) VALUES (96, "RIONEGRO");
INSERT INTO polls_municipio (id, nombre) VALUES (97, "SABANALARGA");
INSERT INTO polls_municipio (id, nombre) VALUES (98, "SABANETA");
INSERT INTO polls_municipio (id, nombre) VALUES (99, "SALGAR");
INSERT INTO polls_municipio (id, nombre) VALUES (100, "SAN ANDRES DE CUERQUIA");
INSERT INTO polls_municipio (id, nombre) VALUES (101, "SAN CARLOS");
INSERT INTO polls_municipio (id, nombre) VALUES (102, "SAN FRANCISCO");
INSERT INTO polls_municipio (id, nombre) VALUES (103, "SAN JERONIMO");
INSERT INTO polls_municipio (id, nombre) VALUES (104, "SAN JOSE DE LA MONTAÑA");
INSERT INTO polls_municipio (id, nombre) VALUES (105, "SAN JUAN DE URABA");
INSERT INTO polls_municipio (id, nombre) VALUES (106, "SAN LUIS");
INSERT INTO polls_municipio (id, nombre) VALUES (107, "SAN PEDRO DE LOS MILAGROS");
INSERT INTO polls_municipio (id, nombre) VALUES (108, "SAN PEDRO DE URABA");
INSERT INTO polls_municipio (id, nombre) VALUES (109, "SAN RAFAEL");
INSERT INTO polls_municipio (id, nombre) VALUES (110, "SAN ROQUE");
INSERT INTO polls_municipio (id, nombre) VALUES (111, "SAN VICENTE");
INSERT INTO polls_municipio (id, nombre) VALUES (112, "SANTA BARBARA");
INSERT INTO polls_municipio (id, nombre) VALUES (113, "SANTA ROSA DE OSOS");
INSERT INTO polls_municipio (id, nombre) VALUES (114, "SANTO DOMINGO");
INSERT INTO polls_municipio (id, nombre) VALUES (115, "SANTUARIO");
INSERT INTO polls_municipio (id, nombre) VALUES (116, "SEGOVIA");
INSERT INTO polls_municipio (id, nombre) VALUES (117, "SONSON");
INSERT INTO polls_municipio (id, nombre) VALUES (118, "SOPETRAN");
INSERT INTO polls_municipio (id, nombre) VALUES (119, "TAMESIS");
INSERT INTO polls_municipio (id, nombre) VALUES (120, "TARAZA");
INSERT INTO polls_municipio (id, nombre) VALUES (121, "TARSO");
INSERT INTO polls_municipio (id, nombre) VALUES (122, "TITIRIBI");
INSERT INTO polls_municipio (id, nombre) VALUES (123, "TOLEDO");
INSERT INTO polls_municipio (id, nombre) VALUES (124, "TURBO");
INSERT INTO polls_municipio (id, nombre) VALUES (125, "URAMITA");
INSERT INTO polls_municipio (id, nombre) VALUES (126, "URRAO");
INSERT INTO polls_municipio (id, nombre) VALUES (127, "VALDIVIA");
INSERT INTO polls_municipio (id, nombre) VALUES (128, "VALPARAISO");
INSERT INTO polls_municipio (id, nombre) VALUES (129, "VEGACHI");
INSERT INTO polls_municipio (id, nombre) VALUES (130, "VENECIA");
INSERT INTO polls_municipio (id, nombre) VALUES (131, "VIGIA DEL FUERTE");
INSERT INTO polls_municipio (id, nombre) VALUES (132, "YALI");
INSERT INTO polls_municipio (id, nombre) VALUES (133, "YARUMAL");
INSERT INTO polls_municipio (id, nombre) VALUES (134, "YOLOMBO");
INSERT INTO polls_municipio (id, nombre) VALUES (135, "YONDO");
INSERT INTO polls_municipio (id, nombre) VALUES (136, "ZARAGOZA");
INSERT INTO polls_municipio (id, nombre) VALUES (137, "ARAUCA");
INSERT INTO polls_municipio (id, nombre) VALUES (138, "ARAUQUITA");
INSERT INTO polls_municipio (id, nombre) VALUES (139, "CRAVO NORTE");
INSERT INTO polls_municipio (id, nombre) VALUES (140, "FORTUL");
INSERT INTO polls_municipio (id, nombre) VALUES (141, "PUERTO RONDON");
INSERT INTO polls_municipio (id, nombre) VALUES (142, "SARAVENA");
INSERT INTO polls_municipio (id, nombre) VALUES (143, "TAME");
INSERT INTO polls_municipio (id, nombre) VALUES (144, "BARANOA");
INSERT INTO polls_municipio (id, nombre) VALUES (145, "BARRANQUILLA");
INSERT INTO polls_municipio (id, nombre) VALUES (146, "CAMPO DE LA CRUZ");
INSERT INTO polls_municipio (id, nombre) VALUES (147, "CANDELARIA");
INSERT INTO polls_municipio (id, nombre) VALUES (148, "GALAPA");
INSERT INTO polls_municipio (id, nombre) VALUES (149, "JUAN DE ACOSTA");
INSERT INTO polls_municipio (id, nombre) VALUES (150, "LURUACO");
INSERT INTO polls_municipio (id, nombre) VALUES (151, "MALAMBO");
INSERT INTO polls_municipio (id, nombre) VALUES (152, "MANATI");
INSERT INTO polls_municipio (id, nombre) VALUES (153, "PALMAR DE VARELA");
INSERT INTO polls_municipio (id, nombre) VALUES (154, "PIOJO");
INSERT INTO polls_municipio (id, nombre) VALUES (155, "POLO NUEVO");
INSERT INTO polls_municipio (id, nombre) VALUES (156, "PONEDERA");
INSERT INTO polls_municipio (id, nombre) VALUES (157, "PUERTO COLOMBIA");
INSERT INTO polls_municipio (id, nombre) VALUES (158, "REPELON");
INSERT INTO polls_municipio (id, nombre) VALUES (159, "SABANAGRANDE");
INSERT INTO polls_municipio (id, nombre) VALUES (160, "SABANALARGA");
INSERT INTO polls_municipio (id, nombre) VALUES (161, "SANTA LUCIA");
INSERT INTO polls_municipio (id, nombre) VALUES (162, "SANTO TOMAS");
INSERT INTO polls_municipio (id, nombre) VALUES (163, "SOLEDAD");
INSERT INTO polls_municipio (id, nombre) VALUES (164, "SUAN");
INSERT INTO polls_municipio (id, nombre) VALUES (165, "TUBARA");
INSERT INTO polls_municipio (id, nombre) VALUES (166, "USIACURI");
INSERT INTO polls_municipio (id, nombre) VALUES (167, "ACHI");
INSERT INTO polls_municipio (id, nombre) VALUES (168, "ALTOS DEL ROSARIO");
INSERT INTO polls_municipio (id, nombre) VALUES (169, "ARENAL");
INSERT INTO polls_municipio (id, nombre) VALUES (170, "ARJONA");
INSERT INTO polls_municipio (id, nombre) VALUES (171, "ARROYOHONDO");
INSERT INTO polls_municipio (id, nombre) VALUES (172, "BARRANCO DE LOBA");
INSERT INTO polls_municipio (id, nombre) VALUES (173, "BRAZUELO DE PAPAYAL");
INSERT INTO polls_municipio (id, nombre) VALUES (174, "CALAMAR");
INSERT INTO polls_municipio (id, nombre) VALUES (175, "CANTAGALLO");
INSERT INTO polls_municipio (id, nombre) VALUES (176, "CARTAGENA DE INDIAS");
INSERT INTO polls_municipio (id, nombre) VALUES (177, "CICUCO");
INSERT INTO polls_municipio (id, nombre) VALUES (178, "CLEMENCIA");
INSERT INTO polls_municipio (id, nombre) VALUES (179, "CORDOBA");
INSERT INTO polls_municipio (id, nombre) VALUES (180, "EL CARMEN DE BOLIVAR");
INSERT INTO polls_municipio (id, nombre) VALUES (181, "EL GUAMO");
INSERT INTO polls_municipio (id, nombre) VALUES (182, "EL PENION");
INSERT INTO polls_municipio (id, nombre) VALUES (183, "HATILLO DE LOBA");
INSERT INTO polls_municipio (id, nombre) VALUES (184, "MAGANGUE");
INSERT INTO polls_municipio (id, nombre) VALUES (185, "MAHATES");
INSERT INTO polls_municipio (id, nombre) VALUES (186, "MARGARITA");
INSERT INTO polls_municipio (id, nombre) VALUES (187, "MARIA LA BAJA");
INSERT INTO polls_municipio (id, nombre) VALUES (188, "MONTECRISTO");
INSERT INTO polls_municipio (id, nombre) VALUES (189, "MORALES");
INSERT INTO polls_municipio (id, nombre) VALUES (190, "MORALES");
INSERT INTO polls_municipio (id, nombre) VALUES (191, "NOROSI");
INSERT INTO polls_municipio (id, nombre) VALUES (192, "PINILLOS");
INSERT INTO polls_municipio (id, nombre) VALUES (193, "REGIDOR");
INSERT INTO polls_municipio (id, nombre) VALUES (194, "RIO VIEJO");
INSERT INTO polls_municipio (id, nombre) VALUES (195, "SAN CRISTOBAL");
INSERT INTO polls_municipio (id, nombre) VALUES (196, "SAN ESTANISLAO");
INSERT INTO polls_municipio (id, nombre) VALUES (197, "SAN FERNANDO");
INSERT INTO polls_municipio (id, nombre) VALUES (198, "SAN JACINTO");
INSERT INTO polls_municipio (id, nombre) VALUES (199, "SAN JACINTO DEL CAUCA");
INSERT INTO polls_municipio (id, nombre) VALUES (200, "SAN JUAN DE NEPOMUCENO");
INSERT INTO polls_municipio (id, nombre) VALUES (201, "SAN MARTIN DE LOBA");
INSERT INTO polls_municipio (id, nombre) VALUES (202, "SAN PABLO");
INSERT INTO polls_municipio (id, nombre) VALUES (203, "SAN PABLO NORTE");
INSERT INTO polls_municipio (id, nombre) VALUES (204, "SANTA CATALINA");
INSERT INTO polls_municipio (id, nombre) VALUES (205, "SANTA CRUZ DE MOMPOX");
INSERT INTO polls_municipio (id, nombre) VALUES (206, "SANTA ROSA");
INSERT INTO polls_municipio (id, nombre) VALUES (207, "SANTA ROSA DEL SUR");
INSERT INTO polls_municipio (id, nombre) VALUES (208, "SIMITI");
INSERT INTO polls_municipio (id, nombre) VALUES (209, "SOPLAVIENTO");
INSERT INTO polls_municipio (id, nombre) VALUES (210, "TALAIGUA NUEVO");
INSERT INTO polls_municipio (id, nombre) VALUES (211, "TUQUISIO");
INSERT INTO polls_municipio (id, nombre) VALUES (212, "TURBACO");
INSERT INTO polls_municipio (id, nombre) VALUES (213, "TURBANA");
INSERT INTO polls_municipio (id, nombre) VALUES (214, "VILLANUEVA");
INSERT INTO polls_municipio (id, nombre) VALUES (215, "ZAMBRANO");
INSERT INTO polls_municipio (id, nombre) VALUES (216, "AQUITANIA");
INSERT INTO polls_municipio (id, nombre) VALUES (217, "ARCABUCO");
INSERT INTO polls_municipio (id, nombre) VALUES (218, "BELÉN");
INSERT INTO polls_municipio (id, nombre) VALUES (219, "BERBEO");
INSERT INTO polls_municipio (id, nombre) VALUES (220, "BETÉITIVA");
INSERT INTO polls_municipio (id, nombre) VALUES (221, "BOAVITA");
INSERT INTO polls_municipio (id, nombre) VALUES (222, "BOYACÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (223, "BRICEÑO");
INSERT INTO polls_municipio (id, nombre) VALUES (224, "BUENAVISTA");
INSERT INTO polls_municipio (id, nombre) VALUES (225, "BUSBANZÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (226, "CALDAS");
INSERT INTO polls_municipio (id, nombre) VALUES (227, "CAMPO HERMOSO");
INSERT INTO polls_municipio (id, nombre) VALUES (228, "CERINZA");
INSERT INTO polls_municipio (id, nombre) VALUES (229, "CHINAVITA");
INSERT INTO polls_municipio (id, nombre) VALUES (230, "CHIQUINQUIRÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (231, "CHÍQUIZA");
INSERT INTO polls_municipio (id, nombre) VALUES (232, "CHISCAS");
INSERT INTO polls_municipio (id, nombre) VALUES (233, "CHITA");
INSERT INTO polls_municipio (id, nombre) VALUES (234, "CHITARAQUE");
INSERT INTO polls_municipio (id, nombre) VALUES (235, "CHIVATÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (236, "CIÉNEGA");
INSERT INTO polls_municipio (id, nombre) VALUES (237, "CÓMBITA");
INSERT INTO polls_municipio (id, nombre) VALUES (238, "COPER");
INSERT INTO polls_municipio (id, nombre) VALUES (239, "CORRALES");
INSERT INTO polls_municipio (id, nombre) VALUES (240, "COVARACHÍA");
INSERT INTO polls_municipio (id, nombre) VALUES (241, "CUBARA");
INSERT INTO polls_municipio (id, nombre) VALUES (242, "CUCAITA");
INSERT INTO polls_municipio (id, nombre) VALUES (243, "CUITIVA");
INSERT INTO polls_municipio (id, nombre) VALUES (244, "DUITAMA");
INSERT INTO polls_municipio (id, nombre) VALUES (245, "EL COCUY");
INSERT INTO polls_municipio (id, nombre) VALUES (246, "EL ESPINO");
INSERT INTO polls_municipio (id, nombre) VALUES (247, "FIRAVITOBA");
INSERT INTO polls_municipio (id, nombre) VALUES (248, "FLORESTA");
INSERT INTO polls_municipio (id, nombre) VALUES (249, "GACHANTIVÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (250, "GÁMEZA");
INSERT INTO polls_municipio (id, nombre) VALUES (251, "GARAGOA");
INSERT INTO polls_municipio (id, nombre) VALUES (252, "GUACAMAYAS");
INSERT INTO polls_municipio (id, nombre) VALUES (253, "GÜICÁN");
INSERT INTO polls_municipio (id, nombre) VALUES (254, "IZA");
INSERT INTO polls_municipio (id, nombre) VALUES (255, "JENESANO");
INSERT INTO polls_municipio (id, nombre) VALUES (256, "JERICÓ");
INSERT INTO polls_municipio (id, nombre) VALUES (257, "LA UVITA");
INSERT INTO polls_municipio (id, nombre) VALUES (258, "LA VICTORIA");
INSERT INTO polls_municipio (id, nombre) VALUES (259, "LABRANZA GRANDE");
INSERT INTO polls_municipio (id, nombre) VALUES (260, "MACANAL");
INSERT INTO polls_municipio (id, nombre) VALUES (261, "MARIPÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (262, "MIRAFLORES");
INSERT INTO polls_municipio (id, nombre) VALUES (263, "MONGUA");
INSERT INTO polls_municipio (id, nombre) VALUES (264, "MONGUÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (265, "MONIQUIRÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (266, "MOTAVITA");
INSERT INTO polls_municipio (id, nombre) VALUES (267, "MUZO");
INSERT INTO polls_municipio (id, nombre) VALUES (268, "NOBSA");
INSERT INTO polls_municipio (id, nombre) VALUES (269, "NUEVO COLÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (270, "OICATÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (271, "OTANCHE");
INSERT INTO polls_municipio (id, nombre) VALUES (272, "PACHAVITA");
INSERT INTO polls_municipio (id, nombre) VALUES (273, "PÁEZ");
INSERT INTO polls_municipio (id, nombre) VALUES (274, "PAIPA");
INSERT INTO polls_municipio (id, nombre) VALUES (275, "PAJARITO");
INSERT INTO polls_municipio (id, nombre) VALUES (276, "PANQUEBA");
INSERT INTO polls_municipio (id, nombre) VALUES (277, "PAUNA");
INSERT INTO polls_municipio (id, nombre) VALUES (278, "PAYA");
INSERT INTO polls_municipio (id, nombre) VALUES (279, "PAZ DE RÍO");
INSERT INTO polls_municipio (id, nombre) VALUES (280, "PESCA");
INSERT INTO polls_municipio (id, nombre) VALUES (281, "PISBA");
INSERT INTO polls_municipio (id, nombre) VALUES (282, "PUERTO BOYACA");
INSERT INTO polls_municipio (id, nombre) VALUES (283, "QUÍPAMA");
INSERT INTO polls_municipio (id, nombre) VALUES (284, "RAMIRIQUÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (285, "RÁQUIRA");
INSERT INTO polls_municipio (id, nombre) VALUES (286, "RONDÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (287, "SABOYÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (288, "SÁCHICA");
INSERT INTO polls_municipio (id, nombre) VALUES (289, "SAMACÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (290, "SAN EDUARDO");
INSERT INTO polls_municipio (id, nombre) VALUES (291, "SAN JOSÉ DE PARE");
INSERT INTO polls_municipio (id, nombre) VALUES (292, "SAN LUÍS DE GACENO");
INSERT INTO polls_municipio (id, nombre) VALUES (293, "SAN MATEO");
INSERT INTO polls_municipio (id, nombre) VALUES (294, "SAN MIGUEL DE SEMA");
INSERT INTO polls_municipio (id, nombre) VALUES (295, "SAN PABLO DE BORBUR");
INSERT INTO polls_municipio (id, nombre) VALUES (296, "SANTA MARÍA");
INSERT INTO polls_municipio (id, nombre) VALUES (297, "SANTA ROSA DE VITERBO");
INSERT INTO polls_municipio (id, nombre) VALUES (298, "SANTA SOFÍA");
INSERT INTO polls_municipio (id, nombre) VALUES (299, "SANTANA");
INSERT INTO polls_municipio (id, nombre) VALUES (300, "SATIVANORTE");
INSERT INTO polls_municipio (id, nombre) VALUES (301, "SATIVASUR");
INSERT INTO polls_municipio (id, nombre) VALUES (302, "SIACHOQUE");
INSERT INTO polls_municipio (id, nombre) VALUES (303, "SOATÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (304, "SOCHA");
INSERT INTO polls_municipio (id, nombre) VALUES (305, "SOCOTÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (306, "SOGAMOSO");
INSERT INTO polls_municipio (id, nombre) VALUES (307, "SORA");
INSERT INTO polls_municipio (id, nombre) VALUES (308, "SORACÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (309, "SOTAQUIRÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (310, "SUSACÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (311, "SUTARMACHÁN");
INSERT INTO polls_municipio (id, nombre) VALUES (312, "TASCO");
INSERT INTO polls_municipio (id, nombre) VALUES (313, "TIBANÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (314, "TIBASOSA");
INSERT INTO polls_municipio (id, nombre) VALUES (315, "TINJACÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (316, "TIPACOQUE");
INSERT INTO polls_municipio (id, nombre) VALUES (317, "TOCA");
INSERT INTO polls_municipio (id, nombre) VALUES (318, "TOGÜÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (319, "TÓPAGA");
INSERT INTO polls_municipio (id, nombre) VALUES (320, "TOTA");
INSERT INTO polls_municipio (id, nombre) VALUES (321, "TUNJA");
INSERT INTO polls_municipio (id, nombre) VALUES (322, "TUNUNGUÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (323, "TURMEQUÉ");
INSERT INTO polls_municipio (id, nombre) VALUES (324, "TUTA");
INSERT INTO polls_municipio (id, nombre) VALUES (325, "TUTAZÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (326, "UMBITA");
INSERT INTO polls_municipio (id, nombre) VALUES (327, "VENTA QUEMADA");
INSERT INTO polls_municipio (id, nombre) VALUES (328, "VILLA DE LEYVA");
INSERT INTO polls_municipio (id, nombre) VALUES (329, "VIRACACHÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (330, "ZETAQUIRA");
INSERT INTO polls_municipio (id, nombre) VALUES (331, "AGUADAS");
INSERT INTO polls_municipio (id, nombre) VALUES (332, "ANSERMA");
INSERT INTO polls_municipio (id, nombre) VALUES (333, "ARANZAZU");
INSERT INTO polls_municipio (id, nombre) VALUES (334, "BELALCAZAR");
INSERT INTO polls_municipio (id, nombre) VALUES (335, "CHINCHINÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (336, "FILADELFIA");
INSERT INTO polls_municipio (id, nombre) VALUES (337, "LA DORADA");
INSERT INTO polls_municipio (id, nombre) VALUES (338, "LA MERCED");
INSERT INTO polls_municipio (id, nombre) VALUES (339, "MANIZALES");
INSERT INTO polls_municipio (id, nombre) VALUES (340, "MANZANARES");
INSERT INTO polls_municipio (id, nombre) VALUES (341, "MARMATO");
INSERT INTO polls_municipio (id, nombre) VALUES (342, "MARQUETALIA");
INSERT INTO polls_municipio (id, nombre) VALUES (343, "MARULANDA");
INSERT INTO polls_municipio (id, nombre) VALUES (344, "NEIRA");
INSERT INTO polls_municipio (id, nombre) VALUES (345, "NORCASIA");
INSERT INTO polls_municipio (id, nombre) VALUES (346, "PACORA");
INSERT INTO polls_municipio (id, nombre) VALUES (347, "PALESTINA");
INSERT INTO polls_municipio (id, nombre) VALUES (348, "PENSILVANIA");
INSERT INTO polls_municipio (id, nombre) VALUES (349, "RIOSUCIO");
INSERT INTO polls_municipio (id, nombre) VALUES (350, "RISARALDA");
INSERT INTO polls_municipio (id, nombre) VALUES (351, "SALAMINA");
INSERT INTO polls_municipio (id, nombre) VALUES (352, "SAMANA");
INSERT INTO polls_municipio (id, nombre) VALUES (353, "SAN JOSE");
INSERT INTO polls_municipio (id, nombre) VALUES (354, "SUPÍA");
INSERT INTO polls_municipio (id, nombre) VALUES (355, "VICTORIA");
INSERT INTO polls_municipio (id, nombre) VALUES (356, "VILLAMARÍA");
INSERT INTO polls_municipio (id, nombre) VALUES (357, "VITERBO");
INSERT INTO polls_municipio (id, nombre) VALUES (358, "ALBANIA");
INSERT INTO polls_municipio (id, nombre) VALUES (359, "BELÉN ANDAQUIES");
INSERT INTO polls_municipio (id, nombre) VALUES (360, "CARTAGENA DEL CHAIRA");
INSERT INTO polls_municipio (id, nombre) VALUES (361, "CURILLO");
INSERT INTO polls_municipio (id, nombre) VALUES (362, "EL DONCELLO");
INSERT INTO polls_municipio (id, nombre) VALUES (363, "EL PAUJIL");
INSERT INTO polls_municipio (id, nombre) VALUES (364, "FLORENCIA");
INSERT INTO polls_municipio (id, nombre) VALUES (365, "LA MONTAÑITA");
INSERT INTO polls_municipio (id, nombre) VALUES (366, "MILÁN");
INSERT INTO polls_municipio (id, nombre) VALUES (367, "MORELIA");
INSERT INTO polls_municipio (id, nombre) VALUES (368, "PUERTO RICO");
INSERT INTO polls_municipio (id, nombre) VALUES (369, "SAN  VICENTE DEL CAGUAN");
INSERT INTO polls_municipio (id, nombre) VALUES (370, "SAN JOSÉ DE FRAGUA");
INSERT INTO polls_municipio (id, nombre) VALUES (371, "SOLANO");
INSERT INTO polls_municipio (id, nombre) VALUES (372, "SOLITA");
INSERT INTO polls_municipio (id, nombre) VALUES (373, "VALPARAÍSO");
INSERT INTO polls_municipio (id, nombre) VALUES (374, "AGUAZUL");
INSERT INTO polls_municipio (id, nombre) VALUES (375, "CHAMEZA");
INSERT INTO polls_municipio (id, nombre) VALUES (376, "HATO COROZAL");
INSERT INTO polls_municipio (id, nombre) VALUES (377, "LA SALINA");
INSERT INTO polls_municipio (id, nombre) VALUES (378, "MANÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (379, "MONTERREY");
INSERT INTO polls_municipio (id, nombre) VALUES (380, "NUNCHIA");
INSERT INTO polls_municipio (id, nombre) VALUES (381, "OROCUE");
INSERT INTO polls_municipio (id, nombre) VALUES (382, "PAZ DE ARIPORO");
INSERT INTO polls_municipio (id, nombre) VALUES (383, "PORE");
INSERT INTO polls_municipio (id, nombre) VALUES (384, "RECETOR");
INSERT INTO polls_municipio (id, nombre) VALUES (385, "SABANA LARGA");
INSERT INTO polls_municipio (id, nombre) VALUES (386, "SACAMA");
INSERT INTO polls_municipio (id, nombre) VALUES (387, "SAN LUIS DE PALENQUE");
INSERT INTO polls_municipio (id, nombre) VALUES (388, "TAMARA");
INSERT INTO polls_municipio (id, nombre) VALUES (389, "TAURAMENA");
INSERT INTO polls_municipio (id, nombre) VALUES (390, "TRINIDAD");
INSERT INTO polls_municipio (id, nombre) VALUES (391, "VILLANUEVA");
INSERT INTO polls_municipio (id, nombre) VALUES (392, "YOPAL");
INSERT INTO polls_municipio (id, nombre) VALUES (393, "ALMAGUER");
INSERT INTO polls_municipio (id, nombre) VALUES (394, "ARGELIA");
INSERT INTO polls_municipio (id, nombre) VALUES (395, "BALBOA");
INSERT INTO polls_municipio (id, nombre) VALUES (396, "BOLÍVAR");
INSERT INTO polls_municipio (id, nombre) VALUES (397, "BUENOS AIRES");
INSERT INTO polls_municipio (id, nombre) VALUES (398, "CAJIBIO");
INSERT INTO polls_municipio (id, nombre) VALUES (399, "CALDONO");
INSERT INTO polls_municipio (id, nombre) VALUES (400, "CALOTO");
INSERT INTO polls_municipio (id, nombre) VALUES (401, "CORINTO");
INSERT INTO polls_municipio (id, nombre) VALUES (402, "EL TAMBO");
INSERT INTO polls_municipio (id, nombre) VALUES (403, "FLORENCIA");
INSERT INTO polls_municipio (id, nombre) VALUES (404, "GUAPI");
INSERT INTO polls_municipio (id, nombre) VALUES (405, "INZA");
INSERT INTO polls_municipio (id, nombre) VALUES (406, "JAMBALÓ");
INSERT INTO polls_municipio (id, nombre) VALUES (407, "LA SIERRA");
INSERT INTO polls_municipio (id, nombre) VALUES (408, "LA VEGA");
INSERT INTO polls_municipio (id, nombre) VALUES (409, "LÓPEZ");
INSERT INTO polls_municipio (id, nombre) VALUES (410, "MERCADERES");
INSERT INTO polls_municipio (id, nombre) VALUES (411, "MIRANDA");
INSERT INTO polls_municipio (id, nombre) VALUES (412, "MORALES");
INSERT INTO polls_municipio (id, nombre) VALUES (413, "PADILLA");
INSERT INTO polls_municipio (id, nombre) VALUES (414, "PÁEZ");
INSERT INTO polls_municipio (id, nombre) VALUES (415, "PATIA (EL BORDO)");
INSERT INTO polls_municipio (id, nombre) VALUES (416, "PIAMONTE");
INSERT INTO polls_municipio (id, nombre) VALUES (417, "PIENDAMO");
INSERT INTO polls_municipio (id, nombre) VALUES (418, "POPAYÁN");
INSERT INTO polls_municipio (id, nombre) VALUES (419, "PUERTO TEJADA");
INSERT INTO polls_municipio (id, nombre) VALUES (420, "PURACE");
INSERT INTO polls_municipio (id, nombre) VALUES (421, "ROSAS");
INSERT INTO polls_municipio (id, nombre) VALUES (422, "SAN SEBASTIÁN");
INSERT INTO polls_municipio (id, nombre) VALUES (423, "SANTA ROSA");
INSERT INTO polls_municipio (id, nombre) VALUES (424, "SANTANDER DE QUILICHAO");
INSERT INTO polls_municipio (id, nombre) VALUES (425, "SILVIA");
INSERT INTO polls_municipio (id, nombre) VALUES (426, "SOTARA");
INSERT INTO polls_municipio (id, nombre) VALUES (427, "SUÁREZ");
INSERT INTO polls_municipio (id, nombre) VALUES (428, "SUCRE");
INSERT INTO polls_municipio (id, nombre) VALUES (429, "TIMBÍO");
INSERT INTO polls_municipio (id, nombre) VALUES (430, "TIMBIQUÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (431, "TORIBIO");
INSERT INTO polls_municipio (id, nombre) VALUES (432, "TOTORO");
INSERT INTO polls_municipio (id, nombre) VALUES (433, "VILLA RICA");
INSERT INTO polls_municipio (id, nombre) VALUES (434, "AGUACHICA");
INSERT INTO polls_municipio (id, nombre) VALUES (435, "AGUSTÍN CODAZZI");
INSERT INTO polls_municipio (id, nombre) VALUES (436, "ASTREA");
INSERT INTO polls_municipio (id, nombre) VALUES (437, "BECERRIL");
INSERT INTO polls_municipio (id, nombre) VALUES (438, "BOSCONIA");
INSERT INTO polls_municipio (id, nombre) VALUES (439, "CHIMICHAGUA");
INSERT INTO polls_municipio (id, nombre) VALUES (440, "CHIRIGUANÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (441, "CURUMANÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (442, "EL COPEY");
INSERT INTO polls_municipio (id, nombre) VALUES (443, "EL PASO");
INSERT INTO polls_municipio (id, nombre) VALUES (444, "GAMARRA");
INSERT INTO polls_municipio (id, nombre) VALUES (445, "GONZÁLEZ");
INSERT INTO polls_municipio (id, nombre) VALUES (446, "LA GLORIA");
INSERT INTO polls_municipio (id, nombre) VALUES (447, "LA JAGUA IBIRICO");
INSERT INTO polls_municipio (id, nombre) VALUES (448, "MANAURE BALCÓN DEL CESAR");
INSERT INTO polls_municipio (id, nombre) VALUES (449, "PAILITAS");
INSERT INTO polls_municipio (id, nombre) VALUES (450, "PELAYA");
INSERT INTO polls_municipio (id, nombre) VALUES (451, "PUEBLO BELLO");
INSERT INTO polls_municipio (id, nombre) VALUES (452, "RÍO DE ORO");
INSERT INTO polls_municipio (id, nombre) VALUES (453, "ROBLES (LA PAZ)");
INSERT INTO polls_municipio (id, nombre) VALUES (454, "SAN ALBERTO");
INSERT INTO polls_municipio (id, nombre) VALUES (455, "SAN DIEGO");
INSERT INTO polls_municipio (id, nombre) VALUES (456, "SAN MARTÍN");
INSERT INTO polls_municipio (id, nombre) VALUES (457, "TAMALAMEQUE");
INSERT INTO polls_municipio (id, nombre) VALUES (458, "VALLEDUPAR");
INSERT INTO polls_municipio (id, nombre) VALUES (459, "ACANDI");
INSERT INTO polls_municipio (id, nombre) VALUES (460, "ALTO BAUDO (PIE DE PATO)");
INSERT INTO polls_municipio (id, nombre) VALUES (461, "ATRATO");
INSERT INTO polls_municipio (id, nombre) VALUES (462, "BAGADO");
INSERT INTO polls_municipio (id, nombre) VALUES (463, "BAHIA SOLANO (MUTIS)");
INSERT INTO polls_municipio (id, nombre) VALUES (464, "BAJO BAUDO (PIZARRO)");
INSERT INTO polls_municipio (id, nombre) VALUES (465, "BOJAYA (BELLAVISTA)");
INSERT INTO polls_municipio (id, nombre) VALUES (466, "CANTON DE SAN PABLO");
INSERT INTO polls_municipio (id, nombre) VALUES (467, "CARMEN DEL DARIEN");
INSERT INTO polls_municipio (id, nombre) VALUES (468, "CERTEGUI");
INSERT INTO polls_municipio (id, nombre) VALUES (469, "CONDOTO");
INSERT INTO polls_municipio (id, nombre) VALUES (470, "EL CARMEN");
INSERT INTO polls_municipio (id, nombre) VALUES (471, "ISTMINA");
INSERT INTO polls_municipio (id, nombre) VALUES (472, "JURADO");
INSERT INTO polls_municipio (id, nombre) VALUES (473, "LITORAL DEL SAN JUAN");
INSERT INTO polls_municipio (id, nombre) VALUES (474, "LLORO");
INSERT INTO polls_municipio (id, nombre) VALUES (475, "MEDIO ATRATO");
INSERT INTO polls_municipio (id, nombre) VALUES (476, "MEDIO BAUDO (BOCA DE PEPE)");
INSERT INTO polls_municipio (id, nombre) VALUES (477, "MEDIO SAN JUAN");
INSERT INTO polls_municipio (id, nombre) VALUES (478, "NOVITA");
INSERT INTO polls_municipio (id, nombre) VALUES (479, "NUQUI");
INSERT INTO polls_municipio (id, nombre) VALUES (480, "QUIBDO");
INSERT INTO polls_municipio (id, nombre) VALUES (481, "RIO IRO");
INSERT INTO polls_municipio (id, nombre) VALUES (482, "RIO QUITO");
INSERT INTO polls_municipio (id, nombre) VALUES (483, "RIOSUCIO");
INSERT INTO polls_municipio (id, nombre) VALUES (484, "SAN JOSE DEL PALMAR");
INSERT INTO polls_municipio (id, nombre) VALUES (485, "SIPI");
INSERT INTO polls_municipio (id, nombre) VALUES (486, "TADO");
INSERT INTO polls_municipio (id, nombre) VALUES (487, "UNGUIA");
INSERT INTO polls_municipio (id, nombre) VALUES (488, "UNIÓN PANAMERICANA");
INSERT INTO polls_municipio (id, nombre) VALUES (489, "AYAPEL");
INSERT INTO polls_municipio (id, nombre) VALUES (490, "BUENAVISTA");
INSERT INTO polls_municipio (id, nombre) VALUES (491, "CANALETE");
INSERT INTO polls_municipio (id, nombre) VALUES (492, "CERETÉ");
INSERT INTO polls_municipio (id, nombre) VALUES (493, "CHIMA");
INSERT INTO polls_municipio (id, nombre) VALUES (494, "CHINÚ");
INSERT INTO polls_municipio (id, nombre) VALUES (495, "CIENAGA DE ORO");
INSERT INTO polls_municipio (id, nombre) VALUES (496, "COTORRA");
INSERT INTO polls_municipio (id, nombre) VALUES (497, "LA APARTADA");
INSERT INTO polls_municipio (id, nombre) VALUES (498, "LORICA");
INSERT INTO polls_municipio (id, nombre) VALUES (499, "LOS CÓRDOBAS");
INSERT INTO polls_municipio (id, nombre) VALUES (500, "MOMIL");
INSERT INTO polls_municipio (id, nombre) VALUES (501, "MONTELÍBANO");
INSERT INTO polls_municipio (id, nombre) VALUES (502, "MONTERÍA");
INSERT INTO polls_municipio (id, nombre) VALUES (503, "MOÑITOS");
INSERT INTO polls_municipio (id, nombre) VALUES (504, "PLANETA RICA");
INSERT INTO polls_municipio (id, nombre) VALUES (505, "PUEBLO NUEVO");
INSERT INTO polls_municipio (id, nombre) VALUES (506, "PUERTO ESCONDIDO");
INSERT INTO polls_municipio (id, nombre) VALUES (507, "PUERTO LIBERTADOR");
INSERT INTO polls_municipio (id, nombre) VALUES (508, "PURÍSIMA");
INSERT INTO polls_municipio (id, nombre) VALUES (509, "SAHAGÚN");
INSERT INTO polls_municipio (id, nombre) VALUES (510, "SAN ANDRÉS SOTAVENTO");
INSERT INTO polls_municipio (id, nombre) VALUES (511, "SAN ANTERO");
INSERT INTO polls_municipio (id, nombre) VALUES (512, "SAN BERNARDO VIENTO");
INSERT INTO polls_municipio (id, nombre) VALUES (513, "SAN CARLOS");
INSERT INTO polls_municipio (id, nombre) VALUES (514, "SAN PELAYO");
INSERT INTO polls_municipio (id, nombre) VALUES (515, "TIERRALTA");
INSERT INTO polls_municipio (id, nombre) VALUES (516, "VALENCIA");
INSERT INTO polls_municipio (id, nombre) VALUES (517, "AGUA DE DIOS");
INSERT INTO polls_municipio (id, nombre) VALUES (518, "ALBAN");
INSERT INTO polls_municipio (id, nombre) VALUES (519, "ANAPOIMA");
INSERT INTO polls_municipio (id, nombre) VALUES (520, "ANOLAIMA");
INSERT INTO polls_municipio (id, nombre) VALUES (521, "ARBELAEZ");
INSERT INTO polls_municipio (id, nombre) VALUES (522, "BELTRÁN");
INSERT INTO polls_municipio (id, nombre) VALUES (523, "BITUIMA");
INSERT INTO polls_municipio (id, nombre) VALUES (524, "BOGOTÁ DC");
INSERT INTO polls_municipio (id, nombre) VALUES (525, "BOJACÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (526, "CABRERA");
INSERT INTO polls_municipio (id, nombre) VALUES (527, "CACHIPAY");
INSERT INTO polls_municipio (id, nombre) VALUES (528, "CAJICÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (529, "CAPARRAPÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (530, "CAQUEZA");
INSERT INTO polls_municipio (id, nombre) VALUES (531, "CARMEN DE CARUPA");
INSERT INTO polls_municipio (id, nombre) VALUES (532, "CHAGUANÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (533, "CHIA");
INSERT INTO polls_municipio (id, nombre) VALUES (534, "CHIPAQUE");
INSERT INTO polls_municipio (id, nombre) VALUES (535, "CHOACHÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (536, "CHOCONTÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (537, "COGUA");
INSERT INTO polls_municipio (id, nombre) VALUES (538, "COTA");
INSERT INTO polls_municipio (id, nombre) VALUES (539, "CUCUNUBÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (540, "EL COLEGIO");
INSERT INTO polls_municipio (id, nombre) VALUES (541, "EL PEÑÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (542, "EL ROSAL1");
INSERT INTO polls_municipio (id, nombre) VALUES (543, "FACATATIVA");
INSERT INTO polls_municipio (id, nombre) VALUES (544, "FÓMEQUE");
INSERT INTO polls_municipio (id, nombre) VALUES (545, "FOSCA");
INSERT INTO polls_municipio (id, nombre) VALUES (546, "FUNZA");
INSERT INTO polls_municipio (id, nombre) VALUES (547, "FÚQUENE");
INSERT INTO polls_municipio (id, nombre) VALUES (548, "FUSAGASUGA");
INSERT INTO polls_municipio (id, nombre) VALUES (549, "GACHALÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (550, "GACHANCIPÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (551, "GACHETA");
INSERT INTO polls_municipio (id, nombre) VALUES (552, "GAMA");
INSERT INTO polls_municipio (id, nombre) VALUES (553, "GIRARDOT");
INSERT INTO polls_municipio (id, nombre) VALUES (554, "GRANADA2");
INSERT INTO polls_municipio (id, nombre) VALUES (555, "GUACHETÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (556, "GUADUAS");
INSERT INTO polls_municipio (id, nombre) VALUES (557, "GUASCA");
INSERT INTO polls_municipio (id, nombre) VALUES (558, "GUATAQUÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (559, "GUATAVITA");
INSERT INTO polls_municipio (id, nombre) VALUES (560, "GUAYABAL DE SIQUIMA");
INSERT INTO polls_municipio (id, nombre) VALUES (561, "GUAYABETAL");
INSERT INTO polls_municipio (id, nombre) VALUES (562, "GUTIÉRREZ");
INSERT INTO polls_municipio (id, nombre) VALUES (563, "JERUSALÉN");
INSERT INTO polls_municipio (id, nombre) VALUES (564, "JUNÍN");
INSERT INTO polls_municipio (id, nombre) VALUES (565, "LA CALERA");
INSERT INTO polls_municipio (id, nombre) VALUES (566, "LA MESA");
INSERT INTO polls_municipio (id, nombre) VALUES (567, "LA PALMA");
INSERT INTO polls_municipio (id, nombre) VALUES (568, "LA PEÑA");
INSERT INTO polls_municipio (id, nombre) VALUES (569, "LA VEGA");
INSERT INTO polls_municipio (id, nombre) VALUES (570, "LENGUAZAQUE");
INSERT INTO polls_municipio (id, nombre) VALUES (571, "MACHETÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (572, "MADRID");
INSERT INTO polls_municipio (id, nombre) VALUES (573, "MANTA");
INSERT INTO polls_municipio (id, nombre) VALUES (574, "MEDINA");
INSERT INTO polls_municipio (id, nombre) VALUES (575, "MOSQUERA");
INSERT INTO polls_municipio (id, nombre) VALUES (576, "NARIÑO");
INSERT INTO polls_municipio (id, nombre) VALUES (577, "NEMOCÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (578, "NILO");
INSERT INTO polls_municipio (id, nombre) VALUES (579, "NIMAIMA");
INSERT INTO polls_municipio (id, nombre) VALUES (580, "NOCAIMA");
INSERT INTO polls_municipio (id, nombre) VALUES (581, "OSPINA PÉREZ");
INSERT INTO polls_municipio (id, nombre) VALUES (582, "PACHO");
INSERT INTO polls_municipio (id, nombre) VALUES (583, "PAIME");
INSERT INTO polls_municipio (id, nombre) VALUES (584, "PANDI");
INSERT INTO polls_municipio (id, nombre) VALUES (585, "PARATEBUENO");
INSERT INTO polls_municipio (id, nombre) VALUES (586, "PASCA");
INSERT INTO polls_municipio (id, nombre) VALUES (587, "PUERTO SALGAR");
INSERT INTO polls_municipio (id, nombre) VALUES (588, "PULÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (589, "QUEBRADANEGRA");
INSERT INTO polls_municipio (id, nombre) VALUES (590, "QUETAME");
INSERT INTO polls_municipio (id, nombre) VALUES (591, "QUIPILE");
INSERT INTO polls_municipio (id, nombre) VALUES (592, "RAFAEL REYES");
INSERT INTO polls_municipio (id, nombre) VALUES (593, "RICAURTE");
INSERT INTO polls_municipio (id, nombre) VALUES (594, "SAN  ANTONIO DEL  TEQUENDAMA");
INSERT INTO polls_municipio (id, nombre) VALUES (595, "SAN BERNARDO");
INSERT INTO polls_municipio (id, nombre) VALUES (596, "SAN CAYETANO");
INSERT INTO polls_municipio (id, nombre) VALUES (597, "SAN FRANCISCO");
INSERT INTO polls_municipio (id, nombre) VALUES (598, "SAN JUAN DE RIOSECO");
INSERT INTO polls_municipio (id, nombre) VALUES (599, "SASAIMA");
INSERT INTO polls_municipio (id, nombre) VALUES (600, "SESQUILÉ");
INSERT INTO polls_municipio (id, nombre) VALUES (601, "SIBATÉ");
INSERT INTO polls_municipio (id, nombre) VALUES (602, "SILVANIA");
INSERT INTO polls_municipio (id, nombre) VALUES (603, "SIMIJACA");
INSERT INTO polls_municipio (id, nombre) VALUES (604, "SOACHA");
INSERT INTO polls_municipio (id, nombre) VALUES (605, "SOPO");
INSERT INTO polls_municipio (id, nombre) VALUES (606, "SUBACHOQUE");
INSERT INTO polls_municipio (id, nombre) VALUES (607, "SUESCA");
INSERT INTO polls_municipio (id, nombre) VALUES (608, "SUPATÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (609, "SUSA");
INSERT INTO polls_municipio (id, nombre) VALUES (610, "SUTATAUSA");
INSERT INTO polls_municipio (id, nombre) VALUES (611, "TABIO");
INSERT INTO polls_municipio (id, nombre) VALUES (612, "TAUSA");
INSERT INTO polls_municipio (id, nombre) VALUES (613, "TENA");
INSERT INTO polls_municipio (id, nombre) VALUES (614, "TENJO");
INSERT INTO polls_municipio (id, nombre) VALUES (615, "TIBACUY");
INSERT INTO polls_municipio (id, nombre) VALUES (616, "TIBIRITA");
INSERT INTO polls_municipio (id, nombre) VALUES (617, "TOCAIMA");
INSERT INTO polls_municipio (id, nombre) VALUES (618, "TOCANCIPÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (619, "TOPAIPÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (620, "UBALÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (621, "UBAQUE");
INSERT INTO polls_municipio (id, nombre) VALUES (622, "UBATÉ");
INSERT INTO polls_municipio (id, nombre) VALUES (623, "UNE");
INSERT INTO polls_municipio (id, nombre) VALUES (624, "UTICA");
INSERT INTO polls_municipio (id, nombre) VALUES (625, "VERGARA");
INSERT INTO polls_municipio (id, nombre) VALUES (626, "VIANI");
INSERT INTO polls_municipio (id, nombre) VALUES (627, "VILLA GOMEZ");
INSERT INTO polls_municipio (id, nombre) VALUES (628, "VILLA PINZÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (629, "VILLETA");
INSERT INTO polls_municipio (id, nombre) VALUES (630, "VIOTA");
INSERT INTO polls_municipio (id, nombre) VALUES (631, "YACOPÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (632, "ZIPACÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (633, "ZIPAQUIRÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (634, "BARRANCO MINAS");
INSERT INTO polls_municipio (id, nombre) VALUES (635, "CACAHUAL");
INSERT INTO polls_municipio (id, nombre) VALUES (636, "INÍRIDA");
INSERT INTO polls_municipio (id, nombre) VALUES (637, "LA GUADALUPE");
INSERT INTO polls_municipio (id, nombre) VALUES (638, "MAPIRIPANA");
INSERT INTO polls_municipio (id, nombre) VALUES (639, "MORICHAL");
INSERT INTO polls_municipio (id, nombre) VALUES (640, "PANA PANA");
INSERT INTO polls_municipio (id, nombre) VALUES (641, "PUERTO COLOMBIA");
INSERT INTO polls_municipio (id, nombre) VALUES (642, "SAN FELIPE");
INSERT INTO polls_municipio (id, nombre) VALUES (643, "CALAMAR");
INSERT INTO polls_municipio (id, nombre) VALUES (644, "EL RETORNO");
INSERT INTO polls_municipio (id, nombre) VALUES (645, "MIRAFLOREZ");
INSERT INTO polls_municipio (id, nombre) VALUES (646, "SAN JOSÉ DEL GUAVIARE");
INSERT INTO polls_municipio (id, nombre) VALUES (647, "ACEVEDO");
INSERT INTO polls_municipio (id, nombre) VALUES (648, "AGRADO");
INSERT INTO polls_municipio (id, nombre) VALUES (649, "AIPE");
INSERT INTO polls_municipio (id, nombre) VALUES (650, "ALGECIRAS");
INSERT INTO polls_municipio (id, nombre) VALUES (651, "ALTAMIRA");
INSERT INTO polls_municipio (id, nombre) VALUES (652, "BARAYA");
INSERT INTO polls_municipio (id, nombre) VALUES (653, "CAMPO ALEGRE");
INSERT INTO polls_municipio (id, nombre) VALUES (654, "COLOMBIA");
INSERT INTO polls_municipio (id, nombre) VALUES (655, "ELIAS");
INSERT INTO polls_municipio (id, nombre) VALUES (656, "GARZÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (657, "GIGANTE");
INSERT INTO polls_municipio (id, nombre) VALUES (658, "GUADALUPE");
INSERT INTO polls_municipio (id, nombre) VALUES (659, "HOBO");
INSERT INTO polls_municipio (id, nombre) VALUES (660, "IQUIRA");
INSERT INTO polls_municipio (id, nombre) VALUES (661, "ISNOS");
INSERT INTO polls_municipio (id, nombre) VALUES (662, "LA ARGENTINA");
INSERT INTO polls_municipio (id, nombre) VALUES (663, "LA PLATA");
INSERT INTO polls_municipio (id, nombre) VALUES (664, "NATAGA");
INSERT INTO polls_municipio (id, nombre) VALUES (665, "NEIVA");
INSERT INTO polls_municipio (id, nombre) VALUES (666, "OPORAPA");
INSERT INTO polls_municipio (id, nombre) VALUES (667, "PAICOL");
INSERT INTO polls_municipio (id, nombre) VALUES (668, "PALERMO");
INSERT INTO polls_municipio (id, nombre) VALUES (669, "PALESTINA");
INSERT INTO polls_municipio (id, nombre) VALUES (670, "PITAL");
INSERT INTO polls_municipio (id, nombre) VALUES (671, "PITALITO");
INSERT INTO polls_municipio (id, nombre) VALUES (672, "RIVERA");
INSERT INTO polls_municipio (id, nombre) VALUES (673, "SALADO BLANCO");
INSERT INTO polls_municipio (id, nombre) VALUES (674, "SAN AGUSTÍN");
INSERT INTO polls_municipio (id, nombre) VALUES (675, "SANTA MARIA");
INSERT INTO polls_municipio (id, nombre) VALUES (676, "SUAZA");
INSERT INTO polls_municipio (id, nombre) VALUES (677, "TARQUI");
INSERT INTO polls_municipio (id, nombre) VALUES (678, "TELLO");
INSERT INTO polls_municipio (id, nombre) VALUES (679, "TERUEL");
INSERT INTO polls_municipio (id, nombre) VALUES (680, "TESALIA");
INSERT INTO polls_municipio (id, nombre) VALUES (681, "TIMANA");
INSERT INTO polls_municipio (id, nombre) VALUES (682, "VILLAVIEJA");
INSERT INTO polls_municipio (id, nombre) VALUES (683, "YAGUARA");
INSERT INTO polls_municipio (id, nombre) VALUES (684, "ALBANIA");
INSERT INTO polls_municipio (id, nombre) VALUES (685, "BARRANCAS");
INSERT INTO polls_municipio (id, nombre) VALUES (686, "DIBULLA");
INSERT INTO polls_municipio (id, nombre) VALUES (687, "DISTRACCIÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (688, "EL MOLINO");
INSERT INTO polls_municipio (id, nombre) VALUES (689, "FONSECA");
INSERT INTO polls_municipio (id, nombre) VALUES (690, "HATO NUEVO");
INSERT INTO polls_municipio (id, nombre) VALUES (691, "LA JAGUA DEL PILAR");
INSERT INTO polls_municipio (id, nombre) VALUES (692, "MAICAO");
INSERT INTO polls_municipio (id, nombre) VALUES (693, "MANAURE");
INSERT INTO polls_municipio (id, nombre) VALUES (694, "RIOHACHA");
INSERT INTO polls_municipio (id, nombre) VALUES (695, "SAN JUAN DEL CESAR");
INSERT INTO polls_municipio (id, nombre) VALUES (696, "URIBIA");
INSERT INTO polls_municipio (id, nombre) VALUES (697, "URUMITA");
INSERT INTO polls_municipio (id, nombre) VALUES (698, "VILLANUEVA");
INSERT INTO polls_municipio (id, nombre) VALUES (699, "ALGARROBO");
INSERT INTO polls_municipio (id, nombre) VALUES (700, "ARACATACA");
INSERT INTO polls_municipio (id, nombre) VALUES (701, "ARIGUANI");
INSERT INTO polls_municipio (id, nombre) VALUES (702, "CERRO SAN ANTONIO");
INSERT INTO polls_municipio (id, nombre) VALUES (703, "CHIVOLO");
INSERT INTO polls_municipio (id, nombre) VALUES (704, "CIENAGA");
INSERT INTO polls_municipio (id, nombre) VALUES (705, "CONCORDIA");
INSERT INTO polls_municipio (id, nombre) VALUES (706, "EL BANCO");
INSERT INTO polls_municipio (id, nombre) VALUES (707, "EL PIÑON");
INSERT INTO polls_municipio (id, nombre) VALUES (708, "EL RETEN");
INSERT INTO polls_municipio (id, nombre) VALUES (709, "FUNDACION");
INSERT INTO polls_municipio (id, nombre) VALUES (710, "GUAMAL");
INSERT INTO polls_municipio (id, nombre) VALUES (711, "NUEVA GRANADA");
INSERT INTO polls_municipio (id, nombre) VALUES (712, "PEDRAZA");
INSERT INTO polls_municipio (id, nombre) VALUES (713, "PIJIÑO DEL CARMEN");
INSERT INTO polls_municipio (id, nombre) VALUES (714, "PIVIJAY");
INSERT INTO polls_municipio (id, nombre) VALUES (715, "PLATO");
INSERT INTO polls_municipio (id, nombre) VALUES (716, "PUEBLO VIEJO");
INSERT INTO polls_municipio (id, nombre) VALUES (717, "REMOLINO");
INSERT INTO polls_municipio (id, nombre) VALUES (718, "SABANAS DE SAN ANGEL");
INSERT INTO polls_municipio (id, nombre) VALUES (719, "SALAMINA");
INSERT INTO polls_municipio (id, nombre) VALUES (720, "SAN SEBASTIAN DE BUENAVISTA");
INSERT INTO polls_municipio (id, nombre) VALUES (721, "SAN ZENON");
INSERT INTO polls_municipio (id, nombre) VALUES (722, "SANTA ANA");
INSERT INTO polls_municipio (id, nombre) VALUES (723, "SANTA BARBARA DE PINTO");
INSERT INTO polls_municipio (id, nombre) VALUES (724, "SANTA MARTA");
INSERT INTO polls_municipio (id, nombre) VALUES (725, "SITIONUEVO");
INSERT INTO polls_municipio (id, nombre) VALUES (726, "TENERIFE");
INSERT INTO polls_municipio (id, nombre) VALUES (727, "ZAPAYAN");
INSERT INTO polls_municipio (id, nombre) VALUES (728, "ZONA BANANERA");
INSERT INTO polls_municipio (id, nombre) VALUES (729, "ACACIAS");
INSERT INTO polls_municipio (id, nombre) VALUES (730, "BARRANCA DE UPIA");
INSERT INTO polls_municipio (id, nombre) VALUES (731, "CABUYARO");
INSERT INTO polls_municipio (id, nombre) VALUES (732, "CASTILLA LA NUEVA");
INSERT INTO polls_municipio (id, nombre) VALUES (733, "CUBARRAL");
INSERT INTO polls_municipio (id, nombre) VALUES (734, "CUMARAL");
INSERT INTO polls_municipio (id, nombre) VALUES (735, "EL CALVARIO");
INSERT INTO polls_municipio (id, nombre) VALUES (736, "EL CASTILLO");
INSERT INTO polls_municipio (id, nombre) VALUES (737, "EL DORADO");
INSERT INTO polls_municipio (id, nombre) VALUES (738, "FUENTE DE ORO");
INSERT INTO polls_municipio (id, nombre) VALUES (739, "GRANADA");
INSERT INTO polls_municipio (id, nombre) VALUES (740, "GUAMAL");
INSERT INTO polls_municipio (id, nombre) VALUES (741, "LA MACARENA");
INSERT INTO polls_municipio (id, nombre) VALUES (742, "LA URIBE");
INSERT INTO polls_municipio (id, nombre) VALUES (743, "LEJANÍAS");
INSERT INTO polls_municipio (id, nombre) VALUES (744, "MAPIRIPÁN");
INSERT INTO polls_municipio (id, nombre) VALUES (745, "MESETAS");
INSERT INTO polls_municipio (id, nombre) VALUES (746, "PUERTO CONCORDIA");
INSERT INTO polls_municipio (id, nombre) VALUES (747, "PUERTO GAITÁN");
INSERT INTO polls_municipio (id, nombre) VALUES (748, "PUERTO LLERAS");
INSERT INTO polls_municipio (id, nombre) VALUES (749, "PUERTO LÓPEZ");
INSERT INTO polls_municipio (id, nombre) VALUES (750, "PUERTO RICO");
INSERT INTO polls_municipio (id, nombre) VALUES (751, "RESTREPO");
INSERT INTO polls_municipio (id, nombre) VALUES (752, "SAN  JUAN DE ARAMA");
INSERT INTO polls_municipio (id, nombre) VALUES (753, "SAN CARLOS GUAROA");
INSERT INTO polls_municipio (id, nombre) VALUES (754, "SAN JUANITO");
INSERT INTO polls_municipio (id, nombre) VALUES (755, "SAN MARTÍN");
INSERT INTO polls_municipio (id, nombre) VALUES (756, "VILLAVICENCIO");
INSERT INTO polls_municipio (id, nombre) VALUES (757, "VISTA HERMOSA");
INSERT INTO polls_municipio (id, nombre) VALUES (758, "ALBAN");
INSERT INTO polls_municipio (id, nombre) VALUES (759, "ALDAÑA");
INSERT INTO polls_municipio (id, nombre) VALUES (760, "ANCUYA");
INSERT INTO polls_municipio (id, nombre) VALUES (761, "ARBOLEDA");
INSERT INTO polls_municipio (id, nombre) VALUES (762, "BARBACOAS");
INSERT INTO polls_municipio (id, nombre) VALUES (763, "BELEN");
INSERT INTO polls_municipio (id, nombre) VALUES (764, "BUESACO");
INSERT INTO polls_municipio (id, nombre) VALUES (765, "CHACHAGUI");
INSERT INTO polls_municipio (id, nombre) VALUES (766, "COLON (GENOVA)");
INSERT INTO polls_municipio (id, nombre) VALUES (767, "CONSACA");
INSERT INTO polls_municipio (id, nombre) VALUES (768, "CONTADERO");
INSERT INTO polls_municipio (id, nombre) VALUES (769, "CORDOBA");
INSERT INTO polls_municipio (id, nombre) VALUES (770, "CUASPUD");
INSERT INTO polls_municipio (id, nombre) VALUES (771, "CUMBAL");
INSERT INTO polls_municipio (id, nombre) VALUES (772, "CUMBITARA");
INSERT INTO polls_municipio (id, nombre) VALUES (773, "EL CHARCO");
INSERT INTO polls_municipio (id, nombre) VALUES (774, "EL PEÑOL");
INSERT INTO polls_municipio (id, nombre) VALUES (775, "EL ROSARIO");
INSERT INTO polls_municipio (id, nombre) VALUES (776, "EL TABLÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (777, "EL TAMBO");
INSERT INTO polls_municipio (id, nombre) VALUES (778, "FUNES");
INSERT INTO polls_municipio (id, nombre) VALUES (779, "GUACHUCAL");
INSERT INTO polls_municipio (id, nombre) VALUES (780, "GUAITARILLA");
INSERT INTO polls_municipio (id, nombre) VALUES (781, "GUALMATAN");
INSERT INTO polls_municipio (id, nombre) VALUES (782, "ILES");
INSERT INTO polls_municipio (id, nombre) VALUES (783, "IMUES");
INSERT INTO polls_municipio (id, nombre) VALUES (784, "IPIALES");
INSERT INTO polls_municipio (id, nombre) VALUES (785, "LA CRUZ");
INSERT INTO polls_municipio (id, nombre) VALUES (786, "LA FLORIDA");
INSERT INTO polls_municipio (id, nombre) VALUES (787, "LA LLANADA");
INSERT INTO polls_municipio (id, nombre) VALUES (788, "LA TOLA");
INSERT INTO polls_municipio (id, nombre) VALUES (789, "LA UNION");
INSERT INTO polls_municipio (id, nombre) VALUES (790, "LEIVA");
INSERT INTO polls_municipio (id, nombre) VALUES (791, "LINARES");
INSERT INTO polls_municipio (id, nombre) VALUES (792, "LOS ANDES");
INSERT INTO polls_municipio (id, nombre) VALUES (793, "MAGUI");
INSERT INTO polls_municipio (id, nombre) VALUES (794, "MALLAMA");
INSERT INTO polls_municipio (id, nombre) VALUES (795, "MOSQUEZA");
INSERT INTO polls_municipio (id, nombre) VALUES (796, "NARIÑO");
INSERT INTO polls_municipio (id, nombre) VALUES (797, "OLAYA HERRERA");
INSERT INTO polls_municipio (id, nombre) VALUES (798, "OSPINA");
INSERT INTO polls_municipio (id, nombre) VALUES (799, "PASTO");
INSERT INTO polls_municipio (id, nombre) VALUES (800, "PIZARRO");
INSERT INTO polls_municipio (id, nombre) VALUES (801, "POLICARPA");
INSERT INTO polls_municipio (id, nombre) VALUES (802, "POTOSI");
INSERT INTO polls_municipio (id, nombre) VALUES (803, "PROVIDENCIA");
INSERT INTO polls_municipio (id, nombre) VALUES (804, "PUERRES");
INSERT INTO polls_municipio (id, nombre) VALUES (805, "PUPIALES");
INSERT INTO polls_municipio (id, nombre) VALUES (806, "RICAURTE");
INSERT INTO polls_municipio (id, nombre) VALUES (807, "ROBERTO PAYAN");
INSERT INTO polls_municipio (id, nombre) VALUES (808, "SAMANIEGO");
INSERT INTO polls_municipio (id, nombre) VALUES (809, "SAN BERNARDO");
INSERT INTO polls_municipio (id, nombre) VALUES (810, "SAN LORENZO");
INSERT INTO polls_municipio (id, nombre) VALUES (811, "SAN PABLO");
INSERT INTO polls_municipio (id, nombre) VALUES (812, "SAN PEDRO DE CARTAGO");
INSERT INTO polls_municipio (id, nombre) VALUES (813, "SANDONA");
INSERT INTO polls_municipio (id, nombre) VALUES (814, "SANTA BARBARA");
INSERT INTO polls_municipio (id, nombre) VALUES (815, "SANTACRUZ");
INSERT INTO polls_municipio (id, nombre) VALUES (816, "SAPUYES");
INSERT INTO polls_municipio (id, nombre) VALUES (817, "TAMINANGO");
INSERT INTO polls_municipio (id, nombre) VALUES (818, "TANGUA");
INSERT INTO polls_municipio (id, nombre) VALUES (819, "TUMACO");
INSERT INTO polls_municipio (id, nombre) VALUES (820, "TUQUERRES");
INSERT INTO polls_municipio (id, nombre) VALUES (821, "YACUANQUER");
INSERT INTO polls_municipio (id, nombre) VALUES (822, "ABREGO");
INSERT INTO polls_municipio (id, nombre) VALUES (823, "ARBOLEDAS");
INSERT INTO polls_municipio (id, nombre) VALUES (824, "BOCHALEMA");
INSERT INTO polls_municipio (id, nombre) VALUES (825, "BUCARASICA");
INSERT INTO polls_municipio (id, nombre) VALUES (826, "CÁCHIRA");
INSERT INTO polls_municipio (id, nombre) VALUES (827, "CÁCOTA");
INSERT INTO polls_municipio (id, nombre) VALUES (828, "CHINÁCOTA");
INSERT INTO polls_municipio (id, nombre) VALUES (829, "CHITAGÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (830, "CONVENCIÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (831, "CÚCUTA");
INSERT INTO polls_municipio (id, nombre) VALUES (832, "CUCUTILLA");
INSERT INTO polls_municipio (id, nombre) VALUES (833, "DURANIA");
INSERT INTO polls_municipio (id, nombre) VALUES (834, "EL CARMEN");
INSERT INTO polls_municipio (id, nombre) VALUES (835, "EL TARRA");
INSERT INTO polls_municipio (id, nombre) VALUES (836, "EL ZULIA");
INSERT INTO polls_municipio (id, nombre) VALUES (837, "GRAMALOTE");
INSERT INTO polls_municipio (id, nombre) VALUES (838, "HACARI");
INSERT INTO polls_municipio (id, nombre) VALUES (839, "HERRÁN");
INSERT INTO polls_municipio (id, nombre) VALUES (840, "LA ESPERANZA");
INSERT INTO polls_municipio (id, nombre) VALUES (841, "LA PLAYA");
INSERT INTO polls_municipio (id, nombre) VALUES (842, "LABATECA");
INSERT INTO polls_municipio (id, nombre) VALUES (843, "LOS PATIOS");
INSERT INTO polls_municipio (id, nombre) VALUES (844, "LOURDES");
INSERT INTO polls_municipio (id, nombre) VALUES (845, "MUTISCUA");
INSERT INTO polls_municipio (id, nombre) VALUES (846, "OCAÑA");
INSERT INTO polls_municipio (id, nombre) VALUES (847, "PAMPLONA");
INSERT INTO polls_municipio (id, nombre) VALUES (848, "PAMPLONITA");
INSERT INTO polls_municipio (id, nombre) VALUES (849, "PUERTO SANTANDER");
INSERT INTO polls_municipio (id, nombre) VALUES (850, "RAGONVALIA");
INSERT INTO polls_municipio (id, nombre) VALUES (851, "SALAZAR");
INSERT INTO polls_municipio (id, nombre) VALUES (852, "SAN CALIXTO");
INSERT INTO polls_municipio (id, nombre) VALUES (853, "SAN CAYETANO");
INSERT INTO polls_municipio (id, nombre) VALUES (854, "SANTIAGO");
INSERT INTO polls_municipio (id, nombre) VALUES (855, "SARDINATA");
INSERT INTO polls_municipio (id, nombre) VALUES (856, "SILOS");
INSERT INTO polls_municipio (id, nombre) VALUES (857, "TEORAMA");
INSERT INTO polls_municipio (id, nombre) VALUES (858, "TIBÚ");
INSERT INTO polls_municipio (id, nombre) VALUES (859, "TOLEDO");
INSERT INTO polls_municipio (id, nombre) VALUES (860, "VILLA CARO");
INSERT INTO polls_municipio (id, nombre) VALUES (861, "VILLA DEL ROSARIO");
INSERT INTO polls_municipio (id, nombre) VALUES (862, "COLÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (863, "MOCOA");
INSERT INTO polls_municipio (id, nombre) VALUES (864, "ORITO");
INSERT INTO polls_municipio (id, nombre) VALUES (865, "PUERTO ASÍS");
INSERT INTO polls_municipio (id, nombre) VALUES (866, "PUERTO CAYCEDO");
INSERT INTO polls_municipio (id, nombre) VALUES (867, "PUERTO GUZMÁN");
INSERT INTO polls_municipio (id, nombre) VALUES (868, "PUERTO LEGUÍZAMO");
INSERT INTO polls_municipio (id, nombre) VALUES (869, "SAN FRANCISCO");
INSERT INTO polls_municipio (id, nombre) VALUES (870, "SAN MIGUEL");
INSERT INTO polls_municipio (id, nombre) VALUES (871, "SANTIAGO");
INSERT INTO polls_municipio (id, nombre) VALUES (872, "SIBUNDOY");
INSERT INTO polls_municipio (id, nombre) VALUES (873, "VALLE DEL GUAMUEZ");
INSERT INTO polls_municipio (id, nombre) VALUES (874, "VILLAGARZÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (875, "ARMENIA");
INSERT INTO polls_municipio (id, nombre) VALUES (876, "BUENAVISTA");
INSERT INTO polls_municipio (id, nombre) VALUES (877, "CALARCÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (878, "CIRCASIA");
INSERT INTO polls_municipio (id, nombre) VALUES (879, "CÓRDOBA");
INSERT INTO polls_municipio (id, nombre) VALUES (880, "FILANDIA");
INSERT INTO polls_municipio (id, nombre) VALUES (881, "GÉNOVA");
INSERT INTO polls_municipio (id, nombre) VALUES (882, "LA TEBAIDA");
INSERT INTO polls_municipio (id, nombre) VALUES (883, "MONTENEGRO");
INSERT INTO polls_municipio (id, nombre) VALUES (884, "PIJAO");
INSERT INTO polls_municipio (id, nombre) VALUES (885, "QUIMBAYA");
INSERT INTO polls_municipio (id, nombre) VALUES (886, "SALENTO");
INSERT INTO polls_municipio (id, nombre) VALUES (887, "APIA");
INSERT INTO polls_municipio (id, nombre) VALUES (888, "BALBOA");
INSERT INTO polls_municipio (id, nombre) VALUES (889, "BELÉN DE UMBRÍA");
INSERT INTO polls_municipio (id, nombre) VALUES (890, "DOS QUEBRADAS");
INSERT INTO polls_municipio (id, nombre) VALUES (891, "GUATICA");
INSERT INTO polls_municipio (id, nombre) VALUES (892, "LA CELIA");
INSERT INTO polls_municipio (id, nombre) VALUES (893, "LA VIRGINIA");
INSERT INTO polls_municipio (id, nombre) VALUES (894, "MARSELLA");
INSERT INTO polls_municipio (id, nombre) VALUES (895, "MISTRATO");
INSERT INTO polls_municipio (id, nombre) VALUES (896, "PEREIRA");
INSERT INTO polls_municipio (id, nombre) VALUES (897, "PUEBLO RICO");
INSERT INTO polls_municipio (id, nombre) VALUES (898, "QUINCHÍA");
INSERT INTO polls_municipio (id, nombre) VALUES (899, "SANTA ROSA DE CABAL");
INSERT INTO polls_municipio (id, nombre) VALUES (900, "SANTUARIO");
INSERT INTO polls_municipio (id, nombre) VALUES (901, "PROVIDENCIA");
INSERT INTO polls_municipio (id, nombre) VALUES (902, "SAN ANDRES");
INSERT INTO polls_municipio (id, nombre) VALUES (903, "SANTA CATALINA");
INSERT INTO polls_municipio (id, nombre) VALUES (904, "AGUADA");
INSERT INTO polls_municipio (id, nombre) VALUES (905, "ALBANIA");
INSERT INTO polls_municipio (id, nombre) VALUES (906, "ARATOCA");
INSERT INTO polls_municipio (id, nombre) VALUES (907, "BARBOSA");
INSERT INTO polls_municipio (id, nombre) VALUES (908, "BARICHARA");
INSERT INTO polls_municipio (id, nombre) VALUES (909, "BARRANCABERMEJA");
INSERT INTO polls_municipio (id, nombre) VALUES (910, "BETULIA");
INSERT INTO polls_municipio (id, nombre) VALUES (911, "BOLÍVAR");
INSERT INTO polls_municipio (id, nombre) VALUES (912, "BUCARAMANGA");
INSERT INTO polls_municipio (id, nombre) VALUES (913, "CABRERA");
INSERT INTO polls_municipio (id, nombre) VALUES (914, "CALIFORNIA");
INSERT INTO polls_municipio (id, nombre) VALUES (915, "CAPITANEJO");
INSERT INTO polls_municipio (id, nombre) VALUES (916, "CARCASI");
INSERT INTO polls_municipio (id, nombre) VALUES (917, "CEPITA");
INSERT INTO polls_municipio (id, nombre) VALUES (918, "CERRITO");
INSERT INTO polls_municipio (id, nombre) VALUES (919, "CHARALÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (920, "CHARTA");
INSERT INTO polls_municipio (id, nombre) VALUES (921, "CHIMA");
INSERT INTO polls_municipio (id, nombre) VALUES (922, "CHIPATÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (923, "CIMITARRA");
INSERT INTO polls_municipio (id, nombre) VALUES (924, "CONCEPCIÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (925, "CONFINES");
INSERT INTO polls_municipio (id, nombre) VALUES (926, "CONTRATACIÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (927, "COROMORO");
INSERT INTO polls_municipio (id, nombre) VALUES (928, "CURITÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (929, "EL CARMEN");
INSERT INTO polls_municipio (id, nombre) VALUES (930, "EL GUACAMAYO");
INSERT INTO polls_municipio (id, nombre) VALUES (931, "EL PEÑÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (932, "EL PLAYÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (933, "ENCINO");
INSERT INTO polls_municipio (id, nombre) VALUES (934, "ENCISO");
INSERT INTO polls_municipio (id, nombre) VALUES (935, "FLORIÁN");
INSERT INTO polls_municipio (id, nombre) VALUES (936, "FLORIDABLANCA");
INSERT INTO polls_municipio (id, nombre) VALUES (937, "GALÁN");
INSERT INTO polls_municipio (id, nombre) VALUES (938, "GAMBITA");
INSERT INTO polls_municipio (id, nombre) VALUES (939, "GIRÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (940, "GUACA");
INSERT INTO polls_municipio (id, nombre) VALUES (941, "GUADALUPE");
INSERT INTO polls_municipio (id, nombre) VALUES (942, "GUAPOTA");
INSERT INTO polls_municipio (id, nombre) VALUES (943, "GUAVATÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (944, "GUEPSA");
INSERT INTO polls_municipio (id, nombre) VALUES (945, "HATO");
INSERT INTO polls_municipio (id, nombre) VALUES (946, "JESÚS MARIA");
INSERT INTO polls_municipio (id, nombre) VALUES (947, "JORDÁN");
INSERT INTO polls_municipio (id, nombre) VALUES (948, "LA BELLEZA");
INSERT INTO polls_municipio (id, nombre) VALUES (949, "LA PAZ");
INSERT INTO polls_municipio (id, nombre) VALUES (950, "LANDAZURI");
INSERT INTO polls_municipio (id, nombre) VALUES (951, "LEBRIJA");
INSERT INTO polls_municipio (id, nombre) VALUES (952, "LOS SANTOS");
INSERT INTO polls_municipio (id, nombre) VALUES (953, "MACARAVITA");
INSERT INTO polls_municipio (id, nombre) VALUES (954, "MÁLAGA");
INSERT INTO polls_municipio (id, nombre) VALUES (955, "MATANZA");
INSERT INTO polls_municipio (id, nombre) VALUES (956, "MOGOTES");
INSERT INTO polls_municipio (id, nombre) VALUES (957, "MOLAGAVITA");
INSERT INTO polls_municipio (id, nombre) VALUES (958, "OCAMONTE");
INSERT INTO polls_municipio (id, nombre) VALUES (959, "OIBA");
INSERT INTO polls_municipio (id, nombre) VALUES (960, "ONZAGA");
INSERT INTO polls_municipio (id, nombre) VALUES (961, "PALMAR");
INSERT INTO polls_municipio (id, nombre) VALUES (962, "PALMAS DEL SOCORRO");
INSERT INTO polls_municipio (id, nombre) VALUES (963, "PÁRAMO");
INSERT INTO polls_municipio (id, nombre) VALUES (964, "PIEDECUESTA");
INSERT INTO polls_municipio (id, nombre) VALUES (965, "PINCHOTE");
INSERT INTO polls_municipio (id, nombre) VALUES (966, "PUENTE NACIONAL");
INSERT INTO polls_municipio (id, nombre) VALUES (967, "PUERTO PARRA");
INSERT INTO polls_municipio (id, nombre) VALUES (968, "PUERTO WILCHES");
INSERT INTO polls_municipio (id, nombre) VALUES (969, "RIONEGRO");
INSERT INTO polls_municipio (id, nombre) VALUES (970, "SABANA DE TORRES");
INSERT INTO polls_municipio (id, nombre) VALUES (971, "SAN ANDRÉS");
INSERT INTO polls_municipio (id, nombre) VALUES (972, "SAN BENITO");
INSERT INTO polls_municipio (id, nombre) VALUES (973, "SAN GIL");
INSERT INTO polls_municipio (id, nombre) VALUES (974, "SAN JOAQUÍN");
INSERT INTO polls_municipio (id, nombre) VALUES (975, "SAN JOSÉ DE MIRANDA");
INSERT INTO polls_municipio (id, nombre) VALUES (976, "SAN MIGUEL");
INSERT INTO polls_municipio (id, nombre) VALUES (977, "SAN VICENTE DE CHUCURÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (978, "SANTA BÁRBARA");
INSERT INTO polls_municipio (id, nombre) VALUES (979, "SANTA HELENA");
INSERT INTO polls_municipio (id, nombre) VALUES (980, "SIMACOTA");
INSERT INTO polls_municipio (id, nombre) VALUES (981, "SOCORRO");
INSERT INTO polls_municipio (id, nombre) VALUES (982, "SUAITA");
INSERT INTO polls_municipio (id, nombre) VALUES (983, "SUCRE");
INSERT INTO polls_municipio (id, nombre) VALUES (984, "SURATA");
INSERT INTO polls_municipio (id, nombre) VALUES (985, "TONA");
INSERT INTO polls_municipio (id, nombre) VALUES (986, "VALLE SAN JOSÉ");
INSERT INTO polls_municipio (id, nombre) VALUES (987, "VÉLEZ");
INSERT INTO polls_municipio (id, nombre) VALUES (988, "VETAS");
INSERT INTO polls_municipio (id, nombre) VALUES (989, "VILLANUEVA");
INSERT INTO polls_municipio (id, nombre) VALUES (990, "ZAPATOCA");
INSERT INTO polls_municipio (id, nombre) VALUES (991, "BUENAVISTA");
INSERT INTO polls_municipio (id, nombre) VALUES (992, "CAIMITO");
INSERT INTO polls_municipio (id, nombre) VALUES (993, "CHALÁN");
INSERT INTO polls_municipio (id, nombre) VALUES (994, "COLOSO");
INSERT INTO polls_municipio (id, nombre) VALUES (995, "COROZAL");
INSERT INTO polls_municipio (id, nombre) VALUES (996, "EL ROBLE");
INSERT INTO polls_municipio (id, nombre) VALUES (997, "GALERAS");
INSERT INTO polls_municipio (id, nombre) VALUES (998, "GUARANDA");
INSERT INTO polls_municipio (id, nombre) VALUES (999, "LA UNIÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (1000, "LOS PALMITOS");
INSERT INTO polls_municipio (id, nombre) VALUES (1001, "MAJAGUAL");
INSERT INTO polls_municipio (id, nombre) VALUES (1002, "MORROA");
INSERT INTO polls_municipio (id, nombre) VALUES (1003, "OVEJAS");
INSERT INTO polls_municipio (id, nombre) VALUES (1004, "PALMITO");
INSERT INTO polls_municipio (id, nombre) VALUES (1005, "SAMPUES");
INSERT INTO polls_municipio (id, nombre) VALUES (1006, "SAN BENITO ABAD");
INSERT INTO polls_municipio (id, nombre) VALUES (1007, "SAN JUAN DE BETULIA");
INSERT INTO polls_municipio (id, nombre) VALUES (1008, "SAN MARCOS");
INSERT INTO polls_municipio (id, nombre) VALUES (1009, "SAN ONOFRE");
INSERT INTO polls_municipio (id, nombre) VALUES (1010, "SAN PEDRO");
INSERT INTO polls_municipio (id, nombre) VALUES (1011, "SINCÉ");
INSERT INTO polls_municipio (id, nombre) VALUES (1012, "SINCELEJO");
INSERT INTO polls_municipio (id, nombre) VALUES (1013, "SUCRE");
INSERT INTO polls_municipio (id, nombre) VALUES (1014, "TOLÚ");
INSERT INTO polls_municipio (id, nombre) VALUES (1015, "TOLUVIEJO");
INSERT INTO polls_municipio (id, nombre) VALUES (1016, "ALPUJARRA");
INSERT INTO polls_municipio (id, nombre) VALUES (1017, "ALVARADO");
INSERT INTO polls_municipio (id, nombre) VALUES (1018, "AMBALEMA");
INSERT INTO polls_municipio (id, nombre) VALUES (1019, "ANZOATEGUI");
INSERT INTO polls_municipio (id, nombre) VALUES (1020, "ARMERO (GUAYABAL)");
INSERT INTO polls_municipio (id, nombre) VALUES (1021, "ATACO");
INSERT INTO polls_municipio (id, nombre) VALUES (1022, "CAJAMARCA");
INSERT INTO polls_municipio (id, nombre) VALUES (1023, "CARMEN DE APICALÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (1024, "CASABIANCA");
INSERT INTO polls_municipio (id, nombre) VALUES (1025, "CHAPARRAL");
INSERT INTO polls_municipio (id, nombre) VALUES (1026, "COELLO");
INSERT INTO polls_municipio (id, nombre) VALUES (1027, "COYAIMA");
INSERT INTO polls_municipio (id, nombre) VALUES (1028, "CUNDAY");
INSERT INTO polls_municipio (id, nombre) VALUES (1029, "DOLORES");
INSERT INTO polls_municipio (id, nombre) VALUES (1030, "ESPINAL");
INSERT INTO polls_municipio (id, nombre) VALUES (1031, "FALÁN");
INSERT INTO polls_municipio (id, nombre) VALUES (1032, "FLANDES");
INSERT INTO polls_municipio (id, nombre) VALUES (1033, "FRESNO");
INSERT INTO polls_municipio (id, nombre) VALUES (1034, "GUAMO");
INSERT INTO polls_municipio (id, nombre) VALUES (1035, "HERVEO");
INSERT INTO polls_municipio (id, nombre) VALUES (1036, "HONDA");
INSERT INTO polls_municipio (id, nombre) VALUES (1037, "IBAGUÉ");
INSERT INTO polls_municipio (id, nombre) VALUES (1038, "ICONONZO");
INSERT INTO polls_municipio (id, nombre) VALUES (1039, "LÉRIDA");
INSERT INTO polls_municipio (id, nombre) VALUES (1040, "LÍBANO");
INSERT INTO polls_municipio (id, nombre) VALUES (1041, "MARIQUITA");
INSERT INTO polls_municipio (id, nombre) VALUES (1042, "MELGAR");
INSERT INTO polls_municipio (id, nombre) VALUES (1043, "MURILLO");
INSERT INTO polls_municipio (id, nombre) VALUES (1044, "NATAGAIMA");
INSERT INTO polls_municipio (id, nombre) VALUES (1045, "ORTEGA");
INSERT INTO polls_municipio (id, nombre) VALUES (1046, "PALOCABILDO");
INSERT INTO polls_municipio (id, nombre) VALUES (1047, "PIEDRAS PLANADAS");
INSERT INTO polls_municipio (id, nombre) VALUES (1048, "PRADO");
INSERT INTO polls_municipio (id, nombre) VALUES (1049, "PURIFICACIÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (1050, "RIOBLANCO");
INSERT INTO polls_municipio (id, nombre) VALUES (1051, "RONCESVALLES");
INSERT INTO polls_municipio (id, nombre) VALUES (1052, "ROVIRA");
INSERT INTO polls_municipio (id, nombre) VALUES (1053, "SALDAÑA");
INSERT INTO polls_municipio (id, nombre) VALUES (1054, "SAN ANTONIO");
INSERT INTO polls_municipio (id, nombre) VALUES (1055, "SAN LUIS");
INSERT INTO polls_municipio (id, nombre) VALUES (1056, "SANTA ISABEL");
INSERT INTO polls_municipio (id, nombre) VALUES (1057, "SUÁREZ");
INSERT INTO polls_municipio (id, nombre) VALUES (1058, "VALLE DE SAN JUAN");
INSERT INTO polls_municipio (id, nombre) VALUES (1059, "VENADILLO");
INSERT INTO polls_municipio (id, nombre) VALUES (1060, "VILLAHERMOSA");
INSERT INTO polls_municipio (id, nombre) VALUES (1061, "VILLARRICA");
INSERT INTO polls_municipio (id, nombre) VALUES (1062, "ALCALÁ");
INSERT INTO polls_municipio (id, nombre) VALUES (1063, "ANDALUCÍA");
INSERT INTO polls_municipio (id, nombre) VALUES (1064, "ANSERMA NUEVO");
INSERT INTO polls_municipio (id, nombre) VALUES (1065, "ARGELIA");
INSERT INTO polls_municipio (id, nombre) VALUES (1066, "BOLÍVAR");
INSERT INTO polls_municipio (id, nombre) VALUES (1067, "BUENAVENTURA");
INSERT INTO polls_municipio (id, nombre) VALUES (1068, "BUGA");
INSERT INTO polls_municipio (id, nombre) VALUES (1069, "BUGALAGRANDE");
INSERT INTO polls_municipio (id, nombre) VALUES (1070, "CAICEDONIA");
INSERT INTO polls_municipio (id, nombre) VALUES (1071, "CALI");
INSERT INTO polls_municipio (id, nombre) VALUES (1072, "CALIMA (DARIEN)");
INSERT INTO polls_municipio (id, nombre) VALUES (1073, "CANDELARIA");
INSERT INTO polls_municipio (id, nombre) VALUES (1074, "CARTAGO");
INSERT INTO polls_municipio (id, nombre) VALUES (1075, "DAGUA");
INSERT INTO polls_municipio (id, nombre) VALUES (1076, "EL AGUILA");
INSERT INTO polls_municipio (id, nombre) VALUES (1077, "EL CAIRO");
INSERT INTO polls_municipio (id, nombre) VALUES (1078, "EL CERRITO");
INSERT INTO polls_municipio (id, nombre) VALUES (1079, "EL DOVIO");
INSERT INTO polls_municipio (id, nombre) VALUES (1080, "FLORIDA");
INSERT INTO polls_municipio (id, nombre) VALUES (1081, "GINEBRA GUACARI");
INSERT INTO polls_municipio (id, nombre) VALUES (1082, "JAMUNDÍ");
INSERT INTO polls_municipio (id, nombre) VALUES (1083, "LA CUMBRE");
INSERT INTO polls_municipio (id, nombre) VALUES (1084, "LA UNIÓN");
INSERT INTO polls_municipio (id, nombre) VALUES (1085, "LA VICTORIA");
INSERT INTO polls_municipio (id, nombre) VALUES (1086, "OBANDO");
INSERT INTO polls_municipio (id, nombre) VALUES (1087, "PALMIRA");
INSERT INTO polls_municipio (id, nombre) VALUES (1088, "PRADERA");
INSERT INTO polls_municipio (id, nombre) VALUES (1089, "RESTREPO");
INSERT INTO polls_municipio (id, nombre) VALUES (1090, "RIO FRÍO");
INSERT INTO polls_municipio (id, nombre) VALUES (1091, "ROLDANILLO");
INSERT INTO polls_municipio (id, nombre) VALUES (1092, "SAN PEDRO");
INSERT INTO polls_municipio (id, nombre) VALUES (1093, "SEVILLA");
INSERT INTO polls_municipio (id, nombre) VALUES (1094, "TORO");
INSERT INTO polls_municipio (id, nombre) VALUES (1095, "TRUJILLO");
INSERT INTO polls_municipio (id, nombre) VALUES (1096, "TULÚA");
INSERT INTO polls_municipio (id, nombre) VALUES (1097, "ULLOA");
INSERT INTO polls_municipio (id, nombre) VALUES (1098, "VERSALLES");
INSERT INTO polls_municipio (id, nombre) VALUES (1099, "VIJES");
INSERT INTO polls_municipio (id, nombre) VALUES (1100, "YOTOCO");
INSERT INTO polls_municipio (id, nombre) VALUES (1101, "YUMBO");
INSERT INTO polls_municipio (id, nombre) VALUES (1102, "ZARZAL");
INSERT INTO polls_municipio (id, nombre) VALUES (1103, "CARURÚ");
INSERT INTO polls_municipio (id, nombre) VALUES (1104, "MITÚ");
INSERT INTO polls_municipio (id, nombre) VALUES (1105, "PACOA");
INSERT INTO polls_municipio (id, nombre) VALUES (1106, "PAPUNAUA");
INSERT INTO polls_municipio (id, nombre) VALUES (1107, "TARAIRA");
INSERT INTO polls_municipio (id, nombre) VALUES (1108, "YAVARATÉ");
INSERT INTO polls_municipio (id, nombre) VALUES (1109, "CUMARIBO");
INSERT INTO polls_municipio (id, nombre) VALUES (1110, "LA PRIMAVERA");
INSERT INTO polls_municipio (id, nombre) VALUES (1111, "PUERTO CARREÑO");
INSERT INTO polls_municipio (id, nombre) VALUES (1112, "SANTA ROSALIA");