INSERT INTO polls_pollsection VALUES(1,'I. CARACTERÍSTICAS DE ACTITUDES HACIA VIVIR/MORIR',1,1);
INSERT INTO polls_pollsection VALUES(2,'II. CARACTERÍSTICAS DEL DESEO/IDEACION DE SUICIDIO',2,1);
INSERT INTO polls_pollsection VALUES(3,'III. CARACTERÍSTICAS DEL INTENTO EN CUESTIÓN',3,1);
INSERT INTO polls_pollsection VALUES(4,'IV. ACTUALIZACIÓN DEL INTENTO EN CUESTIÓN',4,1);
INSERT INTO polls_pollsection VALUES(5,'V. FACTORES PREVIOS (no incluibles en la puntuación total)',5,1);
