INSERT INTO polls_question VALUES(2,'Deseo de vivir',1,'Elija una de las opciones y presione "Continuar".',1,1);
INSERT INTO polls_question VALUES(3,'Deseo de morir',2,'Elija una de las opciones y presione "Continuar".',1,1);
INSERT INTO polls_question VALUES(4,'Razones para vivir/morir',3,'Elija una de las opciones y presione "Continuar".',1,1);
INSERT INTO polls_question VALUES(5,'Deseo de efectuar un intento activo de suicidio',4,'Elija una de las opciones y presione "Continuar".',1,1);
INSERT INTO polls_question VALUES(6,'Intento pasivo de suicidio',5,'Elija una de las opciones y presione "Continuar".',1,1);
INSERT INTO polls_question VALUES(7,'Dimensión temporal: Duración',6,'Elija una de las opciones y presione "Continuar".',1,2);
INSERT INTO polls_question VALUES(8,'Dimensión temporal: frecuencia',7,'Elija una de las opciones y presione "Continuar".',1,2);
INSERT INTO polls_question VALUES(9,'Actitud hacia la ideación/deseo',8,'Elija una de las opciones y presione "Continuar".',1,2);
INSERT INTO polls_question VALUES(10,'Control sobre el deseo de actuación o acto suicida',9,'Elija una de las opciones y presione "Continuar".',1,2);
INSERT INTO polls_question VALUES(11,'Barreras para el intento activo (por ejemplo: la familia, religión, posibilidad de lesión grave si se fracasa; irreversibilidad del intento)',10,'Elija una de las opciones y presione "Continuar".',1,2);
INSERT INTO polls_question VALUES(12,'Razón del intento en cuestión',11,'Elija una de las opciones y presione "Continuar".',1,2);
INSERT INTO polls_question VALUES(13,'Método: Especificidad/planeación',12,'Elija una de las opciones y presione "Continuar".',1,3);
INSERT INTO polls_question VALUES(14,'Método: Disponibilidad/oportunidad',13,'Elija una de las opciones y presione "Continuar".',1,3);
INSERT INTO polls_question VALUES(15,'Sensación de «capacidad» para llevar a cabo un intento',14,'Elija una de las opciones y presione "Continuar".',1,3);
INSERT INTO polls_question VALUES(16,'Expectativas/anticipación del intento real',15,'Elija una de las opciones y presione "Continuar".',1,3);
INSERT INTO polls_question VALUES(17,'Preparación real',16,'Elija una de las opciones y presione "Continuar".',1,4);
INSERT INTO polls_question VALUES(18,'Nota de suicidio',17,'Elija una de las opciones y presione "Continuar".',1,4);
INSERT INTO polls_question VALUES(19,'Actos finales de anticipación de la muerte (por ejemplo: seguros, testamento, donaciones)',18,'Elija una de las opciones y presione "Continuar".',1,4);
INSERT INTO polls_question VALUES(20,'Engaño/encubrimiento del engaño',19,'Elija una de las opciones y presione "Continuar".',1,4);
INSERT INTO polls_question VALUES(21,'Intentos previos de suicidio',20,'Elija una de las opciones y presione "Continuar".',1,5);
INSERT INTO polls_question VALUES(22,'Intención de morir asociada con el último intento',21,'Elija una de las opciones y presione "Continuar".',1,5);
