INSERT INTO "polls_option" VALUES(1,'0: Moderado a fuerte',1,2);
INSERT INTO "polls_option" VALUES(2,'1: Débil',2,2);
INSERT INTO "polls_option" VALUES(3,'2: Ninguno',3,2);
INSERT INTO "polls_option" VALUES(4,'0: Ninguno',1,3);
INSERT INTO "polls_option" VALUES(5,'1: Débil',2,3);
INSERT INTO "polls_option" VALUES(6,'2: Moderado a fuerte',3,3);
INSERT INTO "polls_option" VALUES(7,'0: Las de vivir superan a las de morir',1,4);
INSERT INTO "polls_option" VALUES(8,'1: Mas o menos igual',2,4);
INSERT INTO "polls_option" VALUES(9,'2: Las de morir superan a las de vivir',3,4);
INSERT INTO "polls_option" VALUES(10,'0: Ninguno',1,5);
INSERT INTO "polls_option" VALUES(11,'1: Débil',2,5);
INSERT INTO "polls_option" VALUES(12,'2: Moderado a fuerte',3,5);
INSERT INTO "polls_option" VALUES(13,'0: Tomaría precauciones para salvar la vida',1,6);
INSERT INTO "polls_option" VALUES(14,'1: Dejaría al azar la vida o la muerte (por ejemplo, cruzar sin mirar una calle)',2,6);
INSERT INTO "polls_option" VALUES(15,'2: Evitaria las medidas necesarias para salvar o mantener la vida (por ejemplo, un diabético que deja de tomar insulina)',3,6);
INSERT INTO "polls_option" VALUES(16,'0: Breve, períodos fugaces',1,7);
INSERT INTO "polls_option" VALUES(17,'1: Períodos más largos',2,7);
INSERT INTO "polls_option" VALUES(18,'2: Continuo (crónico) o casi continuo',3,7);
INSERT INTO "polls_option" VALUES(19,'0: Infrecuente, ocasional',1,8);
INSERT INTO "polls_option" VALUES(20,'1: Intermitente',2,8);
INSERT INTO "polls_option" VALUES(21,'2: Persistente o continua',3,8);
INSERT INTO "polls_option" VALUES(22,'0: Rechazo',1,9);
INSERT INTO "polls_option" VALUES(23,'1: Ambivalente; indiferente',2,9);
INSERT INTO "polls_option" VALUES(24,'2: Aceptación',3,9);
INSERT INTO "polls_option" VALUES(25,'0: Tiene sensación de control',1,10);
INSERT INTO "polls_option" VALUES(26,'1: Inseguro del control',2,10);
INSERT INTO "polls_option" VALUES(27,'2: No tiene sensación de control',3,10);
INSERT INTO "polls_option" VALUES(28,'0: No intentaría suicidio a causa de una barrera',1,11);
INSERT INTO "polls_option" VALUES(29,'1: Alguna preocupación sobre las barreras',2,11);
INSERT INTO "polls_option" VALUES(30,'2: Mínima o nula preocupación sobre las barreras',3,11);
INSERT INTO "polls_option" VALUES(31,'0: Manipular el entorno: Conseguir atención, venganza',1,12);
INSERT INTO "polls_option" VALUES(32,'1: Combinación de «1» y «2»',2,12);
INSERT INTO "polls_option" VALUES(33,'2: Escape, resolver problemas, desaparecer',3,12);
INSERT INTO "polls_option" VALUES(34,'0: No en cuestión',1,13);
INSERT INTO "polls_option" VALUES(35,'1: Considerado pero sin elaborar detalles',2,13);
INSERT INTO "polls_option" VALUES(36,'2: Detalles bien elaborados; bien formulado',3,13);
INSERT INTO "polls_option" VALUES(37,'0: Método no disponible; ninguna oportunidad',1,14);
INSERT INTO "polls_option" VALUES(38,'1: El método llevaría tiempo/esfuerzo; oportunidad no fácilmente disponible',2,14);
INSERT INTO "polls_option" VALUES(39,'2: Oportunidad futura o anticipada disponibilidad de método',3,14);
INSERT INTO "polls_option" VALUES(40,'0: Cobarde, demasiado débil, asustado, incapaz',1,15);
INSERT INTO "polls_option" VALUES(41,'1: Inseguro de la valentía o de la capacidad',2,15);
INSERT INTO "polls_option" VALUES(42,'2: Seguro de la valentía o de la capacidad',3,15);
INSERT INTO "polls_option" VALUES(43,'0: No',1,16);
INSERT INTO "polls_option" VALUES(44,'1: Inciertas, no seguro',2,16);
INSERT INTO "polls_option" VALUES(45,'2: Sí',3,16);
INSERT INTO "polls_option" VALUES(46,'0: Ninguno',1,21);
INSERT INTO "polls_option" VALUES(47,'1: Uno',2,21);
INSERT INTO "polls_option" VALUES(48,'2: Más de uno',3,21);
INSERT INTO "polls_option" VALUES(49,'0: Baja',1,22);
INSERT INTO "polls_option" VALUES(50,' 1: Moderada; ambivalente; incierta',2,22);
INSERT INTO "polls_option" VALUES(51,'2: Alta',3,22);
INSERT INTO "polls_option" VALUES(52,'0: Ninguna',1,17);
INSERT INTO "polls_option" VALUES(53,'1: Parcial (por ejemplo, comenzar a acumular pastillas)',2,17);
INSERT INTO "polls_option" VALUES(54,'2: Completa (por ejemplo, tiene pastillas, cuchillas, un arma cargada)',3,17);
INSERT INTO "polls_option" VALUES(55,'0: Ninguna',1,18);
INSERT INTO "polls_option" VALUES(56,'1: Comenzada pero no acabada; sólo se ha pensado en ella',2,18);
INSERT INTO "polls_option" VALUES(57,'2: Acabada',3,18);
INSERT INTO "polls_option" VALUES(58,'0: Ninguno',1,19);
INSERT INTO "polls_option" VALUES(59,'1: Algunas ideas o se han hecho algunas gestiones',2,19);
INSERT INTO "polls_option" VALUES(60,'2: Planes finales efectuados o gestiones finalizadas',3,19);
INSERT INTO "polls_option" VALUES(61,'0: Ideas expresadas abiertamente',1,20);
INSERT INTO "polls_option" VALUES(62,'1: Ideas reservadas',2,20);
INSERT INTO "polls_option" VALUES(63,'2: Intento de engañar, mentir, encubrir',3,20);
